namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateHu(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Evernote Export",
        "Settings" => "Beállítások elemre",
        "Save" => "Megtakarítás",
        "Cancel" => "Mégse",
        "App:" => "Alkalmazás:",
        "Refresh" => "Frissítés",
        "Log out" => "Jelentkezzen ki",
        "Switch to" => "Váltás erre:",
        "Exit" => "Kijárat",
        "{0} is still running" => "A {0} még mindig fut",
        "Use the tray icon to reopen or exit." => "Használja a tálca ikont az újranyitáshoz vagy a kilépéshez.",
        "Ignore" => "Figyelmen kívül hagyni",
        "Ignore {0}" => "{0} figyelmen kívül hagyása",
        "Unignore {0}" => "{0} figyelmen kívül hagyása",
        "Set export file for {0}..." => "Exportfájl beállítása a következőhöz: {0}...",
        "Clear export file name" => "Törölje az exportfájl nevét",
        "Clear export file ({0})" => "Exportfájl törlése ({0})",
        "stack" => "verem",
        "notebook" => "jegyzetfüzet",
        "Select the Evernote root folder, then export the checked notebooks." => "Válassza ki az Evernote gyökérmappáját, majd exportálja a bejelölt jegyzetfüzeteket.",
        "Evernote Folder..." => "Evernote mappa...",
        "Reload" => "Újratöltés",
        "Export" => "Export",
        "Evernote polling frequency (minutes):" => "Evernote lekérdezési gyakoriság (perc):",
        "Pause automatic polling" => "Az automatikus lehívás szüneteltetése",
        "Lock: (none)" => "Zár: (nincs)",
        "Force" => "Erő",
        "State poll: every 6s, next in --s" => "Állami közvélemény-kutatás: 6 másodpercenként, következő --s múlva",
        "Keep last X markdown exports:" => "Az utolsó X leértékelés megtartása:",
        "Older files in ./markdown will be deleted automatically after each export." => "A ./markdown mappában lévő régebbi fájlok minden exportálás után automatikusan törlődnek.",
        "No Evernote folder selected." => "Nincs kiválasztva Evernote mappa.",
        "Show ignored" => "A műsor figyelmen kívül hagyva",
        "Right-click: ignore or set export file name." => "Kattintson a jobb gombbal: figyelmen kívül hagyja vagy állítsa be az exportfájl nevét.",
        "Choose the root folder of the Evernote installation" => "Válassza ki az Evernote telepítésének gyökérmappáját",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB észlelve: {0} | Halmok: {1} | Jegyzetfüzetek: {2}",
        "DB error: {0}" => "DB hiba: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Az Evernote adatbázis nem olvasható.{0}{0}{1}",
        " [ignored]" => "[figyelmen kívül hagyva]",
        " | updated: {0}" => "| frissítve: {0}",
        " | export: {0}.md" => "| exportálás: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} jegyzetfüzet){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} megjegyzések){2}{3}{4}",
        "(none)" => "(egyik sem)",
        "Lock: {0}" => "Zár: {0}",
        "awaiting confirmation from {0}" => "megerősítésre vár a következőtől: {0}",
        "State poll: every {0}s, next in {1}s" => "Állapotszavazás: {0}s, következő {1}s múlva",
        "Export File Name" => "Fájlnév exportálása",
        "Export file name for {0} (without .md):" => "A {0} fájlnév exportálása (.md nélkül):",
        "The same name lets you group multiple stacks/notebooks." => "Ugyanaz a név lehetővé teszi több köteg/jegyzetfüzet csoportosítását.",
        "Invalid name. Use at least one valid character." => "Érvénytelen név. Használjon legalább egy érvényes karaktert.",
        "Language" => "Nyelv",
        "Choose the UI language" => "Válassza ki a felhasználói felület nyelvét",
        "System default" => "Rendszer alapértelmezett",
        "Close button behavior:" => "Bezárás gomb viselkedése:",
        "Minimize to tray" => "Minimalizálja a tálcára",
        "Close app" => "Zárja be az alkalmazást",
        "Controls what happens when you click the window close button." => "Szabályozza, hogy mi történjen, amikor az ablak bezárása gombra kattint.",
        "Enable debug logs" => "Hibakeresési naplók engedélyezése",
        "Local config file: {0}" => "Helyi konfigurációs fájl: {0}",
        "Google Drive config sync" => "Google Drive konfigurációs szinkronizálás",
        "Enable Google Drive sync" => "Google Drive szinkronizálás engedélyezése",
        "Auto-restore at startup" => "Automatikus visszaállítás indításkor",
        "Click the button below to connect with Google OAuth." => "Kattintson az alábbi gombra a Google OAuth-hoz való csatlakozáshoz.",
        "Connect with Google" => "Csatlakozzon a Google-hoz",
        "OAuth status: configured." => "OAuth állapot: konfigurálva.",
        "OAuth status: not connected." => "OAuth állapot: nincs csatlakoztatva.",
        "OAuth status: connecting..." => "OAuth állapot: csatlakozás...",
        "Unknown OAuth error." => "Ismeretlen OAuth hiba.",
        "OAuth status: failed ({0})" => "OAuth állapot: sikertelen ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Az OAuth-kapcsolat nem sikerült.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Google fiók csatlakoztatva",
        "(not detected)" => "(nincs észlelve)",
        "OAuth client source: {0}" => "OAuth-ügyfélforrás: {0}",
        "Drive file ID (optional):" => "Drive-fájlazonosító (nem kötelező):",
        "Export settings" => "Beállítások exportálása",
        "Import settings" => "Beállítások importálása",
        "Select Google OAuth credentials JSON" => "Válassza a Google OAuth hitelesítési adatok JSON-t",
        "OAuth status: credentials file required." => "OAuth állapot: hitelesítő adatfájl szükséges.",
        "OAuth status: error ({0})" => "OAuth állapot: hiba ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Nem sikerült beolvasni az OAuth hitelesítési adatokat.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth állapot: csatlakoztatva ({0}).",
        "Settings exported to:{0}{1}" => "Beállítások exportálva ide:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Nem lehet exportálni a beállításokat.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Egy beállításfájl importálása lecseréli a jelenlegi helyi konfigurációt. Folytatja?",
        "Unable to read the selected file.{0}{0}{1}" => "A kiválasztott fájl nem olvasható.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "A kiválasztott fájl nem tartalmaz érvényes JSON-beállításokat.",
        "Settings imported from:{0}{1}" => "Beállítások importálva innen:{0}{1}",
        _ => english
    };
}



