namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateEt(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Evernote'i eksport",
        "Settings" => "Seaded",
        "Save" => "Salvesta",
        "Cancel" => "Tühista",
        "App:" => "Rakendus:",
        "Refresh" => "Värskenda",
        "Log out" => "Logi välja",
        "Switch to" => "Lülitu sisse",
        "Exit" => "Välju",
        "{0} is still running" => "{0} töötab endiselt",
        "Use the tray icon to reopen or exit." => "Uuesti avamiseks või väljumiseks kasutage salve ikooni.",
        "Ignore" => "Ignoreeri",
        "Ignore {0}" => "Ignoreeri {0}",
        "Unignore {0}" => "Tühista ignoreerimine {0}",
        "Set export file for {0}..." => "Määra ekspordifail {0} jaoks...",
        "Clear export file name" => "Kustuta ekspordifaili nimi",
        "Clear export file ({0})" => "Kustuta ekspordifail ({0})",
        "stack" => "virna",
        "notebook" => "märkmik",
        "Select the Evernote root folder, then export the checked notebooks." => "Valige Evernote'i juurkaust ja eksportige seejärel kontrollitud märkmikud.",
        "Evernote Folder..." => "Evernote'i kaust...",
        "Reload" => "Laadi uuesti",
        "Export" => "Ekspordi",
        "Evernote polling frequency (minutes):" => "Evernote'i küsitlussagedus (minutites):",
        "Pause automatic polling" => "Peatage automaatne küsitlus",
        "Lock: (none)" => "Lukk: (puudub)",
        "Force" => "Jõud",
        "State poll: every 6s, next in --s" => "Osariigiküsitlus: iga 6 sekundi järel, järgmine pärast --s",
        "Keep last X markdown exports:" => "Säilita viimane X allahindluse eksport:",
        "Older files in ./markdown will be deleted automatically after each export." => "Vanemad failid kaustas ./markdown kustutatakse automaatselt pärast iga eksportimist.",
        "No Evernote folder selected." => "Evernote'i kausta pole valitud.",
        "Show ignored" => "Show ignoreeritud",
        "Right-click: ignore or set export file name." => "Paremklõps: ignoreeri või määra ekspordifaili nimi.",
        "Choose the root folder of the Evernote installation" => "Valige Evernote'i installi juurkaust",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB tuvastatud: {0} | Virnad: {1} | Märkmikud: {2}",
        "DB error: {0}" => "DB viga: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Evernote'i andmebaasi ei saa lugeda.{0}{0}{1}",
        " [ignored]" => "[ignoreeriti]",
        " | updated: {0}" => "| värskendatud: {0}",
        " | export: {0}.md" => "| eksport: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} märkmikud){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} märkmed){2}{3}{4}",
        "(none)" => "(mitte ühtegi)",
        "Lock: {0}" => "Lukk: {0}",
        "awaiting confirmation from {0}" => "ootan kinnitust {0}",
        "State poll: every {0}s, next in {1}s" => "Osariigiküsitlus: iga {0}s, järgmine {1}s pärast",
        "Export File Name" => "Ekspordi failinimi",
        "Export file name for {0} (without .md):" => "Ekspordi faili nimi {0} jaoks (ilma .mdta):",
        "The same name lets you group multiple stacks/notebooks." => "Sama nimi võimaldab teil rühmitada mitu virna/märkmikku.",
        "Invalid name. Use at least one valid character." => "Vale nimi. Kasutage vähemalt ühte kehtivat tähemärki.",
        "Language" => "Keel",
        "Choose the UI language" => "Valige kasutajaliidese keel",
        "System default" => "Süsteemi vaikeseade",
        "Close button behavior:" => "Sulgemisnupu käitumine:",
        "Minimize to tray" => "Minimeeri alusele",
        "Close app" => "Sulgege rakendus",
        "Controls what happens when you click the window close button." => "Juhib seda, mis juhtub, kui klõpsate akna sulgemisnupul.",
        "Enable debug logs" => "Luba silumislogid",
        "Local config file: {0}" => "Kohalik konfiguratsioonifail: {0}",
        "Google Drive config sync" => "Google Drive'i konfiguratsiooni sünkroonimine",
        "Enable Google Drive sync" => "Luba Google Drive'i sünkroonimine",
        "Auto-restore at startup" => "Automaatne taastamine käivitamisel",
        "Click the button below to connect with Google OAuth." => "Google OAuthiga ühenduse loomiseks klõpsake alloleval nupul.",
        "Connect with Google" => "Ühendage Google'iga",
        "OAuth status: configured." => "OAuthi olek: seadistatud.",
        "OAuth status: not connected." => "OAuthi olek: pole ühendatud.",
        "OAuth status: connecting..." => "OAuthi olek: ühendamine...",
        "Unknown OAuth error." => "Tundmatu OAuthi viga.",
        "OAuth status: failed ({0})" => "OAuthi olek: ebaõnnestus ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuthi ühendus ebaõnnestus.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive'i OAuth",
        "Google account connected" => "Google'i konto ühendatud",
        "(not detected)" => "(ei tuvastatud)",
        "OAuth client source: {0}" => "OAuthi kliendi allikas: {0}",
        "Drive file ID (optional):" => "Drive'i faili ID (valikuline):",
        "Export settings" => "Ekspordi seaded",
        "Import settings" => "Impordi seaded",
        "Select Google OAuth credentials JSON" => "Valige Google OAuthi mandaatide JSON",
        "OAuth status: credentials file required." => "OAuthi olek: nõutav on mandaadifail.",
        "OAuth status: error ({0})" => "OAuthi olek: viga ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "OAuthi mandaate ei saa lugeda.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuthi olek: ühendatud ({0}).",
        "Settings exported to:{0}{1}" => "Seaded eksporditi:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Seadeid ei saa eksportida.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Seadete faili importimine asendab teie praeguse kohaliku konfiguratsiooni. Kas jätkata?",
        "Unable to read the selected file.{0}{0}{1}" => "Valitud faili ei saa lugeda.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Valitud fail ei sisalda kehtivaid JSON-i sätteid.",
        "Settings imported from:{0}{1}" => "Seaded imporditud asukohast:{0}{1}",
        _ => english
    };
}



