namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateHi(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "गूगल हाँकना",
        "Evernote Export" => "एवरनोट निर्यात",
        "Settings" => "सेटिंग्स",
        "Save" => "बचाना",
        "Cancel" => "रद्द करना",
        "App:" => "अनुप्रयोग:",
        "Refresh" => "ताज़ा करना",
        "Log out" => "लॉग आउट",
        "Switch to" => "पर स्विच",
        "Exit" => "बाहर निकलना",
        "{0} is still running" => "{0} अभी भी चल रहा है",
        "Use the tray icon to reopen or exit." => "पुनः खोलने या बाहर निकलने के लिए ट्रे आइकन का उपयोग करें।",
        "Ignore" => "अनदेखा करना",
        "Ignore {0}" => "{0} को अनदेखा करें",
        "Unignore {0}" => "अनदेखा करें {0}",
        "Set export file for {0}..." => "{0} के लिए निर्यात फ़ाइल सेट करें...",
        "Clear export file name" => "निर्यात फ़ाइल नाम साफ़ करें",
        "Clear export file ({0})" => "निर्यात फ़ाइल साफ़ करें ({0})",
        "stack" => "ढेर",
        "notebook" => "नोटबुक",
        "Select the Evernote root folder, then export the checked notebooks." => "एवरनोट रूट फ़ोल्डर का चयन करें, फिर चेक की गई नोटबुक निर्यात करें।",
        "Evernote Folder..." => "एवरनोट फ़ोल्डर...",
        "Reload" => "पुनः लोड करें",
        "Export" => "निर्यात",
        "Evernote polling frequency (minutes):" => "एवरनोट मतदान आवृत्ति (मिनट):",
        "Pause automatic polling" => "स्वचालित मतदान रोकें",
        "Lock: (none)" => "लॉक: (कोई नहीं)",
        "Force" => "बल",
        "State poll: every 6s, next in --s" => "राज्य सर्वेक्षण: प्रत्येक 6 सेकंड, अगले -- सेकंड में",
        "Keep last X markdown exports:" => "अंतिम एक्स मार्कडाउन निर्यात रखें:",
        "Older files in ./markdown will be deleted automatically after each export." => "./markdown में पुरानी फ़ाइलें प्रत्येक निर्यात के बाद स्वचालित रूप से हटा दी जाएंगी।",
        "No Evernote folder selected." => "कोई एवरनोट फ़ोल्डर चयनित नहीं.",
        "Show ignored" => "अनदेखा दिखाएँ",
        "Right-click: ignore or set export file name." => "राइट-क्लिक करें: निर्यात फ़ाइल नाम को अनदेखा करें या सेट करें।",
        "Choose the root folder of the Evernote installation" => "एवरनोट इंस्टॉलेशन का रूट फ़ोल्डर चुनें",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "डीबी का पता चला: {0} | ढेर: {1} | नोटबुक: {2}",
        "DB error: {0}" => "डीबी त्रुटि: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Evernote डेटाबेस को पढ़ने में असमर्थ.{0}{0}{1}",
        " [ignored]" => "[अवहेलना करना]",
        " | updated: {0}" => "| अद्यतन: {0}",
        " | export: {0}.md" => "| निर्यात: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} नोटबुक){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} नोट्स){2}{3}{4}",
        "(none)" => "(कोई नहीं)",
        "Lock: {0}" => "लॉक: {0}",
        "awaiting confirmation from {0}" => "{0} से पुष्टि की प्रतीक्षा में",
        "State poll: every {0}s, next in {1}s" => "राज्य सर्वेक्षण: प्रत्येक {0}s, अगला {1}s में",
        "Export File Name" => "फ़ाइल नाम निर्यात करें",
        "Export file name for {0} (without .md):" => "{0} के लिए फ़ाइल नाम निर्यात करें (.md के बिना):",
        "The same name lets you group multiple stacks/notebooks." => "एक ही नाम से आप एकाधिक स्टैक/नोटबुक को समूहित कर सकते हैं।",
        "Invalid name. Use at least one valid character." => "अमान्य नाम। कम से कम एक वैध वर्ण का प्रयोग करें.",
        "Language" => "भाषा",
        "Choose the UI language" => "यूआई भाषा चुनें",
        "System default" => "प्रणालीगत चूक",
        "Close button behavior:" => "बंद करें बटन व्यवहार:",
        "Minimize to tray" => "ट्रे पर छोटा करें",
        "Close app" => "ऐप बंद करें",
        "Controls what happens when you click the window close button." => "यह नियंत्रित करता है कि जब आप विंडो बंद करें बटन पर क्लिक करते हैं तो क्या होता है।",
        "Enable debug logs" => "डिबग लॉग सक्षम करें",
        "Local config file: {0}" => "स्थानीय कॉन्फ़िगरेशन फ़ाइल: {0}",
        "Google Drive config sync" => "Google Drive कॉन्फ़िग सिंक",
        "Enable Google Drive sync" => "Google ड्राइव सिंक सक्षम करें",
        "Auto-restore at startup" => "स्टार्टअप पर स्वतः-पुनर्स्थापना",
        "Click the button below to connect with Google OAuth." => "Google OAuth से जुड़ने के लिए नीचे दिए गए बटन पर क्लिक करें।",
        "Connect with Google" => "गूगल से जुड़ें",
        "OAuth status: configured." => "OAuth स्थिति: कॉन्फ़िगर किया गया.",
        "OAuth status: not connected." => "OAuth स्थिति: कनेक्ट नहीं है.",
        "OAuth status: connecting..." => "OAuth स्थिति: कनेक्ट हो रहा है...",
        "Unknown OAuth error." => "अज्ञात OAuth त्रुटि.",
        "OAuth status: failed ({0})" => "OAuth स्थिति: विफल ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth कनेक्शन विफल.{0}{0}{1}",
        "Google Drive OAuth" => "गूगल ड्राइव OAuth",
        "Google account connected" => "Google खाता कनेक्ट किया गया",
        "(not detected)" => "(का पता नहीं चला)",
        "OAuth client source: {0}" => "OAuth क्लाइंट स्रोत: {0}",
        "Drive file ID (optional):" => "ड्राइव फ़ाइल आईडी (वैकल्पिक):",
        "Export settings" => "निर्यात सेटिंग्स",
        "Import settings" => "सेटिंग आयात करना",
        "Select Google OAuth credentials JSON" => "Google OAuth क्रेडेंशियल JSON चुनें",
        "OAuth status: credentials file required." => "OAuth स्थिति: क्रेडेंशियल फ़ाइल आवश्यक है।",
        "OAuth status: error ({0})" => "OAuth स्थिति: त्रुटि ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "OAuth क्रेडेंशियल पढ़ने में असमर्थ.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth स्थिति: कनेक्टेड ({0})।",
        "Settings exported to:{0}{1}" => "सेटिंग्स यहां निर्यात की गईं:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "सेटिंग्स निर्यात करने में असमर्थ.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "सेटिंग फ़ाइल आयात करना आपके वर्तमान स्थानीय कॉन्फ़िगरेशन को प्रतिस्थापित कर देगा। जारी रखना?",
        "Unable to read the selected file.{0}{0}{1}" => "चयनित फ़ाइल को पढ़ने में असमर्थ.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "चयनित फ़ाइल में वैध सेटिंग्स JSON नहीं है।",
        "Settings imported from:{0}{1}" => "सेटिंग्स यहां से आयात की गईं:{0}{1}",
        _ => english
    };
}



