namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateDa(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drev",
        "Evernote Export" => "Evernote eksport",
        "Settings" => "Indstillinger",
        "Save" => "Spare",
        "Cancel" => "Ophæve",
        "App:" => "App:",
        "Refresh" => "Opfriske",
        "Log out" => "Log ud",
        "Switch to" => "Skift til",
        "Exit" => "Udgang",
        "{0} is still running" => "{0} kører stadig",
        "Use the tray icon to reopen or exit." => "Brug bakkeikonet til at genåbne eller afslutte.",
        "Ignore" => "Ignorere",
        "Ignore {0}" => "Ignorer {0}",
        "Unignore {0}" => "Ignorer {0}",
        "Set export file for {0}..." => "Indstil eksportfil til {0}...",
        "Clear export file name" => "Ryd eksportfilnavn",
        "Clear export file ({0})" => "Ryd eksportfil ({0})",
        "stack" => "stak",
        "notebook" => "notesbog",
        "Select the Evernote root folder, then export the checked notebooks." => "Vælg Evernote-rodmappen, og eksporter derefter de markerede notesbøger.",
        "Evernote Folder..." => "Evernote-mappe...",
        "Reload" => "Genindlæs",
        "Export" => "Eksportere",
        "Evernote polling frequency (minutes):" => "Evernote afstemningsfrekvens (minutter):",
        "Pause automatic polling" => "Sæt automatisk polling på pause",
        "Lock: (none)" => "Lås: (ingen)",
        "Force" => "Kraft",
        "State poll: every 6s, next in --s" => "Statsmåling: hver 6., næste i --s",
        "Keep last X markdown exports:" => "Behold sidste X markdown-eksport:",
        "Older files in ./markdown will be deleted automatically after each export." => "Ældre filer i ./markdown slettes automatisk efter hver eksport.",
        "No Evernote folder selected." => "Der er ikke valgt nogen Evernote-mappe.",
        "Show ignored" => "Vis ignoreret",
        "Right-click: ignore or set export file name." => "Højreklik: ignorer eller indstil eksportfilnavn.",
        "Choose the root folder of the Evernote installation" => "Vælg rodmappen til Evernote-installationen",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB fundet: {0} | Stabler: {1} | Notesbøger: {2}",
        "DB error: {0}" => "DB fejl: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Kan ikke læse Evernote-databasen.{0}{0}{1}",
        " [ignored]" => "[ignoreret]",
        " | updated: {0}" => "| opdateret: {0}",
        " | export: {0}.md" => "| eksport: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} notesbøger){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} noter){2}{3}{4}",
        "(none)" => "(ingen)",
        "Lock: {0}" => "Lås: {0}",
        "awaiting confirmation from {0}" => "afventer bekræftelse fra {0}",
        "State poll: every {0}s, next in {1}s" => "Tilstandsafstemning: hver {0}s, næste om {1}s",
        "Export File Name" => "Eksporter filnavn",
        "Export file name for {0} (without .md):" => "Eksporter filnavn for {0} (uden .md):",
        "The same name lets you group multiple stacks/notebooks." => "Det samme navn giver dig mulighed for at gruppere flere stakke/notesbøger.",
        "Invalid name. Use at least one valid character." => "Ugyldigt navn. Brug mindst ét ​​gyldigt tegn.",
        "Language" => "Sprog",
        "Choose the UI language" => "Vælg UI-sproget",
        "System default" => "System standard",
        "Close button behavior:" => "Luk-knappens adfærd:",
        "Minimize to tray" => "Minimer til bakke",
        "Close app" => "Luk app",
        "Controls what happens when you click the window close button." => "Styrer, hvad der sker, når du klikker på vinduets lukkeknap.",
        "Enable debug logs" => "Aktiver fejlretningslogfiler",
        "Local config file: {0}" => "Lokal konfigurationsfil: {0}",
        "Google Drive config sync" => "Google Drev-konfigurationssynkronisering",
        "Enable Google Drive sync" => "Aktiver Google Drev-synkronisering",
        "Auto-restore at startup" => "Automatisk gendannelse ved opstart",
        "Click the button below to connect with Google OAuth." => "Klik på knappen nedenfor for at oprette forbindelse til Google OAuth.",
        "Connect with Google" => "Forbind med Google",
        "OAuth status: configured." => "OAuth-status: konfigureret.",
        "OAuth status: not connected." => "OAuth-status: ikke forbundet.",
        "OAuth status: connecting..." => "OAuth-status: opretter forbindelse...",
        "Unknown OAuth error." => "Ukendt OAuth-fejl.",
        "OAuth status: failed ({0})" => "OAuth-status: mislykkedes ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth-forbindelse mislykkedes.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drev OAuth",
        "Google account connected" => "Google-konto forbundet",
        "(not detected)" => "(ikke fundet)",
        "OAuth client source: {0}" => "OAuth-klientkilde: {0}",
        "Drive file ID (optional):" => "Drev-fil-id (valgfrit):",
        "Export settings" => "Eksporter indstillinger",
        "Import settings" => "Importer indstillinger",
        "Select Google OAuth credentials JSON" => "Vælg Google OAuth-legitimationsoplysninger JSON",
        "OAuth status: credentials file required." => "OAuth-status: legitimationsfil påkrævet.",
        "OAuth status: error ({0})" => "OAuth-status: fejl ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Kan ikke læse OAuth-legitimationsoplysninger.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth-status: tilsluttet ({0}).",
        "Settings exported to:{0}{1}" => "Indstillinger eksporteret til:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Kan ikke eksportere indstillinger.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Import af en indstillingsfil erstatter din nuværende lokale konfiguration. Fortsætte?",
        "Unable to read the selected file.{0}{0}{1}" => "Kan ikke læse den valgte fil.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Den valgte fil indeholder ikke gyldige JSON-indstillinger.",
        "Settings imported from:{0}{1}" => "Indstillinger importeret fra:{0}{1}",
        _ => english
    };
}



