namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateRu(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Гугл Диск",
        "Evernote Export" => "Экспорт в Evernote",
        "Settings" => "Настройки",
        "Save" => "Сохранять",
        "Cancel" => "Отмена",
        "App:" => "Приложение:",
        "Refresh" => "Обновить",
        "Log out" => "Выйти",
        "Switch to" => "Переключиться на",
        "Exit" => "Выход",
        "{0} is still running" => "{0} все еще работает",
        "Use the tray icon to reopen or exit." => "Используйте значок на панели задач, чтобы снова открыть или выйти.",
        "Ignore" => "игнорировать",
        "Ignore {0}" => "Игнорировать {0}",
        "Unignore {0}" => "Не игнорировать {0}",
        "Set export file for {0}..." => "Установить файл экспорта для {0}...",
        "Clear export file name" => "Очистить имя файла экспорта",
        "Clear export file ({0})" => "Очистить файл экспорта ({0})",
        "stack" => "куча",
        "notebook" => "блокнот",
        "Select the Evernote root folder, then export the checked notebooks." => "Выберите корневую папку Evernote, затем экспортируйте отмеченные блокноты.",
        "Evernote Folder..." => "Папка Evernote...",
        "Reload" => "Перезагрузить",
        "Export" => "Экспорт",
        "Evernote polling frequency (minutes):" => "Частота опроса Evernote (минуты):",
        "Pause automatic polling" => "Приостановить автоматический опрос",
        "Lock: (none)" => "Блокировка: (нет)",
        "Force" => "Сила",
        "State poll: every 6s, next in --s" => "Опрос штата: каждые 6 секунд, следующий через --s",
        "Keep last X markdown exports:" => "Сохранить последний экспорт уценки X:",
        "Older files in ./markdown will be deleted automatically after each export." => "Старые файлы в ./markdown будут автоматически удаляться после каждого экспорта.",
        "No Evernote folder selected." => "Папка Evernote не выбрана.",
        "Show ignored" => "Показать игнорируемые",
        "Right-click: ignore or set export file name." => "Щелкните правой кнопкой мыши: игнорировать или установить имя файла экспорта.",
        "Choose the root folder of the Evernote installation" => "Выберите корневую папку установки Evernote.",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "Обнаружена БД: {0} | Стеки: {1} | Ноутбуки: {2}",
        "DB error: {0}" => "Ошибка БД: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Невозможно прочитать базу данных Evernote.{0}{0}{1}",
        " [ignored]" => "[игнорируется]",
        " | updated: {0}" => "| обновлено: {0}",
        " | export: {0}.md" => "| экспорт: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} (блокноты {1}){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} примечания){2}{3}{4}",
        "(none)" => "(никто)",
        "Lock: {0}" => "Блокировка: {0}",
        "awaiting confirmation from {0}" => "ждём подтверждения от {0}",
        "State poll: every {0}s, next in {1}s" => "Опрос в штате: каждые {0}s, следующий через {1}s.",
        "Export File Name" => "Имя файла экспорта",
        "Export file name for {0} (without .md):" => "Имя файла экспорта для {0} (без .md):",
        "The same name lets you group multiple stacks/notebooks." => "Одно и то же имя позволяет группировать несколько стопок/блокнотов.",
        "Invalid name. Use at least one valid character." => "Неверное имя. Используйте хотя бы один допустимый символ.",
        "Language" => "Язык",
        "Choose the UI language" => "Выберите язык пользовательского интерфейса",
        "System default" => "Система по умолчанию",
        "Close button behavior:" => "Поведение кнопки закрытия:",
        "Minimize to tray" => "Свернуть в трей",
        "Close app" => "Закрыть приложение",
        "Controls what happens when you click the window close button." => "Управляет тем, что происходит при нажатии кнопки закрытия окна.",
        "Enable debug logs" => "Включить журналы отладки",
        "Local config file: {0}" => "Локальный файл конфигурации: {0}",
        "Google Drive config sync" => "Синхронизация конфигурации Google Диска",
        "Enable Google Drive sync" => "Включить синхронизацию с Google Диском",
        "Auto-restore at startup" => "Автовосстановление при запуске",
        "Click the button below to connect with Google OAuth." => "Нажмите кнопку ниже, чтобы подключиться к Google OAuth.",
        "Connect with Google" => "Подключитесь к Google",
        "OAuth status: configured." => "Статус OAuth: настроен.",
        "OAuth status: not connected." => "Статус OAuth: не подключено.",
        "OAuth status: connecting..." => "Статус OAuth: подключение...",
        "Unknown OAuth error." => "Неизвестная ошибка OAuth.",
        "OAuth status: failed ({0})" => "Статус OAuth: не удалось ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Не удалось подключиться к OAuth.{0}{0}{1}.",
        "Google Drive OAuth" => "Google Диск OAuth",
        "Google account connected" => "Аккаунт Google подключен",
        "(not detected)" => "(не обнаружено)",
        "OAuth client source: {0}" => "Источник клиента OAuth: {0}",
        "Drive file ID (optional):" => "Идентификатор файла на диске (необязательно):",
        "Export settings" => "Экспорт настроек",
        "Import settings" => "Импортировать настройки",
        "Select Google OAuth credentials JSON" => "Выберите учетные данные Google OAuth в формате JSON.",
        "OAuth status: credentials file required." => "Статус OAuth: требуется файл учетных данных.",
        "OAuth status: error ({0})" => "Статус OAuth: ошибка ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Невозможно прочитать учетные данные OAuth.{0}{0}{1}.",
        "OAuth status: connected ({0})." => "Статус OAuth: подключен ({0}).",
        "Settings exported to:{0}{1}" => "Настройки экспортированы в: {0}{1}.",
        "Unable to export settings.{0}{0}{1}" => "Невозможно экспортировать настройки.{0}{0}{1}.",
        "Importing a settings file will replace your current local configuration. Continue?" => "Импорт файла настроек заменит вашу текущую локальную конфигурацию. Продолжать?",
        "Unable to read the selected file.{0}{0}{1}" => "Невозможно прочитать выбранный файл.{0}{0}{1}.",
        "The selected file does not contain valid settings JSON." => "Выбранный файл не содержит допустимых настроек JSON.",
        "Settings imported from:{0}{1}" => "Настройки импортированы из: {0}{1}.",
        _ => english
    };
}



