namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateId(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Ekspor Evernote",
        "Settings" => "Pengaturan",
        "Save" => "Menyimpan",
        "Cancel" => "Membatalkan",
        "App:" => "Aplikasi:",
        "Refresh" => "Menyegarkan",
        "Log out" => "Keluar",
        "Switch to" => "Beralih ke",
        "Exit" => "KELUAR",
        "{0} is still running" => "{0} masih berjalan",
        "Use the tray icon to reopen or exit." => "Gunakan ikon baki untuk membuka kembali atau keluar.",
        "Ignore" => "Mengabaikan",
        "Ignore {0}" => "Abaikan {0}",
        "Unignore {0}" => "Abaikan {0}",
        "Set export file for {0}..." => "Setel file ekspor untuk {0}...",
        "Clear export file name" => "Hapus nama file ekspor",
        "Clear export file ({0})" => "Hapus file ekspor ({0})",
        "stack" => "tumpukan",
        "notebook" => "buku catatan",
        "Select the Evernote root folder, then export the checked notebooks." => "Pilih folder akar Evernote, lalu ekspor buku catatan yang dicentang.",
        "Evernote Folder..." => "Folder Evernote...",
        "Reload" => "Muat ulang",
        "Export" => "Ekspor",
        "Evernote polling frequency (minutes):" => "Frekuensi polling Evernote (menit):",
        "Pause automatic polling" => "Jeda pemungutan suara otomatis",
        "Lock: (none)" => "Kunci: (tidak ada)",
        "Force" => "Memaksa",
        "State poll: every 6s, next in --s" => "Jajak pendapat negara bagian: setiap 6 detik, berikutnya dalam --s",
        "Keep last X markdown exports:" => "Pertahankan ekspor penurunan harga X terakhir:",
        "Older files in ./markdown will be deleted automatically after each export." => "File lama di ./markdown akan dihapus secara otomatis setelah setiap ekspor.",
        "No Evernote folder selected." => "Tidak ada folder Evernote yang dipilih.",
        "Show ignored" => "Tampilkan diabaikan",
        "Right-click: ignore or set export file name." => "Klik kanan: abaikan atau atur nama file ekspor.",
        "Choose the root folder of the Evernote installation" => "Pilih folder root dari instalasi Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB terdeteksi: {0} | Tumpukan: {1} | Buku catatan: {2}",
        "DB error: {0}" => "Kesalahan DB: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Tidak dapat membaca basis data Evernote.{0}{0}{1}",
        " [ignored]" => "[diabaikan]",
        " | updated: {0}" => "| diperbarui: {0}",
        " | export: {0}.md" => "| ekspor: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} buku catatan){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} catatan){2}{3}{4}",
        "(none)" => "(tidak ada)",
        "Lock: {0}" => "Kunci: {0}",
        "awaiting confirmation from {0}" => "menunggu konfirmasi dari {0}",
        "State poll: every {0}s, next in {1}s" => "Jajak pendapat negara bagian: setiap {0}s, berikutnya dalam {1}s",
        "Export File Name" => "Ekspor Nama File",
        "Export file name for {0} (without .md):" => "Ekspor nama file untuk {0} (tanpa .md):",
        "The same name lets you group multiple stacks/notebooks." => "Nama yang sama memungkinkan Anda mengelompokkan beberapa tumpukan/buku catatan.",
        "Invalid name. Use at least one valid character." => "Nama tidak valid. Gunakan setidaknya satu karakter yang valid.",
        "Language" => "Bahasa",
        "Choose the UI language" => "Pilih bahasa UI",
        "System default" => "Bawaan sistem",
        "Close button behavior:" => "Perilaku tombol tutup:",
        "Minimize to tray" => "Minimalkan ke baki",
        "Close app" => "Tutup aplikasi",
        "Controls what happens when you click the window close button." => "Mengontrol apa yang terjadi ketika Anda mengklik tombol tutup jendela.",
        "Enable debug logs" => "Aktifkan log debug",
        "Local config file: {0}" => "File konfigurasi lokal: {0}",
        "Google Drive config sync" => "Sinkronisasi konfigurasi Google Drive",
        "Enable Google Drive sync" => "Aktifkan sinkronisasi Google Drive",
        "Auto-restore at startup" => "Pemulihan otomatis saat startup",
        "Click the button below to connect with Google OAuth." => "Klik tombol di bawah untuk terhubung dengan Google OAuth.",
        "Connect with Google" => "Terhubung dengan Google",
        "OAuth status: configured." => "Status OAuth: dikonfigurasi.",
        "OAuth status: not connected." => "Status OAuth: tidak terhubung.",
        "OAuth status: connecting..." => "Status OAuth: menghubungkan...",
        "Unknown OAuth error." => "Kesalahan OAuth tidak diketahui.",
        "OAuth status: failed ({0})" => "Status OAuth: gagal ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Koneksi OAuth gagal.{0}{0}{1}",
        "Google Drive OAuth" => "OAuth Google Drive",
        "Google account connected" => "Akun Google terhubung",
        "(not detected)" => "(tidak terdeteksi)",
        "OAuth client source: {0}" => "Sumber klien OAuth: {0}",
        "Drive file ID (optional):" => "ID file Drive (opsional):",
        "Export settings" => "Ekspor pengaturan",
        "Import settings" => "Impor pengaturan",
        "Select Google OAuth credentials JSON" => "Pilih kredensial Google OAuth JSON",
        "OAuth status: credentials file required." => "Status OAuth: file kredensial diperlukan.",
        "OAuth status: error ({0})" => "Status OAuth: kesalahan ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Tidak dapat membaca kredensial OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Status OAuth: terhubung ({0}).",
        "Settings exported to:{0}{1}" => "Pengaturan diekspor ke:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Tidak dapat mengekspor pengaturan.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Mengimpor file pengaturan akan menggantikan konfigurasi lokal Anda saat ini. Melanjutkan?",
        "Unable to read the selected file.{0}{0}{1}" => "Tidak dapat membaca file yang dipilih.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "File yang dipilih tidak berisi pengaturan JSON yang valid.",
        "Settings imported from:{0}{1}" => "Pengaturan diimpor dari:{0}{1}",
        _ => english
    };
}



