namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateSrCyrl(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Гоогле диск",
        "Evernote Export" => "Еверноте Екпорт",
        "Settings" => "Подешавања",
        "Save" => "Сачувај",
        "Cancel" => "Откажи",
        "App:" => "апликација:",
        "Refresh" => "Освежи",
        "Log out" => "Одјавите се",
        "Switch to" => "Пребаци на",
        "Exit" => "Изађи",
        "{0} is still running" => "__ПХ0__ још увек ради",
        "Use the tray icon to reopen or exit." => "Користите икону у траци да поново отворите или изађете.",
        "Ignore" => "Игнорирај",
        "Ignore {0}" => "Занемари __ПХ0__",
        "Unignore {0}" => "Занемари __ПХ0__",
        "Set export file for {0}..." => "Подесите датотеку за извоз за __ПХ0__...",
        "Clear export file name" => "Обришите назив датотеке за извоз",
        "Clear export file ({0})" => "Обриши датотеку за извоз (__ПХ0__)",
        "stack" => "стек",
        "notebook" => "свеска",
        "Select the Evernote root folder, then export the checked notebooks." => "Изаберите основну фасциклу Еверноте, а затим извезите означене бележнице.",
        "Evernote Folder..." => "Еверноте фолдер...",
        "Reload" => "Поново учитај",
        "Export" => "Извоз",
        "Evernote polling frequency (minutes):" => "Учесталост анкетирања Еверноте-а (минути):",
        "Pause automatic polling" => "Паузирајте аутоматско гласање",
        "Lock: (none)" => "Закључавање: (нема)",
        "Force" => "Форце",
        "State poll: every 6s, next in --s" => "Државна анкета: сваких 6с, следеће за --с",
        "Keep last X markdown exports:" => "Задржи последње Кс извозе умањења вредности:",
        "Older files in ./markdown will be deleted automatically after each export." => "Старије датотеке у __ПАТХ_МАРКДОВН__ ће се аутоматски избрисати након сваког извоза.",
        "No Evernote folder selected." => "Није изабран ниједан Еверноте фолдер.",
        "Show ignored" => "Прикажи игнорисано",
        "Right-click: ignore or set export file name." => "Десни клик: игноришите или подесите име датотеке за извоз.",
        "Choose the root folder of the Evernote installation" => "Изаберите основну фасциклу Еверноте инсталације",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "ДБ откривен: __ПХ0__ | Стацкс: __ПХ1__ | Свеске: __ПХ2__",
        "DB error: {0}" => "ДБ грешка: __ПХ0__",
        "Unable to read Evernote database.{0}{0}{1}" => "Није могуће прочитати Еверноте базу података.__ПХ0____ПХ0____ПХ1__",
        " [ignored]" => "[игнорисано]",
        " | updated: {0}" => "| ажурирано: __ПХ0__",
        " | export: {0}.md" => "| извоз: __ПХ0__.мд",
        "{0} ({1} notebooks){2}{3}{4}" => "__ПХ0__ (__ПХ1__ свеске)__ПХ2____ПХ3____ПХ4__",
        "{0} ({1} notes){2}{3}{4}" => "__ПХ0__ (__ПХ1__ белешке)__ПХ2____ПХ3____ПХ4__",
        "(none)" => "(ниједна)",
        "Lock: {0}" => "Закључавање: __ПХ0__",
        "awaiting confirmation from {0}" => "чека се потврда од __ПХ0__",
        "State poll: every {0}s, next in {1}s" => "Државна анкета: сваких __ПХ0__с, следећа за __ПХ1__с",
        "Export File Name" => "Извези назив датотеке",
        "Export file name for {0} (without .md):" => "Извези назив датотеке за __ПХ0__ (без .мд):",
        "The same name lets you group multiple stacks/notebooks." => "Исто име вам омогућава да групишете више гомила/бележница.",
        "Invalid name. Use at least one valid character." => "Неважеће име. Користите најмање један важећи знак.",
        "Language" => "Језик",
        "Choose the UI language" => "Изаберите језик корисничког интерфејса",
        "System default" => "Систем подразумевано",
        "Close button behavior:" => "Понашање дугмета за затварање:",
        "Minimize to tray" => "Минимизирајте у послужавник",
        "Close app" => "Затворите апликацију",
        "Controls what happens when you click the window close button." => "Контролише шта се дешава када кликнете на дугме за затварање прозора.",
        "Enable debug logs" => "Омогућите евиденцију отклањања грешака",
        "Local config file: {0}" => "Локална конфигурациона датотека: __ПХ0__",
        "Google Drive config sync" => "Синхронизација конфигурације Гоогле диска",
        "Enable Google Drive sync" => "Омогућите синхронизацију Гоогле диска",
        "Auto-restore at startup" => "Аутоматско враћање при покретању",
        "Click the button below to connect with Google OAuth." => "Кликните на дугме испод да бисте се повезали са Гоогле ОАутх-ом.",
        "Connect with Google" => "Повежите се са Гоогле-ом",
        "OAuth status: configured." => "ОАутх статус: конфигурисан.",
        "OAuth status: not connected." => "ОАутх статус: није повезан.",
        "OAuth status: connecting..." => "ОАутх статус: повезивање...",
        "Unknown OAuth error." => "Непозната ОАутх грешка.",
        "OAuth status: failed ({0})" => "ОАутх статус: није успело (__ПХ0__)",
        "OAuth connection failed.{0}{0}{1}" => "ОАутх веза није успела.__ПХ0____ПХ0____ПХ1__",
        "Google Drive OAuth" => "ОАутх за Гоогле диск",
        "Google account connected" => "Гоогле налог је повезан",
        "(not detected)" => "(није откривено)",
        "OAuth client source: {0}" => "Извор ОАутх клијента: __ПХ0__",
        "Drive file ID (optional):" => "ИД датотеке на диску (опционално):",
        "Export settings" => "Извезите подешавања",
        "Import settings" => "Увезите подешавања",
        "Select Google OAuth credentials JSON" => "Изаберите ЈСОН за Гоогле ОАутх акредитиве",
        "OAuth status: credentials file required." => "ОАутх статус: потребна је датотека акредитива.",
        "OAuth status: error ({0})" => "ОАутх статус: грешка (__ПХ0__)",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Није могуће прочитати ОАутх акредитиве.__ПХ0____ПХ0____ПХ1__",
        "OAuth status: connected ({0})." => "ОАутх статус: повезан (__ПХ0__).",
        "Settings exported to:{0}{1}" => "Подешавања су извезена у:__ПХ0____ПХ1__",
        "Unable to export settings.{0}{0}{1}" => "Није могуће извести подешавања.__ПХ0____ПХ0____ПХ1__",
        "Importing a settings file will replace your current local configuration. Continue?" => "Увоз датотеке подешавања ће заменити вашу тренутну локалну конфигурацију. Наставити?",
        "Unable to read the selected file.{0}{0}{1}" => "Није могуће прочитати изабрану датотеку.__ПХ0____ПХ0____ПХ1__",
        "The selected file does not contain valid settings JSON." => "Изабрана датотека не садржи важеће ЈСОН поставке.",
        "Settings imported from:{0}{1}" => "Подешавања увезена са:__ПХ0____ПХ1__",
        _ => english
    };
}



