namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateNo(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Disk",
        "Evernote Export" => "Evernote Export",
        "Settings" => "Innstillinger",
        "Save" => "Spare",
        "Cancel" => "Kansellere",
        "App:" => "App:",
        "Refresh" => "Forfriske",
        "Log out" => "Logg ut",
        "Switch to" => "Bytt til",
        "Exit" => "Gå",
        "{0} is still running" => "{0} kjører fortsatt",
        "Use the tray icon to reopen or exit." => "Bruk ikonet for å åpne eller avslutte.",
        "Ignore" => "Overse",
        "Ignore {0}" => "Ignorer {0}",
        "Unignore {0}" => "Ignorer {0}",
        "Set export file for {0}..." => "Angi eksportfil for {0}...",
        "Clear export file name" => "Fjern navnet på eksportfilen",
        "Clear export file ({0})" => "Slett eksportfil ({0})",
        "stack" => "stable",
        "notebook" => "notisbok",
        "Select the Evernote root folder, then export the checked notebooks." => "Velg Evernote-rotmappen, og eksporter deretter de merkede notatbøkene.",
        "Evernote Folder..." => "Evernote-mappe...",
        "Reload" => "Last inn på nytt",
        "Export" => "Eksport",
        "Evernote polling frequency (minutes):" => "Evernote-avstemningsfrekvens (minutter):",
        "Pause automatic polling" => "Sett automatisk polling på pause",
        "Lock: (none)" => "Lås: (ingen)",
        "Force" => "Makt",
        "State poll: every 6s, next in --s" => "Statsmåling: hver 6., neste i --s",
        "Keep last X markdown exports:" => "Behold siste X markdown-eksporter:",
        "Older files in ./markdown will be deleted automatically after each export." => "Eldre filer i ./markdown vil bli slettet automatisk etter hver eksport.",
        "No Evernote folder selected." => "Ingen Evernote-mappe er valgt.",
        "Show ignored" => "Vis ignorert",
        "Right-click: ignore or set export file name." => "Høyreklikk: ignorer eller angi eksportfilnavn.",
        "Choose the root folder of the Evernote installation" => "Velg rotmappen til Evernote-installasjonen",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB oppdaget: {0} | Stabler: {1} | Notatbøker: {2}",
        "DB error: {0}" => "DB-feil: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Kan ikke lese Evernote-databasen.{0}{0}{1}",
        " [ignored]" => "[ignorert]",
        " | updated: {0}" => "| oppdatert: {0}",
        " | export: {0}.md" => "| eksport: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} notatbøker){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} notater){2}{3}{4}",
        "(none)" => "(ingen)",
        "Lock: {0}" => "Lås: {0}",
        "awaiting confirmation from {0}" => "venter på bekreftelse fra {0}",
        "State poll: every {0}s, next in {1}s" => "Tilstandsmåling: hver {0}s, neste om {1}s",
        "Export File Name" => "Eksporter filnavn",
        "Export file name for {0} (without .md):" => "Eksporter filnavn for {0} (uten .md):",
        "The same name lets you group multiple stacks/notebooks." => "Det samme navnet lar deg gruppere flere stabler/notatbøker.",
        "Invalid name. Use at least one valid character." => "Ugyldig navn. Bruk minst ett gyldig tegn.",
        "Language" => "Språk",
        "Choose the UI language" => "Velg UI-språket",
        "System default" => "Systemstandard",
        "Close button behavior:" => "Oppførsel av lukkeknapp:",
        "Minimize to tray" => "Minimer til brett",
        "Close app" => "Lukk appen",
        "Controls what happens when you click the window close button." => "Styrer hva som skjer når du klikker på lukkeknappen for vinduet.",
        "Enable debug logs" => "Aktiver feilsøkingslogger",
        "Local config file: {0}" => "Lokal konfigurasjonsfil: {0}",
        "Google Drive config sync" => "Google Disk-konfigurasjonssynkronisering",
        "Enable Google Drive sync" => "Aktiver Google Disk-synkronisering",
        "Auto-restore at startup" => "Automatisk gjenoppretting ved oppstart",
        "Click the button below to connect with Google OAuth." => "Klikk på knappen nedenfor for å koble til Google OAuth.",
        "Connect with Google" => "Koble til Google",
        "OAuth status: configured." => "OAuth-status: konfigurert.",
        "OAuth status: not connected." => "OAuth-status: ikke tilkoblet.",
        "OAuth status: connecting..." => "OAuth-status: kobler til...",
        "Unknown OAuth error." => "Ukjent OAuth-feil.",
        "OAuth status: failed ({0})" => "OAuth-status: mislyktes ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth-tilkobling mislyktes.{0}{0}{1}",
        "Google Drive OAuth" => "Google Disk OAuth",
        "Google account connected" => "Google-kontoen er tilkoblet",
        "(not detected)" => "(ikke oppdaget)",
        "OAuth client source: {0}" => "OAuth-klientkilde: {0}",
        "Drive file ID (optional):" => "Drive-fil-ID (valgfritt):",
        "Export settings" => "Eksporter innstillinger",
        "Import settings" => "Importer innstillinger",
        "Select Google OAuth credentials JSON" => "Velg Google OAuth-legitimasjon JSON",
        "OAuth status: credentials file required." => "OAuth-status: legitimasjonsfil kreves.",
        "OAuth status: error ({0})" => "OAuth-status: feil ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Kan ikke lese OAuth-legitimasjon.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth-status: tilkoblet ({0}).",
        "Settings exported to:{0}{1}" => "Innstillinger eksportert til:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Kan ikke eksportere innstillinger.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Import av en innstillingsfil vil erstatte din nåværende lokale konfigurasjon. Fortsette?",
        "Unable to read the selected file.{0}{0}{1}" => "Kan ikke lese den valgte filen.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Den valgte filen inneholder ikke gyldige JSON-innstillinger.",
        "Settings imported from:{0}{1}" => "Innstillinger importert fra:{0}{1}",
        _ => english
    };
}



