namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateBs(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Evernote izvoz",
        "Settings" => "Postavke",
        "Save" => "Sačuvaj",
        "Cancel" => "Otkaži",
        "App:" => "aplikacija:",
        "Refresh" => "Osvježi",
        "Log out" => "Odjavite se",
        "Switch to" => "Prebaci na",
        "Exit" => "Izađi",
        "{0} is still running" => "{0} još uvijek radi",
        "Use the tray icon to reopen or exit." => "Koristite ikonu u traci da ponovo otvorite ili izađete.",
        "Ignore" => "Ignoriraj",
        "Ignore {0}" => "Zanemari {0}",
        "Unignore {0}" => "Zanemari {0}",
        "Set export file for {0}..." => "Postavi fajl za izvoz za {0}...",
        "Clear export file name" => "Obriši naziv datoteke za izvoz",
        "Clear export file ({0})" => "Obriši fajl za izvoz ({0})",
        "stack" => "stog",
        "notebook" => "notebook",
        "Select the Evernote root folder, then export the checked notebooks." => "Odaberite korijensku mapu Evernotea, a zatim izvezite označene bilježnice.",
        "Evernote Folder..." => "Evernote folder...",
        "Reload" => "Ponovo učitaj",
        "Export" => "Izvoz",
        "Evernote polling frequency (minutes):" => "Učestalost anketiranja Evernotea (minuta):",
        "Pause automatic polling" => "Pauzirajte automatsko glasanje",
        "Lock: (none)" => "Zaključavanje: (nema)",
        "Force" => "Force",
        "State poll: every 6s, next in --s" => "Državna anketa: svakih 6s, sljedeće za --s",
        "Keep last X markdown exports:" => "Zadrži posljednje X izvoze umanjenja vrijednosti:",
        "Older files in ./markdown will be deleted automatically after each export." => "Starije datoteke u ./markdown će se automatski izbrisati nakon svakog izvoza.",
        "No Evernote folder selected." => "Nije odabran nijedan Evernote folder.",
        "Show ignored" => "Prikaži zanemareno",
        "Right-click: ignore or set export file name." => "Desni klik: zanemarite ili postavite naziv datoteke za izvoz.",
        "Choose the root folder of the Evernote installation" => "Odaberite korijenski folder instalacije Evernotea",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB otkriven: {0} | Stogovi: {1} | Bilježnice: {2}",
        "DB error: {0}" => "DB greška: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Nije moguće pročitati Evernote bazu podataka.{0}{0}{1}",
        " [ignored]" => "[ignorirano]",
        " | updated: {0}" => "| ažurirano: {0}",
        " | export: {0}.md" => "| izvoz: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} notebooks){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} bilješke){2}{3}{4}",
        "(none)" => "(nijedna)",
        "Lock: {0}" => "Zaključavanje: {0}",
        "awaiting confirmation from {0}" => "čekam potvrdu od {0}",
        "State poll: every {0}s, next in {1}s" => "Državna anketa: svakih {0}s, sljedeće za {1}s",
        "Export File Name" => "Izvezi naziv datoteke",
        "Export file name for {0} (without .md):" => "Izvezi naziv datoteke za {0} (bez .md):",
        "The same name lets you group multiple stacks/notebooks." => "Isti naziv vam omogućava grupisanje više hrpa/bilježnica.",
        "Invalid name. Use at least one valid character." => "Nevažeći naziv. Koristite barem jedan važeći znak.",
        "Language" => "Jezik",
        "Choose the UI language" => "Odaberite jezik korisničkog sučelja",
        "System default" => "Sistemski zadani",
        "Close button behavior:" => "Ponašanje dugmeta za zatvaranje:",
        "Minimize to tray" => "Minimizirajte u poslužavnik",
        "Close app" => "Zatvorite aplikaciju",
        "Controls what happens when you click the window close button." => "Kontrolira šta se dešava kada kliknete na dugme za zatvaranje prozora.",
        "Enable debug logs" => "Omogućite evidenciju otklanjanja grešaka",
        "Local config file: {0}" => "Lokalni konfiguracioni fajl: {0}",
        "Google Drive config sync" => "Sinhronizacija konfiguracije Google diska",
        "Enable Google Drive sync" => "Omogućite sinhronizaciju Google diska",
        "Auto-restore at startup" => "Automatsko vraćanje pri pokretanju",
        "Click the button below to connect with Google OAuth." => "Kliknite na dugme ispod da se povežete sa Google OAuthom.",
        "Connect with Google" => "Povežite se s Googleom",
        "OAuth status: configured." => "OAuth status: konfigurisan.",
        "OAuth status: not connected." => "OAuth status: nije povezan.",
        "OAuth status: connecting..." => "OAuth status: povezivanje...",
        "Unknown OAuth error." => "Nepoznata OAuth greška.",
        "OAuth status: failed ({0})" => "OAuth status: neuspješan ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth veza nije uspjela.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Google račun je povezan",
        "(not detected)" => "(nije otkriveno)",
        "OAuth client source: {0}" => "Izvor OAuth klijenta: {0}",
        "Drive file ID (optional):" => "ID fajla na disku (opcionalno):",
        "Export settings" => "Izvoz postavki",
        "Import settings" => "Uvezite postavke",
        "Select Google OAuth credentials JSON" => "Odaberite Google OAuth vjerodajnice JSON",
        "OAuth status: credentials file required." => "OAuth status: potrebna je datoteka akreditiva.",
        "OAuth status: error ({0})" => "OAuth status: greška ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Nije moguće pročitati OAuth akreditive.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth status: povezan ({0}).",
        "Settings exported to:{0}{1}" => "Postavke izvezene u:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Nije moguće izvesti postavke.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Uvoz datoteke postavki zamijenit će vašu trenutnu lokalnu konfiguraciju. Nastaviti?",
        "Unable to read the selected file.{0}{0}{1}" => "Nije moguće pročitati odabranu datoteku.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Odabrani fajl ne sadrži važeće postavke JSON.",
        "Settings imported from:{0}{1}" => "Postavke uvezene sa:{0}{1}",
        _ => english
    };
}



