namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateZhHant(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google雲端硬碟",
        "Evernote Export" => "印象筆記導出",
        "Settings" => "設定",
        "Save" => "節省",
        "Cancel" => "取消",
        "App:" => "應用程式:",
        "Refresh" => "重新整理",
        "Log out" => "退出",
        "Switch to" => "切換到",
        "Exit" => "出口",
        "{0} is still running" => "{0} 仍在運作",
        "Use the tray icon to reopen or exit." => "使用托盤圖示重新打開或退出。",
        "Ignore" => "忽略",
        "Ignore {0}" => "忽略 {0}",
        "Unignore {0}" => "忽略 {0}",
        "Set export file for {0}..." => "設定匯出檔案為 {0}...",
        "Clear export file name" => "清除匯出檔名",
        "Clear export file ({0})" => "清除匯出檔案 ({0})",
        "stack" => "堆疊",
        "notebook" => "筆記本",
        "Select the Evernote root folder, then export the checked notebooks." => "選擇 Evernote 根資料夾，然後匯出選取的筆記本。",
        "Evernote Folder..." => "印象筆記資料夾...",
        "Reload" => "重新載入",
        "Export" => "出口",
        "Evernote polling frequency (minutes):" => "Evernote 投票頻率（分鐘）：",
        "Pause automatic polling" => "暫停自動輪詢",
        "Lock: (none)" => "鎖：（無）",
        "Force" => "力量",
        "State poll: every 6s, next in --s" => "狀態民調：每 6 秒一次，下一個 --s 後",
        "Keep last X markdown exports:" => "保留最後 X 個降價匯出：",
        "Older files in ./markdown will be deleted automatically after each export." => "每次匯出後，./markdown 中的舊檔案將會自動刪除。",
        "No Evernote folder selected." => "未選擇 Evernote 資料夾。",
        "Show ignored" => "顯示忽略",
        "Right-click: ignore or set export file name." => "右鍵單擊：忽略或設定匯出檔案名稱。",
        "Choose the root folder of the Evernote installation" => "選擇 Evernote 安裝的根資料夾",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "偵測到資料庫：{0} |堆疊：{1} |筆記本：{2}",
        "DB error: {0}" => "資料庫錯誤：{0}",
        "Unable to read Evernote database.{0}{0}{1}" => "無法讀取 Evernote 資料庫。 {0}{0}{1}",
        " [ignored]" => "[忽略]",
        " | updated: {0}" => "|更新：{0}",
        " | export: {0}.md" => "|匯出：{0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0}（{1} 筆記本）{2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0}（{1} 註釋）{2}{3}{4}",
        "(none)" => "（沒有任何）",
        "Lock: {0}" => "鎖：{0}",
        "awaiting confirmation from {0}" => "等待 {0} 的確認",
        "State poll: every {0}s, next in {1}s" => "州民調：每 {0} 秒，下一個 {1} 秒",
        "Export File Name" => "匯出檔名",
        "Export file name for {0} (without .md):" => "{0} 的匯出檔名（不含 .md）：",
        "The same name lets you group multiple stacks/notebooks." => "相同的名稱可讓您將多個堆疊/筆記本分組。",
        "Invalid name. Use at least one valid character." => "名稱無效。至少使用一個有效字元。",
        "Language" => "語言",
        "Choose the UI language" => "選擇使用者介面語言",
        "System default" => "系統預設",
        "Close button behavior:" => "關閉按鈕行為：",
        "Minimize to tray" => "最小化到托盤",
        "Close app" => "關閉應用程式",
        "Controls what happens when you click the window close button." => "控制點擊視窗關閉按鈕時發生的情況。",
        "Enable debug logs" => "啟用調試日誌",
        "Local config file: {0}" => "本機設定檔：{0}",
        "Google Drive config sync" => "Google 雲端硬碟設定同步",
        "Enable Google Drive sync" => "啟用 Google 雲端硬碟同步",
        "Auto-restore at startup" => "啟動時自動恢復",
        "Click the button below to connect with Google OAuth." => "點擊下面的按鈕連接 Google OAuth。",
        "Connect with Google" => "與Google連接",
        "OAuth status: configured." => "OAuth 狀態：已配置。",
        "OAuth status: not connected." => "OAuth 狀態：未連線。",
        "OAuth status: connecting..." => "OAuth 狀態：正在連線...",
        "Unknown OAuth error." => "未知的 OAuth 錯誤。",
        "OAuth status: failed ({0})" => "OAuth 狀態：失敗 ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth 連線失敗。 {0}{0}{1}",
        "Google Drive OAuth" => "Google 雲端硬碟 OAuth",
        "Google account connected" => "已連結 Google 帳戶",
        "(not detected)" => "（未檢測到）",
        "OAuth client source: {0}" => "OAuth 客戶端來源：{0}",
        "Drive file ID (optional):" => "磁碟機檔案 ID（可選）：",
        "Export settings" => "匯出設定",
        "Import settings" => "導入設定",
        "Select Google OAuth credentials JSON" => "選擇 Google OAuth 憑證 JSON",
        "OAuth status: credentials file required." => "OAuth 狀態：需要憑證檔案。",
        "OAuth status: error ({0})" => "OAuth 狀態：錯誤 ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "無法讀取 OAuth 憑證。 {0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth 狀態：已連線 ({0})。",
        "Settings exported to:{0}{1}" => "設定匯出到：{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "無法導出設定。 {0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "導入設定檔將取代您目前的本機配置。繼續？",
        "Unable to read the selected file.{0}{0}{1}" => "無法讀取所選檔案。 {0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "所選檔案不包含有效的設定 JSON。",
        "Settings imported from:{0}{1}" => "設定導入自：{0}{1}",
        _ => english
    };
}



