namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateSl(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Izvoz Evernote",
        "Settings" => "nastavitve",
        "Save" => "Shrani",
        "Cancel" => "Prekliči",
        "App:" => "Aplikacija:",
        "Refresh" => "Osveži",
        "Log out" => "Odjava",
        "Switch to" => "Preklopi na",
        "Exit" => "Izhod",
        "{0} is still running" => "{0} še vedno teče",
        "Use the tray icon to reopen or exit." => "Za ponovno odpiranje ali izhod uporabite ikono pladnja.",
        "Ignore" => "Ignoriraj",
        "Ignore {0}" => "Ignoriraj {0}",
        "Unignore {0}" => "Prezri {0}",
        "Set export file for {0}..." => "Nastavi izvozno datoteko za {0} ...",
        "Clear export file name" => "Počisti ime izvozne datoteke",
        "Clear export file ({0})" => "Počisti izvozno datoteko ({0})",
        "stack" => "kup",
        "notebook" => "zvezek",
        "Select the Evernote root folder, then export the checked notebooks." => "Izberite korensko mapo Evernote in nato izvozite označene zvezke.",
        "Evernote Folder..." => "Mapa Evernote ...",
        "Reload" => "Ponovno naloži",
        "Export" => "Izvozi",
        "Evernote polling frequency (minutes):" => "Frekvenca anketiranja Evernote (minute):",
        "Pause automatic polling" => "Zaustavi samodejno glasovanje",
        "Lock: (none)" => "Zaklepanje: (brez)",
        "Force" => "Sila",
        "State poll: every 6s, next in --s" => "Državna anketa: vsakih 6s, naslednja čez --s",
        "Keep last X markdown exports:" => "Ohrani zadnje X izvoze oznak:",
        "Older files in ./markdown will be deleted automatically after each export." => "Starejše datoteke v ./markdown bodo samodejno izbrisane po vsakem izvozu.",
        "No Evernote folder selected." => "Izbrana ni nobena mapa Evernote.",
        "Show ignored" => "Prikaži prezrto",
        "Right-click: ignore or set export file name." => "Desni klik: prezri ali nastavi ime izvozne datoteke.",
        "Choose the root folder of the Evernote installation" => "Izberite korensko mapo namestitve Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "Zaznan DB: {0} | Skupi: {1} | Zvezki: {2}",
        "DB error: {0}" => "Napaka DB: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Ni mogoče prebrati zbirke podatkov Evernote.{0}{0}{1}",
        " [ignored]" => "[prezrto]",
        " | updated: {0}" => "| posodobljeno: {0}",
        " | export: {0}.md" => "| izvoz: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} zvezkov){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} opombe){2}{3}{4}",
        "(none)" => "(brez)",
        "Lock: {0}" => "Zaklepanje: {0}",
        "awaiting confirmation from {0}" => "čakam na potrditev od {0}",
        "State poll: every {0}s, next in {1}s" => "Državna anketa: vsakih {0}s, naslednja čez {1}s",
        "Export File Name" => "Ime izvozne datoteke",
        "Export file name for {0} (without .md):" => "Ime izvozne datoteke za {0} (brez .md):",
        "The same name lets you group multiple stacks/notebooks." => "Isto ime vam omogoča združevanje več skladov/zvezkov.",
        "Invalid name. Use at least one valid character." => "Neveljavno ime. Uporabite vsaj en veljaven znak.",
        "Language" => "Jezik",
        "Choose the UI language" => "Izberite jezik uporabniškega vmesnika",
        "System default" => "Sistemsko privzeto",
        "Close button behavior:" => "Delovanje gumba za zapiranje:",
        "Minimize to tray" => "Pomanjšaj na pladenj",
        "Close app" => "Zapri aplikacijo",
        "Controls what happens when you click the window close button." => "Nadzira, kaj se zgodi, ko kliknete gumb za zapiranje okna.",
        "Enable debug logs" => "Omogoči dnevnike odpravljanja napak",
        "Local config file: {0}" => "Lokalna konfiguracijska datoteka: {0}",
        "Google Drive config sync" => "Sinhronizacija konfiguracije Google Drive",
        "Enable Google Drive sync" => "Omogoči sinhronizacijo Google Drive",
        "Auto-restore at startup" => "Samodejna obnovitev ob zagonu",
        "Click the button below to connect with Google OAuth." => "Za povezavo z Google OAuth kliknite spodnji gumb.",
        "Connect with Google" => "Povežite se z Googlom",
        "OAuth status: configured." => "Stanje OAuth: konfigurirano.",
        "OAuth status: not connected." => "Stanje OAuth: ni povezano.",
        "OAuth status: connecting..." => "Stanje OAuth: povezovanje ...",
        "Unknown OAuth error." => "Neznana napaka OAuth.",
        "OAuth status: failed ({0})" => "Stanje OAuth: ni uspelo ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Povezava OAuth ni uspela.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Google račun je povezan",
        "(not detected)" => "(ni zaznano)",
        "OAuth client source: {0}" => "Vir odjemalca OAuth: {0}",
        "Drive file ID (optional):" => "ID datoteke Drive (neobvezno):",
        "Export settings" => "Izvozi nastavitve",
        "Import settings" => "Uvozi nastavitve",
        "Select Google OAuth credentials JSON" => "Izberite poverilnice Google OAuth JSON",
        "OAuth status: credentials file required." => "Stanje OAuth: potrebna je datoteka s poverilnicami.",
        "OAuth status: error ({0})" => "Stanje OAuth: napaka ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Ni mogoče prebrati poverilnic OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Stanje OAuth: vzpostavljena povezava ({0}).",
        "Settings exported to:{0}{1}" => "Nastavitve izvožene v: {0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Nastavitev ni mogoče izvoziti.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Uvoz datoteke z nastavitvami bo nadomestil vašo trenutno lokalno konfiguracijo. Nadaljevati?",
        "Unable to read the selected file.{0}{0}{1}" => "Izbrane datoteke ni mogoče prebrati.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Izbrana datoteka ne vsebuje veljavnih nastavitev JSON.",
        "Settings imported from:{0}{1}" => "Nastavitve, uvožene iz: {0}{1}",
        _ => english
    };
}



