namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateMk(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Evernote Export",
        "Settings" => "Поставки",
        "Save" => "Зачувај",
        "Cancel" => "Откажи",
        "App:" => "Апликација:",
        "Refresh" => "Освежи",
        "Log out" => "Одјави се",
        "Switch to" => "Префрли се на",
        "Exit" => "Излезете",
        "{0} is still running" => "{0} сè уште работи",
        "Use the tray icon to reopen or exit." => "Користете ја иконата во фиоката за повторно отворање или излез.",
        "Ignore" => "Игнорирај",
        "Ignore {0}" => "Игнорирај {0}",
        "Unignore {0}" => "Не игнорирај {0}",
        "Set export file for {0}..." => "Поставете датотека за извоз за {0}...",
        "Clear export file name" => "Исчистете го името на датотеката за извоз",
        "Clear export file ({0})" => "Исчистете ја датотеката за извоз ({0})",
        "stack" => "магацинот",
        "notebook" => "тетратка",
        "Select the Evernote root folder, then export the checked notebooks." => "Изберете ја основната папка на Evernote, а потоа извезете ги проверените тетратки.",
        "Evernote Folder..." => "Папката Evernote...",
        "Reload" => "Вчитај повторно",
        "Export" => "Извоз",
        "Evernote polling frequency (minutes):" => "Фреквенција на гласање на Evernote (минути):",
        "Pause automatic polling" => "Паузирајте го автоматското гласање",
        "Lock: (none)" => "Заклучување: (нема)",
        "Force" => "Сила",
        "State poll: every 6s, next in --s" => "Државна анкета: на секои 6 секунди, следната во ---и",
        "Keep last X markdown exports:" => "Задржете го последниот извоз со X означување:",
        "Older files in ./markdown will be deleted automatically after each export." => "Постарите датотеки во ./markdown ќе се бришат автоматски по секое извезување.",
        "No Evernote folder selected." => "Не е избрана папка Evernote.",
        "Show ignored" => "Прикажи игнориран",
        "Right-click: ignore or set export file name." => "Десен-клик: игнорирајте или поставете име на датотека за извоз.",
        "Choose the root folder of the Evernote installation" => "Изберете ја основната папка на инсталацијата на Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "Откриен DB: {0} | Купишта: {1} | Тетратки: {2}",
        "DB error: {0}" => "Грешка во DB: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Не можам да ја прочитам базата на податоци на Evernote.{0}{0}{1}",
        " [ignored]" => "[игнорирано]",
        " | updated: {0}" => "| ажурирано: {0}",
        " | export: {0}.md" => "| извоз: {0}.мд",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} тетратки){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} белешки){2}{3}{4}",
        "(none)" => "(никој)",
        "Lock: {0}" => "Заклучување: {0}",
        "awaiting confirmation from {0}" => "се чека потврда од {0}",
        "State poll: every {0}s, next in {1}s" => "Државна анкета: на секои {0}s, следната во {1}s",
        "Export File Name" => "Извези име на датотека",
        "Export file name for {0} (without .md):" => "Извези име на датотека за {0} (без .md):",
        "The same name lets you group multiple stacks/notebooks." => "Истото име ви овозможува да групирате повеќе стекови/тетратки.",
        "Invalid name. Use at least one valid character." => "Неважечко име. Користете барем еден валиден знак.",
        "Language" => "Јазик",
        "Choose the UI language" => "Изберете го јазикот на корисничкиот интерфејс",
        "System default" => "Стандардно на системот",
        "Close button behavior:" => "Однесување на копчето за затворање:",
        "Minimize to tray" => "Минимизирајте до послужавник",
        "Close app" => "Затворете ја апликацијата",
        "Controls what happens when you click the window close button." => "Контролира што се случува кога ќе кликнете на копчето за затворање на прозорецот.",
        "Enable debug logs" => "Овозможи евиденција за отстранување грешки",
        "Local config file: {0}" => "Локална конфигурациска датотека: {0}",
        "Google Drive config sync" => "Синхронизација на конфигурацијата на Google Drive",
        "Enable Google Drive sync" => "Овозможете синхронизација на Google Drive",
        "Auto-restore at startup" => "Автоматско враќање при стартување",
        "Click the button below to connect with Google OAuth." => "Кликнете на копчето подолу за да се поврзете со Google OAuth.",
        "Connect with Google" => "Поврзете се со Google",
        "OAuth status: configured." => "Статус на OAuth: конфигуриран.",
        "OAuth status: not connected." => "Статус на OAuth: не е поврзан.",
        "OAuth status: connecting..." => "Статус на OAuth: се поврзува...",
        "Unknown OAuth error." => "Непозната грешка на OAuth.",
        "OAuth status: failed ({0})" => "Статус на OAuth: не успеа ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Врската за OAuth не успеа.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Поврзана е сметката на Google",
        "(not detected)" => "(не е откриен)",
        "OAuth client source: {0}" => "Извор на клиент OAuth: {0}",
        "Drive file ID (optional):" => "ID на датотека на диск (изборно):",
        "Export settings" => "Извези поставки",
        "Import settings" => "Увезете поставки",
        "Select Google OAuth credentials JSON" => "Изберете акредитиви на Google OAuth JSON",
        "OAuth status: credentials file required." => "Статус на OAuth: потребна е датотека со ингеренциите.",
        "OAuth status: error ({0})" => "Статус на OAuth: грешка ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Не можам да ги прочитам ингеренциите за OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Статус на OAuth: поврзан ({0}).",
        "Settings exported to:{0}{1}" => "Поставките се извезени на:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Не може да се извезат поставките.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Увезувањето датотека со поставки ќе ја замени вашата тековна локална конфигурација. Да продолжиме?",
        "Unable to read the selected file.{0}{0}{1}" => "Не можам да ја прочитам избраната датотека.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Избраната датотека не содржи валидни поставки JSON.",
        "Settings imported from:{0}{1}" => "Увезени поставки од:{0}{1}",
        _ => english
    };
}



