namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateBn(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "গুগল ড্রাইভ",
        "Evernote Export" => "Evernote এক্সপোর্ট",
        "Settings" => "সেটিংস",
        "Save" => "সংরক্ষণ করুন",
        "Cancel" => "বাতিল করুন",
        "App:" => "অ্যাপ:",
        "Refresh" => "রিফ্রেশ",
        "Log out" => "লগ আউট করুন",
        "Switch to" => "এ স্যুইচ করুন",
        "Exit" => "প্রস্থান করুন",
        "{0} is still running" => "{0} এখনও চলছে৷",
        "Use the tray icon to reopen or exit." => "পুনরায় খুলতে বা প্রস্থান করতে ট্রে আইকনটি ব্যবহার করুন।",
        "Ignore" => "উপেক্ষা করুন",
        "Ignore {0}" => "উপেক্ষা করুন {0}",
        "Unignore {0}" => "উপেক্ষা করুন {0}",
        "Set export file for {0}..." => "{0} এর জন্য এক্সপোর্ট ফাইল সেট করুন...",
        "Clear export file name" => "এক্সপোর্ট ফাইলের নাম সাফ করুন",
        "Clear export file ({0})" => "রপ্তানি ফাইল সাফ করুন ({0})",
        "stack" => "স্ট্যাক",
        "notebook" => "নোটবুক",
        "Select the Evernote root folder, then export the checked notebooks." => "Evernote রুট ফোল্ডার নির্বাচন করুন, তারপর চেক করা নোটবুক রপ্তানি করুন।",
        "Evernote Folder..." => "Evernote ফোল্ডার...",
        "Reload" => "পুনরায় লোড করুন",
        "Export" => "রপ্তানি",
        "Evernote polling frequency (minutes):" => "Evernote পোলিং ফ্রিকোয়েন্সি (মিনিট):",
        "Pause automatic polling" => "স্বয়ংক্রিয় ভোটগ্রহণ বিরতি",
        "Lock: (none)" => "তালা: (কোনও নয়)",
        "Force" => "বল",
        "State poll: every 6s, next in --s" => "রাজ্য ভোট: প্রতি 6 সেকেন্ডে, পরবর্তী --s-এ",
        "Keep last X markdown exports:" => "শেষ এক্স মার্কডাউন রপ্তানি রাখুন:",
        "Older files in ./markdown will be deleted automatically after each export." => "./markdown-এর পুরানো ফাইলগুলি প্রতিটি রপ্তানির পরে স্বয়ংক্রিয়ভাবে মুছে যাবে৷",
        "No Evernote folder selected." => "কোনো Evernote ফোল্ডার নির্বাচন করা হয়নি।",
        "Show ignored" => "উপেক্ষা দেখান",
        "Right-click: ignore or set export file name." => "ডান-ক্লিক করুন: উপেক্ষা করুন বা এক্সপোর্ট ফাইলের নাম সেট করুন।",
        "Choose the root folder of the Evernote installation" => "Evernote ইনস্টলেশনের রুট ফোল্ডারটি নির্বাচন করুন",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB সনাক্ত করা হয়েছে: {0} | স্ট্যাক: {1} | নোটবুক: {2}",
        "DB error: {0}" => "DB ত্রুটি: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Evernote ডাটাবেস পড়তে অক্ষম।{0}{0}{1}",
        " [ignored]" => "[উপেক্ষিত]",
        " | updated: {0}" => "| আপডেট করা হয়েছে: {0}",
        " | export: {0}.md" => "| রপ্তানি: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} নোটবুক){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} নোট){2}{3}{4}",
        "(none)" => "(কোনও)",
        "Lock: {0}" => "লক: {0}",
        "awaiting confirmation from {0}" => "{0} থেকে নিশ্চিতকরণের অপেক্ষায়",
        "State poll: every {0}s, next in {1}s" => "রাজ্য ভোট: প্রতি {0} সেকেন্ডে, পরবর্তী {1} সেকেন্ডে",
        "Export File Name" => "ফাইলের নাম রপ্তানি করুন",
        "Export file name for {0} (without .md):" => "{0} এর জন্য ফাইলের নাম রপ্তানি করুন (.md ছাড়া):",
        "The same name lets you group multiple stacks/notebooks." => "একই নাম আপনাকে একাধিক স্ট্যাক/নোটবুক গ্রুপ করতে দেয়।",
        "Invalid name. Use at least one valid character." => "অবৈধ নাম। অন্তত একটি বৈধ অক্ষর ব্যবহার করুন.",
        "Language" => "ভাষা",
        "Choose the UI language" => "UI ভাষা নির্বাচন করুন",
        "System default" => "সিস্টেম ডিফল্ট",
        "Close button behavior:" => "বন্ধ বোতাম আচরণ:",
        "Minimize to tray" => "ট্রেতে ছোট করুন",
        "Close app" => "অ্যাপ বন্ধ করুন",
        "Controls what happens when you click the window close button." => "আপনি উইন্ডো বন্ধ করার বোতামে ক্লিক করলে কী ঘটবে তা নিয়ন্ত্রণ করে।",
        "Enable debug logs" => "ডিবাগ লগ সক্রিয় করুন",
        "Local config file: {0}" => "স্থানীয় কনফিগারেশন ফাইল: {0}",
        "Google Drive config sync" => "গুগল ড্রাইভ কনফিগারেশন সিঙ্ক",
        "Enable Google Drive sync" => "Google ড্রাইভ সিঙ্ক সক্ষম করুন৷",
        "Auto-restore at startup" => "স্টার্টআপে অটো-রিস্টোর",
        "Click the button below to connect with Google OAuth." => "Google OAuth এর সাথে সংযোগ করতে নীচের বোতামে ক্লিক করুন৷",
        "Connect with Google" => "Google এর সাথে সংযোগ করুন",
        "OAuth status: configured." => "OAuth স্থিতি: কনফিগার করা হয়েছে।",
        "OAuth status: not connected." => "OAuth স্থিতি: সংযুক্ত নয়।",
        "OAuth status: connecting..." => "OAuth স্থিতি: সংযোগ করা হচ্ছে...",
        "Unknown OAuth error." => "অজানা OAuth ত্রুটি৷",
        "OAuth status: failed ({0})" => "OAuth স্থিতি: ব্যর্থ ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth সংযোগ ব্যর্থ হয়েছে৷{0}_{0}_PH1__",
        "Google Drive OAuth" => "Google ড্রাইভ OAuth",
        "Google account connected" => "Google অ্যাকাউন্ট সংযুক্ত",
        "(not detected)" => "(শনাক্ত হয়নি)",
        "OAuth client source: {0}" => "OAuth ক্লায়েন্ট উত্স: {0}",
        "Drive file ID (optional):" => "ড্রাইভ ফাইল আইডি (ঐচ্ছিক):",
        "Export settings" => "রপ্তানি সেটিংস",
        "Import settings" => "সেটিংস আমদানি করুন",
        "Select Google OAuth credentials JSON" => "Google OAuth শংসাপত্র JSON নির্বাচন করুন",
        "OAuth status: credentials file required." => "OAuth স্থিতি: শংসাপত্র ফাইল প্রয়োজন।",
        "OAuth status: error ({0})" => "OAuth স্থিতি: ত্রুটি ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "OAuth শংসাপত্র পড়তে অক্ষম৷{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth স্থিতি: সংযুক্ত ({0})।",
        "Settings exported to:{0}{1}" => "সেটিংস এতে রপ্তানি করা হয়েছে:{0}PH1__",
        "Unable to export settings.{0}{0}{1}" => "সেটিংস রপ্তানি করতে অক্ষম৷{0}_{0}_PH1__",
        "Importing a settings file will replace your current local configuration. Continue?" => "একটি সেটিংস ফাইল আমদানি করা আপনার বর্তমান স্থানীয় কনফিগারেশন প্রতিস্থাপন করবে। চালিয়ে যান?",
        "Unable to read the selected file.{0}{0}{1}" => "নির্বাচিত ফাইল পড়তে অক্ষম৷{0}_{0}_PH1__",
        "The selected file does not contain valid settings JSON." => "নির্বাচিত ফাইলে বৈধ সেটিংস JSON নেই।",
        "Settings imported from:{0}{1}" => "সেটিংস থেকে আমদানি করা হয়েছে:{0}PH1__",
        _ => english
    };
}



