namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateCa(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Exportació Evernote",
        "Settings" => "Configuració",
        "Save" => "Desa",
        "Cancel" => "Cancel·la",
        "App:" => "Aplicació:",
        "Refresh" => "Actualitza",
        "Log out" => "Tanca la sessió",
        "Switch to" => "Canvia a",
        "Exit" => "Sortida",
        "{0} is still running" => "{0} encara s'està executant",
        "Use the tray icon to reopen or exit." => "Utilitzeu la icona de la safata per tornar a obrir o sortir.",
        "Ignore" => "Ignorar",
        "Ignore {0}" => "Ignora {0}",
        "Unignore {0}" => "No ignora {0}",
        "Set export file for {0}..." => "Estableix el fitxer d'exportació per a {0}...",
        "Clear export file name" => "Esborra el nom del fitxer d'exportació",
        "Clear export file ({0})" => "Esborra el fitxer d'exportació ({0})",
        "stack" => "pila",
        "notebook" => "llibreta",
        "Select the Evernote root folder, then export the checked notebooks." => "Seleccioneu la carpeta arrel d'Evernote i exporteu els quaderns marcats.",
        "Evernote Folder..." => "Carpeta Evernote...",
        "Reload" => "Torna a carregar",
        "Export" => "Exporta",
        "Evernote polling frequency (minutes):" => "Freqüència d'enquesta d'Evernote (minuts):",
        "Pause automatic polling" => "Posa en pausa l'enquesta automàtica",
        "Lock: (none)" => "Bloqueig: (cap)",
        "Force" => "Força",
        "State poll: every 6s, next in --s" => "Enquesta estatal: cada 6 segons, següent en --s",
        "Keep last X markdown exports:" => "Mantenir les darreres exportacions de rebaixes X:",
        "Older files in ./markdown will be deleted automatically after each export." => "Els fitxers més antics de ./markdown se suprimiran automàticament després de cada exportació.",
        "No Evernote folder selected." => "No s'ha seleccionat cap carpeta Evernote.",
        "Show ignored" => "Mostra ignorat",
        "Right-click: ignore or set export file name." => "Feu clic amb el botó dret: ignora o defineix el nom del fitxer d'exportació.",
        "Choose the root folder of the Evernote installation" => "Trieu la carpeta arrel de la instal·lació d'Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "Base de dades detectada: {0} | Piles: {1} | Quaderns: {2}",
        "DB error: {0}" => "Error de base de dades: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "No es pot llegir la base de dades d'Evernote.{0}{0}{1}",
        " [ignored]" => "[ignorat]",
        " | updated: {0}" => "| actualitzat: {0}",
        " | export: {0}.md" => "| exportar: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} quaderns){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} notes){2}{3}{4}",
        "(none)" => "(cap)",
        "Lock: {0}" => "Bloqueig: {0}",
        "awaiting confirmation from {0}" => "esperant confirmació de {0}",
        "State poll: every {0}s, next in {1}s" => "Enquesta estatal: cada {0}s, la següent en {1}s",
        "Export File Name" => "Exporta el nom del fitxer",
        "Export file name for {0} (without .md):" => "Exporta el nom del fitxer per a {0} (sense .md):",
        "The same name lets you group multiple stacks/notebooks." => "El mateix nom us permet agrupar diverses piles/quaderns.",
        "Invalid name. Use at least one valid character." => "Nom no vàlid. Utilitzeu almenys un caràcter vàlid.",
        "Language" => "Llengua",
        "Choose the UI language" => "Trieu l'idioma de la IU",
        "System default" => "Sistema predeterminat",
        "Close button behavior:" => "Comportament del botó de tancament:",
        "Minimize to tray" => "Minimitzar a la safata",
        "Close app" => "Tanca l'aplicació",
        "Controls what happens when you click the window close button." => "Controla què passa quan feu clic al botó de tancament de la finestra.",
        "Enable debug logs" => "Activa els registres de depuració",
        "Local config file: {0}" => "Fitxer de configuració local: {0}",
        "Google Drive config sync" => "Sincronització de la configuració de Google Drive",
        "Enable Google Drive sync" => "Activa la sincronització de Google Drive",
        "Auto-restore at startup" => "Restauració automàtica a l'inici",
        "Click the button below to connect with Google OAuth." => "Feu clic al botó següent per connectar-vos amb Google OAuth.",
        "Connect with Google" => "Connecta't amb Google",
        "OAuth status: configured." => "Estat OAuth: configurat.",
        "OAuth status: not connected." => "Estat OAuth: no connectat.",
        "OAuth status: connecting..." => "Estat OAuth: connectant...",
        "Unknown OAuth error." => "Error d'OAuth desconegut.",
        "OAuth status: failed ({0})" => "Estat d'OAuth: fallat ({0})",
        "OAuth connection failed.{0}{0}{1}" => "La connexió OAuth ha fallat.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Compte de Google connectat",
        "(not detected)" => "(no detectat)",
        "OAuth client source: {0}" => "Font del client OAuth: {0}",
        "Drive file ID (optional):" => "Identificador del fitxer de la unitat (opcional):",
        "Export settings" => "Exporta la configuració",
        "Import settings" => "Importa la configuració",
        "Select Google OAuth credentials JSON" => "Seleccioneu les credencials JSON de Google OAuth",
        "OAuth status: credentials file required." => "Estat OAuth: cal un fitxer de credencials.",
        "OAuth status: error ({0})" => "Estat d'OAuth: error ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "No es poden llegir les credencials d'OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Estat OAuth: connectat ({0}).",
        "Settings exported to:{0}{1}" => "Configuració exportada a:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "No es pot exportar la configuració.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "La importació d'un fitxer de configuració substituirà la vostra configuració local actual. Continuar?",
        "Unable to read the selected file.{0}{0}{1}" => "No es pot llegir el fitxer seleccionat.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "El fitxer seleccionat no conté configuracions JSON vàlides.",
        "Settings imported from:{0}{1}" => "Configuració importada de:{0}{1}",
        _ => english
    };
}



