namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslatePt(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Exportação Evernote",
        "Settings" => "Configurações",
        "Save" => "Salvar",
        "Cancel" => "Cancelar",
        "App:" => "Aplicativo:",
        "Refresh" => "Atualizar",
        "Log out" => "Sair",
        "Switch to" => "Mudar para",
        "Exit" => "Saída",
        "{0} is still running" => "{0} ainda está em execução",
        "Use the tray icon to reopen or exit." => "Use o ícone da bandeja para reabrir ou sair.",
        "Ignore" => "Ignorar",
        "Ignore {0}" => "Ignorar {0}",
        "Unignore {0}" => "Designorar {0}",
        "Set export file for {0}..." => "Definir arquivo de exportação para {0}...",
        "Clear export file name" => "Limpar nome do arquivo de exportação",
        "Clear export file ({0})" => "Limpar arquivo de exportação ({0})",
        "stack" => "pilha",
        "notebook" => "caderno",
        "Select the Evernote root folder, then export the checked notebooks." => "Selecione a pasta raiz do Evernote e exporte os cadernos verificados.",
        "Evernote Folder..." => "Pasta Evernote...",
        "Reload" => "Recarregar",
        "Export" => "Exportar",
        "Evernote polling frequency (minutes):" => "Frequência de pesquisa do Evernote (minutos):",
        "Pause automatic polling" => "Pausar a votação automática",
        "Lock: (none)" => "Bloqueio: (nenhum)",
        "Force" => "Vigor",
        "State poll: every 6s, next in --s" => "Enquete estadual: a cada 6s, próximo em --s",
        "Keep last X markdown exports:" => "Mantenha as últimas exportações de descontos X:",
        "Older files in ./markdown will be deleted automatically after each export." => "Arquivos mais antigos em ./markdown serão excluídos automaticamente após cada exportação.",
        "No Evernote folder selected." => "Nenhuma pasta do Evernote selecionada.",
        "Show ignored" => "Mostrar ignorado",
        "Right-click: ignore or set export file name." => "Clique com o botão direito: ignore ou defina o nome do arquivo de exportação.",
        "Choose the root folder of the Evernote installation" => "Escolha a pasta raiz da instalação do Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "Banco de dados detectado: {0} | Pilhas: {1} | Cadernos: {2}",
        "DB error: {0}" => "Erro de banco de dados: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Não é possível ler o banco de dados Evernote.{0}{0}{1}",
        " [ignored]" => "[ignorado]",
        " | updated: {0}" => "| atualizado: {0}",
        " | export: {0}.md" => "| exportar: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} (cadernos {1}){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} (notas {1}){2}{3}{4}",
        "(none)" => "(nenhum)",
        "Lock: {0}" => "Bloqueio: {0}",
        "awaiting confirmation from {0}" => "aguardando confirmação de {0}",
        "State poll: every {0}s, next in {1}s" => "Enquete estadual: a cada {0}s, próximo em {1}s",
        "Export File Name" => "Nome do arquivo de exportação",
        "Export file name for {0} (without .md):" => "Nome do arquivo de exportação para {0} (sem .md):",
        "The same name lets you group multiple stacks/notebooks." => "O mesmo nome permite agrupar várias pilhas/cadernos.",
        "Invalid name. Use at least one valid character." => "Nome inválido. Use pelo menos um caractere válido.",
        "Language" => "Linguagem",
        "Choose the UI language" => "Escolha o idioma da IU",
        "System default" => "Padrão do sistema",
        "Close button behavior:" => "Comportamento do botão Fechar:",
        "Minimize to tray" => "Minimizar para a bandeja",
        "Close app" => "Fechar aplicativo",
        "Controls what happens when you click the window close button." => "Controla o que acontece quando você clica no botão Fechar janela.",
        "Enable debug logs" => "Habilitar logs de depuração",
        "Local config file: {0}" => "Arquivo de configuração local: {0}",
        "Google Drive config sync" => "Sincronização de configuração do Google Drive",
        "Enable Google Drive sync" => "Ative a sincronização do Google Drive",
        "Auto-restore at startup" => "Restauração automática na inicialização",
        "Click the button below to connect with Google OAuth." => "Clique no botão abaixo para se conectar ao Google OAuth.",
        "Connect with Google" => "Conecte-se com o Google",
        "OAuth status: configured." => "Status do OAuth: configurado.",
        "OAuth status: not connected." => "Status do OAuth: não conectado.",
        "OAuth status: connecting..." => "Status do OAuth: conectando...",
        "Unknown OAuth error." => "Erro OAuth desconhecido.",
        "OAuth status: failed ({0})" => "Status do OAuth: falhou ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Falha na conexão OAuth.{0}{0}{1}",
        "Google Drive OAuth" => "OAuth do Google Drive",
        "Google account connected" => "Conta do Google conectada",
        "(not detected)" => "(não detectado)",
        "OAuth client source: {0}" => "Fonte do cliente OAuth: {0}",
        "Drive file ID (optional):" => "ID do arquivo do Drive (opcional):",
        "Export settings" => "Exportar configurações",
        "Import settings" => "Importar configurações",
        "Select Google OAuth credentials JSON" => "Selecione as credenciais JSON do Google OAuth",
        "OAuth status: credentials file required." => "Status do OAuth: arquivo de credenciais necessário.",
        "OAuth status: error ({0})" => "Status do OAuth: erro ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Não foi possível ler as credenciais do OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Status do OAuth: conectado ({0}).",
        "Settings exported to:{0}{1}" => "Configurações exportadas para:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Não foi possível exportar as configurações.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "A importação de um arquivo de configurações substituirá sua configuração local atual. Continuar?",
        "Unable to read the selected file.{0}{0}{1}" => "Não foi possível ler o arquivo selecionado.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "O arquivo selecionado não contém configurações JSON válidas.",
        "Settings imported from:{0}{1}" => "Configurações importadas de:{0}{1}",
        _ => english
    };
}



