namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateFr(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Exportation Evernote",
        "Settings" => "Paramètres",
        "Save" => "Sauvegarder",
        "Cancel" => "Annuler",
        "App:" => "Application :",
        "Refresh" => "Rafraîchir",
        "Log out" => "Se déconnecter",
        "Switch to" => "Passer à",
        "Exit" => "Sortie",
        "{0} is still running" => "{0} est toujours en cours d'exécution",
        "Use the tray icon to reopen or exit." => "Utilisez l'icône de la barre d'état pour rouvrir ou quitter.",
        "Ignore" => "Ignorer",
        "Ignore {0}" => "Ignorer {0}",
        "Unignore {0}" => "Ne plus ignorer {0}",
        "Set export file for {0}..." => "Définir le fichier d'exportation pour {0}...",
        "Clear export file name" => "Effacer le nom du fichier d'exportation",
        "Clear export file ({0})" => "Effacer le fichier d'exportation ({0})",
        "stack" => "empiler",
        "notebook" => "carnet de notes",
        "Select the Evernote root folder, then export the checked notebooks." => "Sélectionnez le dossier racine Evernote, puis exportez les blocs-notes cochés.",
        "Evernote Folder..." => "Dossier Evernote...",
        "Reload" => "Recharger",
        "Export" => "Exporter",
        "Evernote polling frequency (minutes):" => "Fréquence d'interrogation Evernote (minutes) :",
        "Pause automatic polling" => "Suspendre l'interrogation automatique",
        "Lock: (none)" => "Verrouillage : (aucun)",
        "Force" => "Forcer",
        "State poll: every 6s, next in --s" => "Sondage d'État : toutes les 6 s, le prochain dans --s",
        "Keep last X markdown exports:" => "Conserver les X dernières exportations de démarque :",
        "Older files in ./markdown will be deleted automatically after each export." => "Les fichiers plus anciens dans ./markdown seront automatiquement supprimés après chaque exportation.",
        "No Evernote folder selected." => "Aucun dossier Evernote sélectionné.",
        "Show ignored" => "Afficher ignoré",
        "Right-click: ignore or set export file name." => "Clic droit : ignorer ou définir le nom du fichier d'exportation.",
        "Choose the root folder of the Evernote installation" => "Choisissez le dossier racine de l'installation d'Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "Base de données détectée : {0} | Piles : {1} | Cahiers : {2}",
        "DB error: {0}" => "Erreur de base de données : {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Impossible de lire la base de données Evernote.{0}{0}{1}",
        " [ignored]" => "[ignoré]",
        " | updated: {0}" => "| mis à jour : {0}",
        " | export: {0}.md" => "| exporter : {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} (cahiers {1}){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} remarques){2}{3}{4}",
        "(none)" => "(aucun)",
        "Lock: {0}" => "Verrou : {0}",
        "awaiting confirmation from {0}" => "en attente de confirmation de {0}",
        "State poll: every {0}s, next in {1}s" => "Sondage d'État : tous les {0}s, le prochain dans {1}s",
        "Export File Name" => "Nom du fichier d'exportation",
        "Export file name for {0} (without .md):" => "Nom du fichier d'exportation pour {0} (sans .md) :",
        "The same name lets you group multiple stacks/notebooks." => "Le même nom vous permet de regrouper plusieurs piles/carnets.",
        "Invalid name. Use at least one valid character." => "Nom invalide. Utilisez au moins un caractère valide.",
        "Language" => "Langue",
        "Choose the UI language" => "Choisissez la langue de l'interface utilisateur",
        "System default" => "Valeur par défaut du système",
        "Close button behavior:" => "Comportement du bouton de fermeture :",
        "Minimize to tray" => "Réduire dans le bac",
        "Close app" => "Fermer l'application",
        "Controls what happens when you click the window close button." => "Contrôle ce qui se passe lorsque vous cliquez sur le bouton de fermeture de la fenêtre.",
        "Enable debug logs" => "Activer les journaux de débogage",
        "Local config file: {0}" => "Fichier de configuration local : {0}",
        "Google Drive config sync" => "Synchronisation de la configuration de Google Drive",
        "Enable Google Drive sync" => "Activer la synchronisation Google Drive",
        "Auto-restore at startup" => "Restauration automatique au démarrage",
        "Click the button below to connect with Google OAuth." => "Cliquez sur le bouton ci-dessous pour vous connecter à Google OAuth.",
        "Connect with Google" => "Connectez-vous avec Google",
        "OAuth status: configured." => "Statut OAuth : configuré.",
        "OAuth status: not connected." => "Statut OAuth : non connecté.",
        "OAuth status: connecting..." => "Statut OAuth : connexion...",
        "Unknown OAuth error." => "Erreur OAuth inconnue.",
        "OAuth status: failed ({0})" => "Statut OAuth : échec ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Échec de la connexion OAuth.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Compte Google connecté",
        "(not detected)" => "(non détecté)",
        "OAuth client source: {0}" => "Source du client OAuth : {0}",
        "Drive file ID (optional):" => "ID du fichier Drive (facultatif) :",
        "Export settings" => "Paramètres d'exportation",
        "Import settings" => "Paramètres d'importation",
        "Select Google OAuth credentials JSON" => "Sélectionnez les identifiants Google OAuth JSON",
        "OAuth status: credentials file required." => "Statut OAuth : fichier d'informations d'identification requis.",
        "OAuth status: error ({0})" => "État OAuth : erreur ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Impossible de lire les informations d'identification OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Statut OAuth : connecté ({0}).",
        "Settings exported to:{0}{1}" => "Paramètres exportés vers :{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Impossible d'exporter les paramètres.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "L'importation d'un fichier de paramètres remplacera votre configuration locale actuelle. Continuer?",
        "Unable to read the selected file.{0}{0}{1}" => "Impossible de lire le fichier sélectionné.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Le fichier sélectionné ne contient pas de paramètres JSON valides.",
        "Settings imported from:{0}{1}" => "Paramètres importés de :{0}{1}",
        _ => english
    };
}



