namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateCs(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Disk Google",
        "Evernote Export" => "Evernote Export",
        "Settings" => "Nastavení",
        "Save" => "Uložit",
        "Cancel" => "Zrušit",
        "App:" => "Aplikace:",
        "Refresh" => "Obnovit",
        "Log out" => "Odhlaste se",
        "Switch to" => "Switch to",
        "Exit" => "Výstup",
        "{0} is still running" => "{0} stále běží",
        "Use the tray icon to reopen or exit." => "Pro opětovné otevření nebo ukončení použijte ikonu na hlavním panelu.",
        "Ignore" => "Ignorovat",
        "Ignore {0}" => "Ignorovat {0}",
        "Unignore {0}" => "Přestat ignorovat {0}",
        "Set export file for {0}..." => "Nastavit soubor exportu pro {0}...",
        "Clear export file name" => "Vymazat název exportovaného souboru",
        "Clear export file ({0})" => "Vymazat exportovaný soubor ({0})",
        "stack" => "stoh",
        "notebook" => "notebook",
        "Select the Evernote root folder, then export the checked notebooks." => "Vyberte kořenovou složku Evernote a exportujte zaškrtnuté poznámkové bloky.",
        "Evernote Folder..." => "Složka Evernote...",
        "Reload" => "Znovu načíst",
        "Export" => "Vývozní",
        "Evernote polling frequency (minutes):" => "Frekvence dotazování Evernote (minuty):",
        "Pause automatic polling" => "Pozastavit automatické dotazování",
        "Lock: (none)" => "Zámek: (žádný)",
        "Force" => "Platnost",
        "State poll: every 6s, next in --s" => "Státní průzkum: každých 6 s, další za --s",
        "Keep last X markdown exports:" => "Zachovat exporty posledních X markdown:",
        "Older files in ./markdown will be deleted automatically after each export." => "Starší soubory v ./markdown budou po každém exportu automaticky smazány.",
        "No Evernote folder selected." => "Není vybrána žádná složka Evernote.",
        "Show ignored" => "Show ignorována",
        "Right-click: ignore or set export file name." => "Klepněte pravým tlačítkem myši: ignorujte nebo nastavte název exportovaného souboru.",
        "Choose the root folder of the Evernote installation" => "Vyberte kořenovou složku instalace Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "Zjištěno DB: {0} | Zásobníky: {1} | Notebooky: {2}",
        "DB error: {0}" => "Chyba DB: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Nelze číst databázi Evernote.{0}{0}{1}",
        " [ignored]" => "[ignorováno]",
        " | updated: {0}" => "| aktualizováno: {0}",
        " | export: {0}.md" => "| export: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} notebooky){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} poznámky){2}{3}{4}",
        "(none)" => "(žádný)",
        "Lock: {0}" => "Zámek: {0}",
        "awaiting confirmation from {0}" => "čeká na potvrzení od {0}",
        "State poll: every {0}s, next in {1}s" => "Průzkum stavu: každých {0}s, další za {1}s",
        "Export File Name" => "Název exportovaného souboru",
        "Export file name for {0} (without .md):" => "Exportovat název souboru pro {0} (bez .md):",
        "The same name lets you group multiple stacks/notebooks." => "Stejný název umožňuje seskupovat více zásobníků/notebooků.",
        "Invalid name. Use at least one valid character." => "Neplatné jméno. Použijte alespoň jeden platný znak.",
        "Language" => "Jazyk",
        "Choose the UI language" => "Vyberte jazyk uživatelského rozhraní",
        "System default" => "Výchozí nastavení systému",
        "Close button behavior:" => "Chování tlačítka Zavřít:",
        "Minimize to tray" => "Minimalizovat do zásobníku",
        "Close app" => "Zavřete aplikaci",
        "Controls what happens when you click the window close button." => "Řídí, co se stane, když kliknete na tlačítko pro zavření okna.",
        "Enable debug logs" => "Povolit protokoly ladění",
        "Local config file: {0}" => "Místní konfigurační soubor: {0}",
        "Google Drive config sync" => "Synchronizace konfigurace Disku Google",
        "Enable Google Drive sync" => "Povolit synchronizaci Disku Google",
        "Auto-restore at startup" => "Automatické obnovení při spuštění",
        "Click the button below to connect with Google OAuth." => "Kliknutím na tlačítko níže se připojíte ke službě Google OAuth.",
        "Connect with Google" => "Spojte se s Googlem",
        "OAuth status: configured." => "Stav OAuth: nakonfigurováno.",
        "OAuth status: not connected." => "Stav OAuth: nepřipojeno.",
        "OAuth status: connecting..." => "Stav OAuth: připojování...",
        "Unknown OAuth error." => "Neznámá chyba OAuth.",
        "OAuth status: failed ({0})" => "Stav OAuth: neúspěšný ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Připojení OAuth se nezdařilo.{0}{0}{1}",
        "Google Drive OAuth" => "OAuth Disku Google",
        "Google account connected" => "Účet Google je připojen",
        "(not detected)" => "(nezjištěno)",
        "OAuth client source: {0}" => "Zdroj klienta OAuth: {0}",
        "Drive file ID (optional):" => "ID souboru na Disku (volitelné):",
        "Export settings" => "Export nastavení",
        "Import settings" => "Importovat nastavení",
        "Select Google OAuth credentials JSON" => "Vyberte JSON přihlašovací údaje Google OAuth",
        "OAuth status: credentials file required." => "Stav OAuth: je vyžadován soubor přihlašovacích údajů.",
        "OAuth status: error ({0})" => "Stav OAuth: chyba ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Nelze přečíst přihlašovací údaje OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Stav OAuth: připojeno ({0}).",
        "Settings exported to:{0}{1}" => "Nastavení exportováno do:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Nastavení nelze exportovat.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Import souboru nastavení nahradí vaši aktuální místní konfiguraci. Pokračovat?",
        "Unable to read the selected file.{0}{0}{1}" => "Vybraný soubor nelze přečíst.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Vybraný soubor neobsahuje platná nastavení JSON.",
        "Settings imported from:{0}{1}" => "Nastavení importováno z:{0}{1}",
        _ => english
    };
}



