namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateSv(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Evernote Export",
        "Settings" => "Inställningar",
        "Save" => "Spara",
        "Cancel" => "Avboka",
        "App:" => "App:",
        "Refresh" => "Uppdatera",
        "Log out" => "Logga ut",
        "Switch to" => "Byt till",
        "Exit" => "Utgång",
        "{0} is still running" => "{0} körs fortfarande",
        "Use the tray icon to reopen or exit." => "Använd ikonen för att öppna eller avsluta igen.",
        "Ignore" => "Ignorera",
        "Ignore {0}" => "Ignorera {0}",
        "Unignore {0}" => "Ignorera {0}",
        "Set export file for {0}..." => "Ställ in exportfil för {0}...",
        "Clear export file name" => "Rensa exportfilnamn",
        "Clear export file ({0})" => "Rensa exportfil ({0})",
        "stack" => "stack",
        "notebook" => "anteckningsbok",
        "Select the Evernote root folder, then export the checked notebooks." => "Välj Evernotes rotmapp och exportera sedan de markerade anteckningsböckerna.",
        "Evernote Folder..." => "Evernote-mapp...",
        "Reload" => "Ladda om",
        "Export" => "Exportera",
        "Evernote polling frequency (minutes):" => "Evernote polling frekvens (minuter):",
        "Pause automatic polling" => "Pausa automatisk polling",
        "Lock: (none)" => "Lås: (inget)",
        "Force" => "Tvinga",
        "State poll: every 6s, next in --s" => "Statlig undersökning: var 6:e, nästa i --s",
        "Keep last X markdown exports:" => "Behåll de senaste X markdown-exporterna:",
        "Older files in ./markdown will be deleted automatically after each export." => "Äldre filer i ./markdown kommer att raderas automatiskt efter varje export.",
        "No Evernote folder selected." => "Ingen Evernote-mapp har valts.",
        "Show ignored" => "Visa ignorerad",
        "Right-click: ignore or set export file name." => "Högerklicka: ignorera eller ange exportfilnamn.",
        "Choose the root folder of the Evernote installation" => "Välj rotmappen för Evernote-installationen",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB upptäckt: {0} | Stackar: {1} | Anteckningsböcker: {2}",
        "DB error: {0}" => "DB-fel: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Det går inte att läsa Evernote-databasen.{0}{0}{1}",
        " [ignored]" => "[ignorerade]",
        " | updated: {0}" => "| uppdaterad: {0}",
        " | export: {0}.md" => "| exportera: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} anteckningsböcker){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} anteckningar){2}{3}{4}",
        "(none)" => "(ingen)",
        "Lock: {0}" => "Lås: {0}",
        "awaiting confirmation from {0}" => "väntar på bekräftelse från {0}",
        "State poll: every {0}s, next in {1}s" => "Tillståndsundersökning: varje {0}s, nästa om {1}s",
        "Export File Name" => "Exportera filnamn",
        "Export file name for {0} (without .md):" => "Exportera filnamn för {0} (utan .md):",
        "The same name lets you group multiple stacks/notebooks." => "Med samma namn kan du gruppera flera stackar/anteckningsböcker.",
        "Invalid name. Use at least one valid character." => "Ogiltigt namn. Använd minst ett giltigt tecken.",
        "Language" => "Språk",
        "Choose the UI language" => "Välj UI-språk",
        "System default" => "Systemstandard",
        "Close button behavior:" => "Stängningsknappens beteende:",
        "Minimize to tray" => "Minimera till bricka",
        "Close app" => "Stäng appen",
        "Controls what happens when you click the window close button." => "Styr vad som händer när du klickar på stängningsknappen för fönstret.",
        "Enable debug logs" => "Aktivera felsökningsloggar",
        "Local config file: {0}" => "Lokal konfigurationsfil: {0}",
        "Google Drive config sync" => "Google Drive konfigurationssynkronisering",
        "Enable Google Drive sync" => "Aktivera Google Drive-synkronisering",
        "Auto-restore at startup" => "Återställ automatiskt vid start",
        "Click the button below to connect with Google OAuth." => "Klicka på knappen nedan för att ansluta till Google OAuth.",
        "Connect with Google" => "Anslut till Google",
        "OAuth status: configured." => "OAuth-status: konfigurerad.",
        "OAuth status: not connected." => "OAuth-status: inte ansluten.",
        "OAuth status: connecting..." => "OAuth-status: ansluter...",
        "Unknown OAuth error." => "Okänt OAuth-fel.",
        "OAuth status: failed ({0})" => "OAuth-status: misslyckades ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth-anslutningen misslyckades.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Google-konto anslutet",
        "(not detected)" => "(inte upptäckt)",
        "OAuth client source: {0}" => "OAuth-klientkälla: {0}",
        "Drive file ID (optional):" => "Drive fil-id (valfritt):",
        "Export settings" => "Exportera inställningar",
        "Import settings" => "Importera inställningar",
        "Select Google OAuth credentials JSON" => "Välj Google OAuth-uppgifter JSON",
        "OAuth status: credentials file required." => "OAuth-status: autentiseringsfil krävs.",
        "OAuth status: error ({0})" => "OAuth-status: fel ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Det gick inte att läsa OAuth-uppgifter.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth-status: ansluten ({0}).",
        "Settings exported to:{0}{1}" => "Inställningar exporterade till:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Det gick inte att exportera inställningar.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Att importera en inställningsfil kommer att ersätta din nuvarande lokala konfiguration. Fortsätta?",
        "Unable to read the selected file.{0}{0}{1}" => "Det gick inte att läsa den valda filen.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Den valda filen innehåller inte giltiga JSON-inställningar.",
        "Settings imported from:{0}{1}" => "Inställningar importerade från:{0}{1}",
        _ => english
    };
}



