namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateFa(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "گوگل درایو",
        "Evernote Export" => "Evernote Export",
        "Settings" => "تنظیمات",
        "Save" => "ذخیره کنید",
        "Cancel" => "لغو کنید",
        "App:" => "برنامه:",
        "Refresh" => "تازه کردن",
        "Log out" => "از سیستم خارج شوید",
        "Switch to" => "تغییر به",
        "Exit" => "خارج شوید",
        "{0} is still running" => "{0} هنوز در حال اجرا است",
        "Use the tray icon to reopen or exit." => "از نماد سینی برای باز کردن مجدد یا خروج استفاده کنید.",
        "Ignore" => "نادیده گرفتن",
        "Ignore {0}" => "نادیده گرفتن {0}",
        "Unignore {0}" => "نادیده گرفتن {0}",
        "Set export file for {0}..." => "تنظیم فایل صادراتی برای {0}...",
        "Clear export file name" => "نام فایل صادراتی را پاک کنید",
        "Clear export file ({0})" => "پاک کردن فایل صادراتی ({0})",
        "stack" => "پشته",
        "notebook" => "دفترچه یادداشت",
        "Select the Evernote root folder, then export the checked notebooks." => "پوشه ریشه Evernote را انتخاب کنید، سپس نوت بوک های علامت گذاری شده را صادر کنید.",
        "Evernote Folder..." => "پوشه Evernote...",
        "Reload" => "بارگذاری مجدد",
        "Export" => "صادرات",
        "Evernote polling frequency (minutes):" => "فرکانس نظرسنجی Evernote (دقیقه):",
        "Pause automatic polling" => "توقف نظرسنجی خودکار",
        "Lock: (none)" => "قفل: (هیچ)",
        "Force" => "زور",
        "State poll: every 6s, next in --s" => "نظرسنجی ایالتی: هر 6 ثانیه، بعدی در -- ثانیه",
        "Keep last X markdown exports:" => "آخرین صادرات X نشانه گذاری را حفظ کنید:",
        "Older files in ./markdown will be deleted automatically after each export." => "فایل‌های قدیمی‌تر در ./markdown پس از هر بار صادرات به‌طور خودکار حذف می‌شوند.",
        "No Evernote folder selected." => "پوشه Evernote انتخاب نشده است.",
        "Show ignored" => "نمایش نادیده گرفته شده است",
        "Right-click: ignore or set export file name." => "راست کلیک کنید: نادیده گرفتن یا تنظیم نام فایل صادراتی.",
        "Choose the root folder of the Evernote installation" => "پوشه ریشه نصب Evernote را انتخاب کنید",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB شناسایی شد: {0} | پشته: {1} | نوت بوک: {2}",
        "DB error: {0}" => "خطای DB: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "نمی‌توان پایگاه داده Evernote را خواند.{0}{0}{1}",
        " [ignored]" => "[بی توجهی شد]",
        " | updated: {0}" => "| به روز شده: {0}",
        " | export: {0}.md" => "| صادرات: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} نوت بوک){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} یادداشت){2}{3}{4}",
        "(none)" => "(هیچ کدام)",
        "Lock: {0}" => "قفل: {0}",
        "awaiting confirmation from {0}" => "در انتظار تایید از {0}",
        "State poll: every {0}s, next in {1}s" => "نظرسنجی ایالتی: هر {0}s، بعدی در {1}s",
        "Export File Name" => "صادرات نام فایل",
        "Export file name for {0} (without .md):" => "صادر کردن نام فایل برای {0} (بدون md.):",
        "The same name lets you group multiple stacks/notebooks." => "همین نام به شما امکان می دهد چندین پشته / نوت بوک را گروه بندی کنید.",
        "Invalid name. Use at least one valid character." => "نام نامعتبر حداقل از یک کاراکتر معتبر استفاده کنید.",
        "Language" => "زبان",
        "Choose the UI language" => "زبان UI را انتخاب کنید",
        "System default" => "پیش فرض سیستم",
        "Close button behavior:" => "رفتار دکمه بستن:",
        "Minimize to tray" => "سینی را به حداقل برسانید",
        "Close app" => "برنامه را ببندید",
        "Controls what happens when you click the window close button." => "وقتی روی دکمه بستن پنجره کلیک می‌کنید چه اتفاقی می‌افتد را کنترل می‌کند.",
        "Enable debug logs" => "گزارش های اشکال زدایی را فعال کنید",
        "Local config file: {0}" => "فایل پیکربندی محلی: {0}",
        "Google Drive config sync" => "همگام سازی پیکربندی Google Drive",
        "Enable Google Drive sync" => "همگام سازی Google Drive را فعال کنید",
        "Auto-restore at startup" => "بازیابی خودکار هنگام راه اندازی",
        "Click the button below to connect with Google OAuth." => "برای اتصال به Google OAuth روی دکمه زیر کلیک کنید.",
        "Connect with Google" => "با گوگل ارتباط برقرار کنید",
        "OAuth status: configured." => "وضعیت OAuth: پیکربندی شده است.",
        "OAuth status: not connected." => "وضعیت OAuth: متصل نیست.",
        "OAuth status: connecting..." => "وضعیت OAuth: در حال اتصال...",
        "Unknown OAuth error." => "خطای OAuth ناشناخته.",
        "OAuth status: failed ({0})" => "وضعیت OAuth: ناموفق ({0})",
        "OAuth connection failed.{0}{0}{1}" => "اتصال OAuth ناموفق بود.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "حساب Google متصل شد",
        "(not detected)" => "(تشخیص داده نشد)",
        "OAuth client source: {0}" => "منبع مشتری OAuth: {0}",
        "Drive file ID (optional):" => "شناسه فایل Drive (اختیاری):",
        "Export settings" => "تنظیمات صادرات",
        "Import settings" => "تنظیمات وارد کنید",
        "Select Google OAuth credentials JSON" => "Google OAuth credentials JSON را انتخاب کنید",
        "OAuth status: credentials file required." => "وضعیت OAuth: فایل اعتبارنامه مورد نیاز است.",
        "OAuth status: error ({0})" => "وضعیت OAuth: خطا ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "خواندن اطلاعات کاربری OAuth ممکن نیست.{0}{0}{1}",
        "OAuth status: connected ({0})." => "وضعیت OAuth: متصل ({0}).",
        "Settings exported to:{0}{1}" => "تنظیمات صادر شده به:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "امکان صادر کردن تنظیمات وجود ندارد.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "وارد کردن یک فایل تنظیمات جایگزین پیکربندی محلی فعلی شما خواهد شد. ادامه دهید؟",
        "Unable to read the selected file.{0}{0}{1}" => "خواندن فایل انتخابی ممکن نیست.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "فایل انتخابی دارای تنظیمات معتبر JSON نیست.",
        "Settings imported from:{0}{1}" => "تنظیمات وارد شده از:{0}{1}",
        _ => english
    };
}



