namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateFi(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Evernote Export",
        "Settings" => "Asetukset",
        "Save" => "Tallentaa",
        "Cancel" => "Peruuttaa",
        "App:" => "Sovellus:",
        "Refresh" => "Päivitä",
        "Log out" => "Kirjaudu ulos",
        "Switch to" => "Vaihda kohteeseen",
        "Exit" => "Poistu",
        "{0} is still running" => "{0} on edelleen käynnissä",
        "Use the tray icon to reopen or exit." => "Avaa tai poistu uudelleen käyttämällä lokerokuvaketta.",
        "Ignore" => "Sivuuttaa",
        "Ignore {0}" => "Ohita {0}",
        "Unignore {0}" => "Kumoa huomioimatta {0}",
        "Set export file for {0}..." => "Aseta vientitiedosto kohteelle {0}...",
        "Clear export file name" => "Tyhjennä vientitiedoston nimi",
        "Clear export file ({0})" => "Tyhjennä vientitiedosto ({0})",
        "stack" => "pino",
        "notebook" => "muistikirja",
        "Select the Evernote root folder, then export the checked notebooks." => "Valitse Evernoten juurikansio ja vie sitten valitut muistikirjat.",
        "Evernote Folder..." => "Evernote-kansio...",
        "Reload" => "Lataa uudelleen",
        "Export" => "Viedä",
        "Evernote polling frequency (minutes):" => "Evernote äänestystaajuus (minuutteina):",
        "Pause automatic polling" => "Keskeytä automaattinen kysely",
        "Lock: (none)" => "Lukko: (ei mitään)",
        "Force" => "Pakottaa",
        "State poll: every 6s, next in --s" => "Osavaltiokysely: 6s välein, seuraavaksi --s",
        "Keep last X markdown exports:" => "Säilytä viimeiset X-vientit:",
        "Older files in ./markdown will be deleted automatically after each export." => "Vanhemmat tiedostot kohteessa ./markdown poistetaan automaattisesti jokaisen viennin jälkeen.",
        "No Evernote folder selected." => "Evernote-kansiota ei ole valittu.",
        "Show ignored" => "Show ohitettu",
        "Right-click: ignore or set export file name." => "Napsauta hiiren kakkospainikkeella: ohita tai aseta vientitiedoston nimi.",
        "Choose the root folder of the Evernote installation" => "Valitse Evernote-asennuksen juurikansio",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "Tietokanta havaittu: {0} | Pinot: {1} | Muistikirjat: {2}",
        "DB error: {0}" => "DB-virhe: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Evernote-tietokantaa ei voi lukea.{0}{0}{1}",
        " [ignored]" => "[jätetty huomioimatta]",
        " | updated: {0}" => "| päivitetty: {0}",
        " | export: {0}.md" => "| vienti: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} muistikirjat){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} muistiinpanoja){2}{3}{4}",
        "(none)" => "(ei mitään)",
        "Lock: {0}" => "Lukko: {0}",
        "awaiting confirmation from {0}" => "odottaa vahvistusta {0}",
        "State poll: every {0}s, next in {1}s" => "Osavaltiokysely: joka {0}s, seuraava {1}s kuluttua",
        "Export File Name" => "Vie tiedoston nimi",
        "Export file name for {0} (without .md):" => "Vie tiedostonimi kohteelle {0} (ilman .md:tä):",
        "The same name lets you group multiple stacks/notebooks." => "Saman nimen avulla voit ryhmitellä useita pinoja/muistikirjoja.",
        "Invalid name. Use at least one valid character." => "Virheellinen nimi. Käytä vähintään yhtä kelvollista merkkiä.",
        "Language" => "Kieli",
        "Choose the UI language" => "Valitse käyttöliittymän kieli",
        "System default" => "Järjestelmän oletus",
        "Close button behavior:" => "Sulje-painikkeen toiminta:",
        "Minimize to tray" => "Pienennä lokeroon",
        "Close app" => "Sulje sovellus",
        "Controls what happens when you click the window close button." => "Ohjaa, mitä tapahtuu, kun napsautat ikkunan sulkemispainiketta.",
        "Enable debug logs" => "Ota virheenkorjauslokit käyttöön",
        "Local config file: {0}" => "Paikallinen asetustiedosto: {0}",
        "Google Drive config sync" => "Google Drive -määritysten synkronointi",
        "Enable Google Drive sync" => "Ota Google Drive -synkronointi käyttöön",
        "Auto-restore at startup" => "Automaattinen palautus käynnistyksen yhteydessä",
        "Click the button below to connect with Google OAuth." => "Napsauta alla olevaa painiketta muodostaaksesi yhteyden Google OAuthiin.",
        "Connect with Google" => "Ota yhteyttä Googleen",
        "OAuth status: configured." => "OAuth-tila: määritetty.",
        "OAuth status: not connected." => "OAuth-tila: ei yhdistetty.",
        "OAuth status: connecting..." => "OAuth-tila: yhdistetään...",
        "Unknown OAuth error." => "Tuntematon OAuth-virhe.",
        "OAuth status: failed ({0})" => "OAuth-tila: epäonnistui ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth-yhteys epäonnistui.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Google-tili yhdistetty",
        "(not detected)" => "(ei havaittu)",
        "OAuth client source: {0}" => "OAuth-asiakaslähde: {0}",
        "Drive file ID (optional):" => "Drive-tiedostotunnus (valinnainen):",
        "Export settings" => "Vie asetukset",
        "Import settings" => "Tuo asetukset",
        "Select Google OAuth credentials JSON" => "Valitse Google OAuth -kirjautumistietojen JSON",
        "OAuth status: credentials file required." => "OAuth-tila: vaaditaan tunnistetiedosto.",
        "OAuth status: error ({0})" => "OAuth-tila: virhe ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "OAuth-kirjautumistietoja ei voi lukea.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth-tila: yhdistetty ({0}).",
        "Settings exported to:{0}{1}" => "Asetukset viety kohteeseen:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Asetuksia ei voi viedä.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Asetustiedoston tuominen korvaa nykyisen paikallisen kokoonpanosi. Jatkaa?",
        "Unable to read the selected file.{0}{0}{1}" => "Valittua tiedostoa ei voi lukea.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Valittu tiedosto ei sisällä kelvollisia JSON-asetuksia.",
        "Settings imported from:{0}{1}" => "Asetukset tuotu osoitteesta:{0}{1}",
        _ => english
    };
}



