namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateDe(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Evernote-Export",
        "Settings" => "Einstellungen",
        "Save" => "Speichern",
        "Cancel" => "Stornieren",
        "App:" => "App:",
        "Refresh" => "Aktualisieren",
        "Log out" => "Abmelden",
        "Switch to" => "Wechseln Sie zu",
        "Exit" => "Ausfahrt",
        "{0} is still running" => "{0} läuft noch",
        "Use the tray icon to reopen or exit." => "Verwenden Sie das Taskleistensymbol, um es erneut zu öffnen oder zu beenden.",
        "Ignore" => "Ignorieren",
        "Ignore {0}" => "{0} ignorieren",
        "Unignore {0}" => "{0} nicht mehr ignorieren",
        "Set export file for {0}..." => "Exportdatei für {0} festlegen...",
        "Clear export file name" => "Löschen Sie den Namen der Exportdatei",
        "Clear export file ({0})" => "Exportdatei löschen ({0})",
        "stack" => "Stapel",
        "notebook" => "Notizbuch",
        "Select the Evernote root folder, then export the checked notebooks." => "Wählen Sie den Evernote-Stammordner aus und exportieren Sie dann die überprüften Notizbücher.",
        "Evernote Folder..." => "Evernote-Ordner...",
        "Reload" => "Neu laden",
        "Export" => "Export",
        "Evernote polling frequency (minutes):" => "Häufigkeit der Evernote-Abfragen (Minuten):",
        "Pause automatic polling" => "Automatische Abfrage anhalten",
        "Lock: (none)" => "Sperre: (keine)",
        "Force" => "Gewalt",
        "State poll: every 6s, next in --s" => "Landesumfrage: alle 6 Sekunden, nächste in --s",
        "Keep last X markdown exports:" => "Letzte X Markdown-Exporte beibehalten:",
        "Older files in ./markdown will be deleted automatically after each export." => "Ältere Dateien in ./markdown werden nach jedem Export automatisch gelöscht.",
        "No Evernote folder selected." => "Kein Evernote-Ordner ausgewählt.",
        "Show ignored" => "Show ignoriert",
        "Right-click: ignore or set export file name." => "Rechtsklick: Exportdateinamen ignorieren oder festlegen.",
        "Choose the root folder of the Evernote installation" => "Wählen Sie den Stammordner der Evernote-Installation",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB erkannt: {0} | Stapel: {1} | Notizbücher: {2}",
        "DB error: {0}" => "DB-Fehler: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Evernote-Datenbank kann nicht gelesen werden.{0}{0}{1}",
        " [ignored]" => "[ignoriert]",
        " | updated: {0}" => "| aktualisiert: {0}",
        " | export: {0}.md" => "| Export: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} Notizbücher){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} Notizen){2}{3}{4}",
        "(none)" => "(keiner)",
        "Lock: {0}" => "Sperre: {0}",
        "awaiting confirmation from {0}" => "Warte auf Bestätigung von {0}",
        "State poll: every {0}s, next in {1}s" => "Landesumfrage: alle {0}s, nächste in {1}s",
        "Export File Name" => "Dateiname exportieren",
        "Export file name for {0} (without .md):" => "Exportdateiname für {0} (ohne .md):",
        "The same name lets you group multiple stacks/notebooks." => "Mit demselben Namen können Sie mehrere Stapel/Notizbücher gruppieren.",
        "Invalid name. Use at least one valid character." => "Ungültiger Name. Verwenden Sie mindestens ein gültiges Zeichen.",
        "Language" => "Sprache",
        "Choose the UI language" => "Wählen Sie die UI-Sprache",
        "System default" => "Systemstandard",
        "Close button behavior:" => "Verhalten der Schaltfläche „Schließen“:",
        "Minimize to tray" => "Auf das Fach minimieren",
        "Close app" => "App schließen",
        "Controls what happens when you click the window close button." => "Steuert, was passiert, wenn Sie auf die Schaltfläche zum Schließen des Fensters klicken.",
        "Enable debug logs" => "Aktivieren Sie Debug-Protokolle",
        "Local config file: {0}" => "Lokale Konfigurationsdatei: {0}",
        "Google Drive config sync" => "Synchronisierung der Google Drive-Konfiguration",
        "Enable Google Drive sync" => "Aktivieren Sie die Google Drive-Synchronisierung",
        "Auto-restore at startup" => "Automatische Wiederherstellung beim Start",
        "Click the button below to connect with Google OAuth." => "Klicken Sie auf die Schaltfläche unten, um eine Verbindung mit Google OAuth herzustellen.",
        "Connect with Google" => "Verbinden Sie sich mit Google",
        "OAuth status: configured." => "OAuth-Status: konfiguriert.",
        "OAuth status: not connected." => "OAuth-Status: nicht verbunden.",
        "OAuth status: connecting..." => "OAuth-Status: Verbindung wird hergestellt...",
        "Unknown OAuth error." => "Unbekannter OAuth-Fehler.",
        "OAuth status: failed ({0})" => "OAuth-Status: fehlgeschlagen ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth-Verbindung fehlgeschlagen.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Google-Konto verbunden",
        "(not detected)" => "(nicht erkannt)",
        "OAuth client source: {0}" => "OAuth-Client-Quelle: {0}",
        "Drive file ID (optional):" => "Laufwerksdatei-ID (optional):",
        "Export settings" => "Einstellungen exportieren",
        "Import settings" => "Einstellungen importieren",
        "Select Google OAuth credentials JSON" => "Wählen Sie Google OAuth-Anmeldeinformationen JSON aus",
        "OAuth status: credentials file required." => "OAuth-Status: Anmeldeinformationsdatei erforderlich.",
        "OAuth status: error ({0})" => "OAuth-Status: Fehler ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "OAuth-Anmeldeinformationen können nicht gelesen werden.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth-Status: verbunden ({0}).",
        "Settings exported to:{0}{1}" => "Einstellungen exportiert nach:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Einstellungen können nicht exportiert werden.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Durch das Importieren einer Einstellungsdatei wird Ihre aktuelle lokale Konfiguration ersetzt. Weitermachen?",
        "Unable to read the selected file.{0}{0}{1}" => "Die ausgewählte Datei kann nicht gelesen werden.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Die ausgewählte Datei enthält keine gültigen JSON-Einstellungen.",
        "Settings imported from:{0}{1}" => "Einstellungen importiert von:{0}{1}",
        _ => english
    };
}



