namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateEl(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Evernote Export",
        "Settings" => "Ρυθμίσεις",
        "Save" => "Εκτός",
        "Cancel" => "Ματαίωση",
        "App:" => "Εφαρμογή:",
        "Refresh" => "Φρεσκάρω",
        "Log out" => "Αποσυνδεθείτε",
        "Switch to" => "Εναλλαγή σε",
        "Exit" => "Εξοδος",
        "{0} is still running" => "Το {0} εξακολουθεί να εκτελείται",
        "Use the tray icon to reopen or exit." => "Χρησιμοποιήστε το εικονίδιο του δίσκου για να ανοίξετε ξανά ή να βγείτε.",
        "Ignore" => "Αγνοώ",
        "Ignore {0}" => "Αγνοήστε {0}",
        "Unignore {0}" => "Παράβλεψη {0}",
        "Set export file for {0}..." => "Ορισμός αρχείου εξαγωγής για {0}...",
        "Clear export file name" => "Διαγραφή ονόματος αρχείου εξαγωγής",
        "Clear export file ({0})" => "Εκκαθάριση αρχείου εξαγωγής ({0})",
        "stack" => "σωρός",
        "notebook" => "σημειωματάριο",
        "Select the Evernote root folder, then export the checked notebooks." => "Επιλέξτε τον ριζικό φάκελο Evernote και, στη συνέχεια, εξαγάγετε τα επιλεγμένα σημειωματάρια.",
        "Evernote Folder..." => "Φάκελος Evernote...",
        "Reload" => "Γεμίζω πάλι",
        "Export" => "Εξαγωγή",
        "Evernote polling frequency (minutes):" => "Συχνότητα δημοσκοπήσεων Evernote (λεπτά):",
        "Pause automatic polling" => "Παύση αυτόματης ψηφοφορίας",
        "Lock: (none)" => "Κλείδωμα: (κανένα)",
        "Force" => "Δύναμη",
        "State poll: every 6s, next in --s" => "Δημοσκόπηση: κάθε 6 δευτερόλεπτα, επόμενο σε --δ",
        "Keep last X markdown exports:" => "Διατήρηση των τελευταίων εξαγωγών X markdown:",
        "Older files in ./markdown will be deleted automatically after each export." => "Τα παλαιότερα αρχεία στο ./markdown θα διαγράφονται αυτόματα μετά από κάθε εξαγωγή.",
        "No Evernote folder selected." => "Δεν έχει επιλεγεί φάκελος Evernote.",
        "Show ignored" => "Εμφάνιση αγνοήθηκε",
        "Right-click: ignore or set export file name." => "Κάντε δεξί κλικ: αγνοήστε ή ορίστε το όνομα αρχείου εξαγωγής.",
        "Choose the root folder of the Evernote installation" => "Επιλέξτε τον ριζικό φάκελο της εγκατάστασης του Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "Εντοπίστηκε DB: {0} | Στοίβες: {1} | Σημειωματάρια: {2}",
        "DB error: {0}" => "Σφάλμα DB: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Δεν είναι δυνατή η ανάγνωση της βάσης δεδομένων Evernote.{0}{0}{1}",
        " [ignored]" => "[αγνοήθηκε]",
        " | updated: {0}" => "| ενημερώθηκε: {0}",
        " | export: {0}.md" => "| εξαγωγή: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} σημειωματάρια){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} σημειώσεις){2}{3}{4}",
        "(none)" => "(κανένας)",
        "Lock: {0}" => "Κλείδωμα: {0}",
        "awaiting confirmation from {0}" => "σε αναμονή επιβεβαίωσης από {0}",
        "State poll: every {0}s, next in {1}s" => "Δημοσκόπηση: κάθε {0}s, επόμενη σε {1}s",
        "Export File Name" => "Εξαγωγή ονόματος αρχείου",
        "Export file name for {0} (without .md):" => "Εξαγωγή ονόματος αρχείου για {0} (χωρίς .md):",
        "The same name lets you group multiple stacks/notebooks." => "Το ίδιο όνομα σάς επιτρέπει να ομαδοποιήσετε πολλές στοίβες/σημειωματάρια.",
        "Invalid name. Use at least one valid character." => "Μη έγκυρο όνομα. Χρησιμοποιήστε τουλάχιστον έναν έγκυρο χαρακτήρα.",
        "Language" => "Γλώσσα",
        "Choose the UI language" => "Επιλέξτε τη γλώσσα διεπαφής χρήστη",
        "System default" => "Προεπιλογή συστήματος",
        "Close button behavior:" => "Συμπεριφορά κουμπιού κλεισίματος:",
        "Minimize to tray" => "Ελαχιστοποιήστε στο δίσκο",
        "Close app" => "Κλείσιμο εφαρμογής",
        "Controls what happens when you click the window close button." => "Ελέγχει τι συμβαίνει όταν κάνετε κλικ στο κουμπί κλεισίματος παραθύρου.",
        "Enable debug logs" => "Ενεργοποίηση αρχείων καταγραφής εντοπισμού σφαλμάτων",
        "Local config file: {0}" => "Τοπικό αρχείο διαμόρφωσης: {0}",
        "Google Drive config sync" => "Συγχρονισμός διαμόρφωσης Google Drive",
        "Enable Google Drive sync" => "Ενεργοποίηση συγχρονισμού Google Drive",
        "Auto-restore at startup" => "Αυτόματη επαναφορά κατά την εκκίνηση",
        "Click the button below to connect with Google OAuth." => "Κάντε κλικ στο κουμπί παρακάτω για να συνδεθείτε με το Google OAuth.",
        "Connect with Google" => "Συνδεθείτε με την Google",
        "OAuth status: configured." => "Κατάσταση OAuth: διαμορφώθηκε.",
        "OAuth status: not connected." => "Κατάσταση OAuth: δεν είναι συνδεδεμένο.",
        "OAuth status: connecting..." => "Κατάσταση OAuth: σύνδεση...",
        "Unknown OAuth error." => "Άγνωστο σφάλμα OAuth.",
        "OAuth status: failed ({0})" => "Κατάσταση OAuth: απέτυχε ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Η σύνδεση OAuth απέτυχε.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Συνδέθηκε ο λογαριασμός Google",
        "(not detected)" => "(δεν εντοπίστηκε)",
        "OAuth client source: {0}" => "Πηγή πελάτη OAuth: {0}",
        "Drive file ID (optional):" => "Αναγνωριστικό αρχείου Drive (προαιρετικό):",
        "Export settings" => "Εξαγωγή ρυθμίσεων",
        "Import settings" => "Ρυθμίσεις εισαγωγής",
        "Select Google OAuth credentials JSON" => "Επιλέξτε διαπιστευτήρια Google OAuth JSON",
        "OAuth status: credentials file required." => "Κατάσταση OAuth: απαιτείται αρχείο διαπιστευτηρίων.",
        "OAuth status: error ({0})" => "Κατάσταση OAuth: σφάλμα ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Δεν είναι δυνατή η ανάγνωση των διαπιστευτηρίων OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Κατάσταση OAuth: συνδεδεμένο ({0}).",
        "Settings exported to:{0}{1}" => "Οι ρυθμίσεις εξάγονται σε:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Δεν είναι δυνατή η εξαγωγή ρυθμίσεων.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Η εισαγωγή ενός αρχείου ρυθμίσεων θα αντικαταστήσει την τρέχουσα τοπική σας διαμόρφωση. Συνεχίζω;",
        "Unable to read the selected file.{0}{0}{1}" => "Δεν είναι δυνατή η ανάγνωση του επιλεγμένου αρχείου.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Το επιλεγμένο αρχείο δεν περιέχει έγκυρες ρυθμίσεις JSON.",
        "Settings imported from:{0}{1}" => "Ρυθμίσεις που εισάγονται από:{0}{1}",
        _ => english
    };
}



