namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateEs(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Exportación de Evernote",
        "Settings" => "Ajustes",
        "Save" => "Ahorrar",
        "Cancel" => "Cancelar",
        "App:" => "Aplicación:",
        "Refresh" => "Refrescar",
        "Log out" => "Finalizar la sesión",
        "Switch to" => "Cambiar a",
        "Exit" => "Salida",
        "{0} is still running" => "{0} todavía está funcionando",
        "Use the tray icon to reopen or exit." => "Utilice el icono de la bandeja para volver a abrir o salir.",
        "Ignore" => "Ignorar",
        "Ignore {0}" => "Ignorar {0}",
        "Unignore {0}" => "Dejar de ignorar {0}",
        "Set export file for {0}..." => "Establecer archivo de exportación para {0}...",
        "Clear export file name" => "Borrar nombre del archivo de exportación",
        "Clear export file ({0})" => "Borrar archivo de exportación ({0})",
        "stack" => "pila",
        "notebook" => "computadora portátil",
        "Select the Evernote root folder, then export the checked notebooks." => "Seleccione la carpeta raíz de Evernote y luego exporte los cuadernos marcados.",
        "Evernote Folder..." => "Carpeta de Evernote...",
        "Reload" => "Recargar",
        "Export" => "Exportar",
        "Evernote polling frequency (minutes):" => "Frecuencia de encuestas de Evernote (minutos):",
        "Pause automatic polling" => "Pausar el sondeo automático",
        "Lock: (none)" => "Bloqueo: (ninguno)",
        "Force" => "Fuerza",
        "State poll: every 6s, next in --s" => "Encuesta estatal: cada 6 segundos, la siguiente en --s",
        "Keep last X markdown exports:" => "Mantener las últimas X exportaciones de rebajas:",
        "Older files in ./markdown will be deleted automatically after each export." => "Los archivos más antiguos en ./markdown se eliminarán automáticamente después de cada exportación.",
        "No Evernote folder selected." => "No se seleccionó ninguna carpeta de Evernote.",
        "Show ignored" => "Mostrar ignorado",
        "Right-click: ignore or set export file name." => "Haga clic derecho: ignore o establezca el nombre del archivo de exportación.",
        "Choose the root folder of the Evernote installation" => "Elija la carpeta raíz de la instalación de Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "BD detectada: {0} | Pilas: {1} | Cuadernos: {2}",
        "DB error: {0}" => "Error de base de datos: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "No se puede leer la base de datos de Evernote.{0}{0}{1}",
        " [ignored]" => "[ignorado]",
        " | updated: {0}" => "| actualizado: {0}",
        " | export: {0}.md" => "| exportar: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} cuadernos){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} notas){2}{3}{4}",
        "(none)" => "(ninguno)",
        "Lock: {0}" => "Bloqueo: {0}",
        "awaiting confirmation from {0}" => "esperando confirmación de {0}",
        "State poll: every {0}s, next in {1}s" => "Encuesta estatal: cada {0}s, la siguiente en {1}s",
        "Export File Name" => "Exportar nombre de archivo",
        "Export file name for {0} (without .md):" => "Nombre del archivo de exportación para {0} (sin .md):",
        "The same name lets you group multiple stacks/notebooks." => "El mismo nombre le permite agrupar varias pilas/cuadernos.",
        "Invalid name. Use at least one valid character." => "Nombre no válido. Utilice al menos un carácter válido.",
        "Language" => "Idioma",
        "Choose the UI language" => "Elija el idioma de la interfaz de usuario",
        "System default" => "Valor predeterminado del sistema",
        "Close button behavior:" => "Comportamiento del botón Cerrar:",
        "Minimize to tray" => "Minimizar a bandeja",
        "Close app" => "Cerrar aplicación",
        "Controls what happens when you click the window close button." => "Controla lo que sucede cuando haces clic en el botón de cerrar ventana.",
        "Enable debug logs" => "Habilitar registros de depuración",
        "Local config file: {0}" => "Archivo de configuración local: {0}",
        "Google Drive config sync" => "Sincronización de configuración de Google Drive",
        "Enable Google Drive sync" => "Habilitar la sincronización de Google Drive",
        "Auto-restore at startup" => "Restauración automática al inicio",
        "Click the button below to connect with Google OAuth." => "Haga clic en el botón a continuación para conectarse con Google OAuth.",
        "Connect with Google" => "Conéctate con Google",
        "OAuth status: configured." => "Estado de OAuth: configurado.",
        "OAuth status: not connected." => "Estado de OAuth: no conectado.",
        "OAuth status: connecting..." => "Estado de OAuth: conectando...",
        "Unknown OAuth error." => "Error de OAuth desconocido.",
        "OAuth status: failed ({0})" => "Estado de OAuth: fallido ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Error en la conexión OAuth.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Cuenta de Google conectada",
        "(not detected)" => "(no detectado)",
        "OAuth client source: {0}" => "Fuente del cliente OAuth: {0}",
        "Drive file ID (optional):" => "ID de archivo de unidad (opcional):",
        "Export settings" => "Exportar configuración",
        "Import settings" => "Importar configuración",
        "Select Google OAuth credentials JSON" => "Seleccione las credenciales JSON de Google OAuth",
        "OAuth status: credentials file required." => "Estado de OAuth: se requiere archivo de credenciales.",
        "OAuth status: error ({0})" => "Estado de OAuth: error ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "No se pueden leer las credenciales de OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Estado de OAuth: conectado ({0}).",
        "Settings exported to:{0}{1}" => "Configuraciones exportadas a:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "No se puede exportar la configuración.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "La importación de un archivo de configuración reemplazará su configuración local actual. ¿Continuar?",
        "Unable to read the selected file.{0}{0}{1}" => "No se puede leer el archivo seleccionado.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "El archivo seleccionado no contiene configuraciones JSON válidas.",
        "Settings imported from:{0}{1}" => "Configuraciones importadas desde:{0}{1}",
        _ => english
    };
}



