namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateUk(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Диск Google",
        "Evernote Export" => "Експорт Evernote",
        "Settings" => "Налаштування",
        "Save" => "зберегти",
        "Cancel" => "Скасувати",
        "App:" => "додаток:",
        "Refresh" => "Оновити",
        "Log out" => "Вийти",
        "Switch to" => "Перейти на",
        "Exit" => "Вихід",
        "{0} is still running" => "{0} все ще працює",
        "Use the tray icon to reopen or exit." => "Щоб повторно відкрити або вийти, скористайтеся піктограмою на панелі задач.",
        "Ignore" => "Ігнорувати",
        "Ignore {0}" => "Ігнорувати {0}",
        "Unignore {0}" => "Скасувати ігнорування {0}",
        "Set export file for {0}..." => "Установити файл експорту для {0}...",
        "Clear export file name" => "Очистити назву файлу експорту",
        "Clear export file ({0})" => "Очистити файл експорту ({0})",
        "stack" => "стек",
        "notebook" => "блокнот",
        "Select the Evernote root folder, then export the checked notebooks." => "Виберіть кореневу папку Evernote, а потім експортуйте відмічені блокноти.",
        "Evernote Folder..." => "Папка Evernote...",
        "Reload" => "Перезавантажити",
        "Export" => "Експорт",
        "Evernote polling frequency (minutes):" => "Частота опитування Evernote (у хвилинах):",
        "Pause automatic polling" => "Призупинити автоматичне опитування",
        "Lock: (none)" => "Блокування: (немає)",
        "Force" => "Сила",
        "State poll: every 6s, next in --s" => "Опитування штату: кожні 6 с, наступне через --с",
        "Keep last X markdown exports:" => "Зберігати експорт останніх X уцінок:",
        "Older files in ./markdown will be deleted automatically after each export." => "Старіші файли в ./markdown видалятимуться автоматично після кожного експорту.",
        "No Evernote folder selected." => "Папка Evernote не вибрана.",
        "Show ignored" => "Показати проігноровано",
        "Right-click: ignore or set export file name." => "Клацніть правою кнопкою миші: ігноруйте або встановіть назву файлу експорту.",
        "Choose the root folder of the Evernote installation" => "Виберіть кореневу папку встановлення Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "Виявлено БД: {0} | Стеки: {1} | Блокноти: {2}",
        "DB error: {0}" => "Помилка БД: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Не вдається прочитати базу даних Evernote.{0}{0}{1}",
        " [ignored]" => "[ігнорується]",
        " | updated: {0}" => "| оновлено: {0}",
        " | export: {0}.md" => "| експорт: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} зошитів){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} примітки){2}{3}{4}",
        "(none)" => "(жоден)",
        "Lock: {0}" => "Блокування: {0}",
        "awaiting confirmation from {0}" => "очікується підтвердження від {0}",
        "State poll: every {0}s, next in {1}s" => "Опитування штату: кожні {0} с, наступне через {1} с",
        "Export File Name" => "Ім'я файлу експорту",
        "Export file name for {0} (without .md):" => "Ім’я файлу експорту для {0} (без .md):",
        "The same name lets you group multiple stacks/notebooks." => "Таке ж ім’я дозволяє групувати кілька стосів/блокнотів.",
        "Invalid name. Use at least one valid character." => "Недійсне ім'я. Використовуйте принаймні один дійсний символ.",
        "Language" => "Мова",
        "Choose the UI language" => "Виберіть мову інтерфейсу",
        "System default" => "Система за умовчанням",
        "Close button behavior:" => "Поведінка кнопки «Закрити»:",
        "Minimize to tray" => "Згорнути в трей",
        "Close app" => "Закрити додаток",
        "Controls what happens when you click the window close button." => "Керує тим, що відбувається, коли ви натискаєте кнопку закриття вікна.",
        "Enable debug logs" => "Увімкнути журнали налагодження",
        "Local config file: {0}" => "Локальний конфігураційний файл: {0}",
        "Google Drive config sync" => "Синхронізація конфігурації Google Drive",
        "Enable Google Drive sync" => "Увімкніть синхронізацію Google Drive",
        "Auto-restore at startup" => "Автоматичне відновлення при запуску",
        "Click the button below to connect with Google OAuth." => "Натисніть кнопку нижче, щоб підключитися до Google OAuth.",
        "Connect with Google" => "Підключіться до Google",
        "OAuth status: configured." => "Статус OAuth: налаштовано.",
        "OAuth status: not connected." => "Статус OAuth: не підключено.",
        "OAuth status: connecting..." => "Статус OAuth: підключення...",
        "Unknown OAuth error." => "Невідома помилка OAuth.",
        "OAuth status: failed ({0})" => "Статус OAuth: помилка ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Помилка підключення OAuth.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Обліковий запис Google підключено",
        "(not detected)" => "(не виявлено)",
        "OAuth client source: {0}" => "Джерело клієнта OAuth: {0}",
        "Drive file ID (optional):" => "Ідентифікатор файлу на Диску (необов’язково):",
        "Export settings" => "Експорт налаштувань",
        "Import settings" => "Імпорт налаштувань",
        "Select Google OAuth credentials JSON" => "Виберіть облікові дані Google OAuth JSON",
        "OAuth status: credentials file required." => "Статус OAuth: потрібен файл облікових даних.",
        "OAuth status: error ({0})" => "Статус OAuth: помилка ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Не вдалося прочитати облікові дані OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Статус OAuth: підключено ({0}).",
        "Settings exported to:{0}{1}" => "Налаштування експортовано до: {0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Не вдалося експортувати налаштування.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Імпорт файлу налаштувань замінить поточну локальну конфігурацію. Продовжити?",
        "Unable to read the selected file.{0}{0}{1}" => "Неможливо прочитати вибраний файл.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Вибраний файл не містить дійсних налаштувань JSON.",
        "Settings imported from:{0}{1}" => "Налаштування імпортовано з: {0}{1}",
        _ => english
    };
}



