namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateSq(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Evernote Export",
        "Settings" => "Cilësimet",
        "Save" => "Ruaj",
        "Cancel" => "Anulo",
        "App:" => "Aplikacioni:",
        "Refresh" => "Rifresko",
        "Log out" => "Dilni",
        "Switch to" => "Kalo te",
        "Exit" => "Dilni",
        "{0} is still running" => "{0} është ende në punë",
        "Use the tray icon to reopen or exit." => "Përdorni ikonën e tabakasë për të rihapur ose për të dalë.",
        "Ignore" => "Injoro",
        "Ignore {0}" => "Injoro {0}",
        "Unignore {0}" => "Anulo {0}",
        "Set export file for {0}..." => "Cakto skedarin e eksportit për {0}...",
        "Clear export file name" => "Pastro emrin e skedarit të eksportit",
        "Clear export file ({0})" => "Pastro skedarin e eksportit ({0})",
        "stack" => "pirg",
        "notebook" => "fletore",
        "Select the Evernote root folder, then export the checked notebooks." => "Zgjidhni dosjen rrënjë Evernote, më pas eksportoni fletoret e kontrolluara.",
        "Evernote Folder..." => "Dosja Evernote...",
        "Reload" => "Ringarko",
        "Export" => "Eksporti",
        "Evernote polling frequency (minutes):" => "Frekuenca e votimit të Evernote (minuta):",
        "Pause automatic polling" => "Ndalo votimin automatik",
        "Lock: (none)" => "Kyçja: (asnjë)",
        "Force" => "Forca",
        "State poll: every 6s, next in --s" => "Sondazhi i shtetit: çdo 6 sekonda, më pas në --s",
        "Keep last X markdown exports:" => "Mbani eksportet e fundit të shënjimit X:",
        "Older files in ./markdown will be deleted automatically after each export." => "Skedarët e vjetër në ./markdown do të fshihen automatikisht pas çdo eksportimi.",
        "No Evernote folder selected." => "Asnjë dosje Evernote nuk është zgjedhur.",
        "Show ignored" => "Shfaq të shpërfillur",
        "Right-click: ignore or set export file name." => "Klikoni me të djathtën: injoroni ose vendosni emrin e skedarit të eksportit.",
        "Choose the root folder of the Evernote installation" => "Zgjidhni dosjen kryesore të instalimit të Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB e zbuluar: {0} | Rafte: {1} | Fletoret: {2}",
        "DB error: {0}" => "Gabim DB: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Nuk mund të lexohet baza e të dhënave Evernote.{0}{0}{1}",
        " [ignored]" => "[injoruar]",
        " | updated: {0}" => "| përditësuar: {0}",
        " | export: {0}.md" => "| eksport: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} fletore){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} shënime){2}{3}{4}",
        "(none)" => "(asnjë)",
        "Lock: {0}" => "Bllokimi: {0}",
        "awaiting confirmation from {0}" => "në pritje të konfirmimit nga {0}",
        "State poll: every {0}s, next in {1}s" => "Sondazhi shtetëror: çdo {0}s, pas {1}s",
        "Export File Name" => "Eksporto emrin e skedarit",
        "Export file name for {0} (without .md):" => "Eksporto emrin e skedarit për {0} (pa .md):",
        "The same name lets you group multiple stacks/notebooks." => "I njëjti emër ju lejon të gruponi pirgje/fletore të shumta.",
        "Invalid name. Use at least one valid character." => "Emër i pavlefshëm. Përdorni të paktën një karakter të vlefshëm.",
        "Language" => "Gjuha",
        "Choose the UI language" => "Zgjidhni gjuhën e UI",
        "System default" => "Parazgjedhja e sistemit",
        "Close button behavior:" => "Sjellja e butonit të mbylljes:",
        "Minimize to tray" => "Minimizojeni në tabaka",
        "Close app" => "Mbyll aplikacionin",
        "Controls what happens when you click the window close button." => "Kontrollon se çfarë ndodh kur klikoni butonin e mbylljes së dritares.",
        "Enable debug logs" => "Aktivizo regjistrat e korrigjimit",
        "Local config file: {0}" => "Skedari lokal i konfigurimit: {0}",
        "Google Drive config sync" => "Sinkronizimi i konfigurimit të Google Drive",
        "Enable Google Drive sync" => "Aktivizo sinkronizimin e Google Drive",
        "Auto-restore at startup" => "Rivendosja automatike në fillim",
        "Click the button below to connect with Google OAuth." => "Klikoni butonin më poshtë për t'u lidhur me Google OAuth.",
        "Connect with Google" => "Lidhu me Google",
        "OAuth status: configured." => "Statusi i OAuth: i konfiguruar.",
        "OAuth status: not connected." => "Statusi i OAuth: nuk është i lidhur.",
        "OAuth status: connecting..." => "Statusi i OAuth: po lidhet...",
        "Unknown OAuth error." => "Gabim i panjohur OAuth.",
        "OAuth status: failed ({0})" => "Statusi i OAuth: i dështuar ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Lidhja OAuth dështoi.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Llogaria e Google u lidh",
        "(not detected)" => "(nuk u zbulua)",
        "OAuth client source: {0}" => "Burimi i klientit OAuth: {0}",
        "Drive file ID (optional):" => "ID-ja e skedarit të diskut (opsionale):",
        "Export settings" => "Cilësimet e eksportit",
        "Import settings" => "Cilësimet e importit",
        "Select Google OAuth credentials JSON" => "Zgjidh kredencialet e Google OAuth JSON",
        "OAuth status: credentials file required." => "Statusi i OAuth: kërkohet skedari i kredencialeve.",
        "OAuth status: error ({0})" => "Statusi i OAuth: gabim ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Nuk mund të lexohen kredencialet e OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Statusi i OAuth: i lidhur ({0}).",
        "Settings exported to:{0}{1}" => "Cilësimet u eksportuan në:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Cilësimet nuk mund të eksportohen.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Importimi i një skedari cilësimesh do të zëvendësojë konfigurimin tuaj aktual lokal. Të vazhdohet?",
        "Unable to read the selected file.{0}{0}{1}" => "Skedari i zgjedhur nuk mund të lexohet.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Skedari i zgjedhur nuk përmban cilësime të vlefshme JSON.",
        "Settings imported from:{0}{1}" => "Cilësimet e importuara nga:{0}{1}",
        _ => english
    };
}



