namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateEu(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Evernote esportazioa",
        "Settings" => "Ezarpenak",
        "Save" => "Gorde",
        "Cancel" => "Utzi",
        "App:" => "Aplikazioa:",
        "Refresh" => "Freskatu",
        "Log out" => "Amaitu saioa",
        "Switch to" => "Aldatu hona",
        "Exit" => "Irten",
        "{0} is still running" => "{0} martxan dago oraindik",
        "Use the tray icon to reopen or exit." => "Erabili erretiluaren ikonoa berriro irekitzeko edo irteteko.",
        "Ignore" => "Ez ikusi",
        "Ignore {0}" => "Ez ikusi {0}",
        "Unignore {0}" => "Ez ikusi {0}",
        "Set export file for {0}..." => "Ezarri esportatzeko fitxategia {0}...",
        "Clear export file name" => "Garbitu esportazio-fitxategiaren izena",
        "Clear export file ({0})" => "Garbitu esportazio fitxategia ({0})",
        "stack" => "pilatu",
        "notebook" => "koadernoa",
        "Select the Evernote root folder, then export the checked notebooks." => "Hautatu Evernote erroko karpeta, eta esportatu egiaztatutako koadernoak.",
        "Evernote Folder..." => "Evernote karpeta...",
        "Reload" => "Berriz kargatu",
        "Export" => "Esportatu",
        "Evernote polling frequency (minutes):" => "Evernote-ren galdeketen maiztasuna (minutuak):",
        "Pause automatic polling" => "Pausatu galdeketa automatikoa",
        "Lock: (none)" => "Blokeoa: (bat ere ez)",
        "Force" => "Indarra",
        "State poll: every 6s, next in --s" => "Estatuko inkesta: 6s behin, hurrengo --s",
        "Keep last X markdown exports:" => "Mantendu azken X marken esportazioak:",
        "Older files in ./markdown will be deleted automatically after each export." => "./markdown-ko fitxategi zaharrak automatikoki ezabatuko dira esportazio bakoitzaren ondoren.",
        "No Evernote folder selected." => "Ez da hautatu Evernote karpetarik.",
        "Show ignored" => "Erakutsi jaramonik egin gabe",
        "Right-click: ignore or set export file name." => "Egin klik eskuineko botoiarekin: ez ikusi edo ezarri esportatzeko fitxategiaren izena.",
        "Choose the root folder of the Evernote installation" => "Aukeratu Evernote instalazioaren erro karpeta",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB detektatu da: {0} | Pilak: {1} | Koadernoak: {2}",
        "DB error: {0}" => "DB errorea: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Ezin da Evernote datu-basea irakurri.{0}{0}{1}",
        " [ignored]" => "[ez ikusi egin]",
        " | updated: {0}" => "| eguneratua: {0}",
        " | export: {0}.md" => "| esportatu: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} koadernoak){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} oharrak){2}{3}{4}",
        "(none)" => "(bat ere ez)",
        "Lock: {0}" => "Blokeoa: {0}",
        "awaiting confirmation from {0}" => "{0}-ren berrespenaren zain",
        "State poll: every {0}s, next in {1}s" => "Estatuko inkesta: {0}s behin, hurrengo {1}s",
        "Export File Name" => "Esportatu fitxategiaren izena",
        "Export file name for {0} (without .md):" => "Esportatu fitxategiaren izena {0} (.md gabe):",
        "The same name lets you group multiple stacks/notebooks." => "Izen berdinak hainbat pila/koaderno multzokatzeko aukera ematen du.",
        "Invalid name. Use at least one valid character." => "Izen baliogabea. Erabili baliozko karaktere bat gutxienez.",
        "Language" => "Hizkuntza",
        "Choose the UI language" => "Aukeratu UI hizkuntza",
        "System default" => "Sistema lehenetsia",
        "Close button behavior:" => "Itxi botoiaren portaera:",
        "Minimize to tray" => "Minimizatu erretilura",
        "Close app" => "Itxi aplikazioa",
        "Controls what happens when you click the window close button." => "Leihoa ixteko botoia sakatzean zer gertatzen den kontrolatzen du.",
        "Enable debug logs" => "Gaitu arazketa-erregistroak",
        "Local config file: {0}" => "Tokiko konfigurazio fitxategia: {0}",
        "Google Drive config sync" => "Google Drive konfigurazioaren sinkronizazioa",
        "Enable Google Drive sync" => "Gaitu Google Drive sinkronizazioa",
        "Auto-restore at startup" => "Berreskuratu automatikoki abiaraztean",
        "Click the button below to connect with Google OAuth." => "Egin klik beheko botoian Google OAuth-ekin konektatzeko.",
        "Connect with Google" => "Konektatu Google-rekin",
        "OAuth status: configured." => "OAuth egoera: konfiguratuta.",
        "OAuth status: not connected." => "OAuth egoera: ez dago konektatuta.",
        "OAuth status: connecting..." => "OAuth egoera: konektatzen...",
        "Unknown OAuth error." => "OAuth errore ezezaguna.",
        "OAuth status: failed ({0})" => "OAuth egoera: huts egin du ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth konexioak huts egin du.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Google kontua konektatuta",
        "(not detected)" => "(ez detektatu)",
        "OAuth client source: {0}" => "OAuth bezeroaren iturria: {0}",
        "Drive file ID (optional):" => "Drive fitxategiaren IDa (aukerakoa):",
        "Export settings" => "Esportatu ezarpenak",
        "Import settings" => "Inportatu ezarpenak",
        "Select Google OAuth credentials JSON" => "Hautatu Google OAuth kredentzialak JSON",
        "OAuth status: credentials file required." => "OAuth egoera: kredentzialen fitxategia behar da.",
        "OAuth status: error ({0})" => "OAuth egoera: errorea ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Ezin dira irakurri OAuth kredentzialak.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth egoera: konektatuta ({0}).",
        "Settings exported to:{0}{1}" => "Hona esportatu dira ezarpenak:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Ezin dira ezarpenak esportatu.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Ezarpen-fitxategi bat inportatzeak uneko tokiko konfigurazioa ordezkatuko du. Jarraitu nahi duzu?",
        "Unable to read the selected file.{0}{0}{1}" => "Ezin da hautatutako fitxategia irakurri.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Hautatutako fitxategiak ez du JSON baliozko ezarpenak.",
        "Settings imported from:{0}{1}" => "Hemendik inportatutako ezarpenak:{0}{1}",
        _ => english
    };
}



