namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateLv(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google disks",
        "Evernote Export" => "Evernote eksports",
        "Settings" => "Iestatījumi",
        "Save" => "Saglabāt",
        "Cancel" => "Atcelt",
        "App:" => "Lietotne:",
        "Refresh" => "Atsvaidzināt",
        "Log out" => "Atteikties",
        "Switch to" => "Pārslēgties uz",
        "Exit" => "Iziet",
        "{0} is still running" => "{0} joprojām darbojas",
        "Use the tray icon to reopen or exit." => "Izmantojiet teknes ikonu, lai atkārtoti atvērtu vai izietu.",
        "Ignore" => "Ignorēt",
        "Ignore {0}" => "Ignorēt {0}",
        "Unignore {0}" => "Atcelt ignorēšanu {0}",
        "Set export file for {0}..." => "Iestatīt eksporta failu {0}...",
        "Clear export file name" => "Notīrīt eksporta faila nosaukumu",
        "Clear export file ({0})" => "Notīrīt eksporta failu ({0})",
        "stack" => "kaudze",
        "notebook" => "piezīmju grāmatiņa",
        "Select the Evernote root folder, then export the checked notebooks." => "Atlasiet Evernote saknes mapi un pēc tam eksportējiet atzīmētās piezīmju grāmatiņas.",
        "Evernote Folder..." => "Evernote mape...",
        "Reload" => "Pārlādēt",
        "Export" => "Eksportēt",
        "Evernote polling frequency (minutes):" => "Evernote aptauju biežums (minūtēs):",
        "Pause automatic polling" => "Apturēt automātisko aptauju",
        "Lock: (none)" => "Slēdzene: (nav)",
        "Force" => "Spēks",
        "State poll: every 6s, next in --s" => "Štatu aptauja: ik pēc 6 sekundēm, nākamais pēc --s",
        "Keep last X markdown exports:" => "Saglabāt pēdējo X atzīmes eksportu:",
        "Older files in ./markdown will be deleted automatically after each export." => "Vecāki faili mapē ./markdown tiks automātiski dzēsti pēc katras eksportēšanas.",
        "No Evernote folder selected." => "Nav atlasīta neviena Evernote mape.",
        "Show ignored" => "Rādīt ignorēts",
        "Right-click: ignore or set export file name." => "Ar peles labo pogu noklikšķiniet: ignorējiet vai iestatiet eksporta faila nosaukumu.",
        "Choose the root folder of the Evernote installation" => "Izvēlieties Evernote instalācijas saknes mapi",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB konstatēts: {0} | Stacks: {1} | Piezīmju grāmatiņas: {2}",
        "DB error: {0}" => "DB kļūda: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Nevar nolasīt Evernote datu bāzi.{0}{0}{1}",
        " [ignored]" => "[ignorēts]",
        " | updated: {0}" => "| atjaunināts: {0}",
        " | export: {0}.md" => "| eksportēt: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} piezīmju grāmatiņas){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} piezīmes){2}{3}{4}",
        "(none)" => "(nav)",
        "Lock: {0}" => "Slēdzene: {0}",
        "awaiting confirmation from {0}" => "gaida apstiprinājumu no {0}",
        "State poll: every {0}s, next in {1}s" => "Štata aptauja: ik pēc {0}s, nākamā pēc {1}s",
        "Export File Name" => "Eksportēt faila nosaukumu",
        "Export file name for {0} (without .md):" => "Eksportēt faila nosaukumu {0} (bez .md):",
        "The same name lets you group multiple stacks/notebooks." => "Tas pats nosaukums ļauj grupēt vairākas kaudzītes/piezīmju grāmatiņas.",
        "Invalid name. Use at least one valid character." => "Nederīgs nosaukums. Izmantojiet vismaz vienu derīgu rakstzīmi.",
        "Language" => "Valoda",
        "Choose the UI language" => "Izvēlieties lietotāja interfeisa valodu",
        "System default" => "Sistēmas noklusējums",
        "Close button behavior:" => "Aizvērt pogas darbība:",
        "Minimize to tray" => "Samaziniet līdz paplātei",
        "Close app" => "Aizveriet lietotni",
        "Controls what happens when you click the window close button." => "Kontrolē, kas notiek, noklikšķinot uz loga aizvēršanas pogas.",
        "Enable debug logs" => "Iespējot atkļūdošanas žurnālus",
        "Local config file: {0}" => "Vietējais konfigurācijas fails: {0}",
        "Google Drive config sync" => "Google diska konfigurācijas sinhronizācija",
        "Enable Google Drive sync" => "Iespējot Google diska sinhronizāciju",
        "Auto-restore at startup" => "Automātiska atjaunošana startēšanas laikā",
        "Click the button below to connect with Google OAuth." => "Noklikšķiniet uz tālāk esošās pogas, lai izveidotu savienojumu ar Google OAuth.",
        "Connect with Google" => "Sazinieties ar Google",
        "OAuth status: configured." => "OAuth statuss: konfigurēts.",
        "OAuth status: not connected." => "OAuth statuss: nav savienots.",
        "OAuth status: connecting..." => "OAuth statuss: tiek izveidots savienojums...",
        "Unknown OAuth error." => "Nezināma OAuth kļūda.",
        "OAuth status: failed ({0})" => "OAuth statuss: neizdevās ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth savienojums neizdevās.{0}{0}{1}",
        "Google Drive OAuth" => "Google diska OAuth",
        "Google account connected" => "Google konts ir pievienots",
        "(not detected)" => "(nav atklāts)",
        "OAuth client source: {0}" => "OAuth klienta avots: {0}",
        "Drive file ID (optional):" => "Diska faila ID (neobligāti):",
        "Export settings" => "Eksportēt iestatījumus",
        "Import settings" => "Importēt iestatījumus",
        "Select Google OAuth credentials JSON" => "Atlasiet Google OAuth akreditācijas datu JSON",
        "OAuth status: credentials file required." => "OAuth statuss: nepieciešams akreditācijas datu fails.",
        "OAuth status: error ({0})" => "OAuth statuss: kļūda ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Nevar nolasīt OAuth akreditācijas datus.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth statuss: savienots ({0}).",
        "Settings exported to:{0}{1}" => "Iestatījumi eksportēti uz:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Nevar eksportēt iestatījumus.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Iestatījumu faila importēšana aizstās jūsu pašreizējo lokālo konfigurāciju. Vai turpināt?",
        "Unable to read the selected file.{0}{0}{1}" => "Nevar nolasīt atlasīto failu.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Atlasītajā failā nav derīgu iestatījumu JSON.",
        "Settings imported from:{0}{1}" => "Iestatījumi importēti no:{0}{1}",
        _ => english
    };
}



