namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslatePl(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Dysk Google",
        "Evernote Export" => "Eksport Evernote'a",
        "Settings" => "Ustawienia",
        "Save" => "Ratować",
        "Cancel" => "Anulować",
        "App:" => "Aplikacja:",
        "Refresh" => "Odświeżać",
        "Log out" => "Wyloguj się",
        "Switch to" => "Przełącz na",
        "Exit" => "Wyjście",
        "{0} is still running" => "{0} nadal działa",
        "Use the tray icon to reopen or exit." => "Użyj ikony na pasku zadań, aby ponownie otworzyć lub wyjść.",
        "Ignore" => "Ignorować",
        "Ignore {0}" => "Ignoruj ​​{0}",
        "Unignore {0}" => "Przestań ignorować {0}",
        "Set export file for {0}..." => "Ustaw plik eksportu dla {0}...",
        "Clear export file name" => "Wyczyść nazwę pliku eksportu",
        "Clear export file ({0})" => "Wyczyść plik eksportu ({0})",
        "stack" => "stos",
        "notebook" => "zeszyt",
        "Select the Evernote root folder, then export the checked notebooks." => "Wybierz folder główny Evernote, a następnie wyeksportuj zaznaczone notesy.",
        "Evernote Folder..." => "Folder Evernote'a...",
        "Reload" => "Przeładować",
        "Export" => "Eksport",
        "Evernote polling frequency (minutes):" => "Częstotliwość odpytywania Evernote (w minutach):",
        "Pause automatic polling" => "Wstrzymaj automatyczne odpytywanie",
        "Lock: (none)" => "Zamek: (brak)",
        "Force" => "Siła",
        "State poll: every 6s, next in --s" => "Sonda stanu: co 6 s, następna za --s",
        "Keep last X markdown exports:" => "Zachowaj ostatni eksport X przecen:",
        "Older files in ./markdown will be deleted automatically after each export." => "Starsze pliki w ./markdown będą automatycznie usuwane po każdym eksporcie.",
        "No Evernote folder selected." => "Nie wybrano folderu Evernote.",
        "Show ignored" => "Pokaż zignorowane",
        "Right-click: ignore or set export file name." => "Kliknięcie prawym przyciskiem myszy: zignorowanie lub ustawienie nazwy pliku eksportu.",
        "Choose the root folder of the Evernote installation" => "Wybierz folder główny instalacji Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "Wykryto bazę danych: {0} | Stosy: {1} | Notatniki: {2}",
        "DB error: {0}" => "Błąd bazy danych: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Nie można odczytać bazy danych Evernote.{0}{0}{1}",
        " [ignored]" => "[zignorowano]",
        " | updated: {0}" => "| zaktualizowano: {0}",
        " | export: {0}.md" => "| eksport: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} notesy){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} notatki){2}{3}{4}",
        "(none)" => "(nic)",
        "Lock: {0}" => "Blokada: {0}",
        "awaiting confirmation from {0}" => "oczekuje na potwierdzenie od {0}",
        "State poll: every {0}s, next in {1}s" => "Sondaż stanowy: co {0}s, następny za {1}s",
        "Export File Name" => "Eksportuj nazwę pliku",
        "Export file name for {0} (without .md):" => "Eksportuj nazwę pliku dla {0} (bez .md):",
        "The same name lets you group multiple stacks/notebooks." => "Ta sama nazwa umożliwia grupowanie wielu stosów/notatników.",
        "Invalid name. Use at least one valid character." => "Nieprawidłowa nazwa. Użyj co najmniej jednego prawidłowego znaku.",
        "Language" => "Język",
        "Choose the UI language" => "Wybierz język interfejsu",
        "System default" => "Domyślne systemowe",
        "Close button behavior:" => "Zachowanie przycisku Zamknij:",
        "Minimize to tray" => "Minimalizuj do zasobnika",
        "Close app" => "Zamknij aplikację",
        "Controls what happens when you click the window close button." => "Kontroluje, co się stanie po kliknięciu przycisku zamykania okna.",
        "Enable debug logs" => "Włącz dzienniki debugowania",
        "Local config file: {0}" => "Lokalny plik konfiguracyjny: {0}",
        "Google Drive config sync" => "Synchronizacja konfiguracji Dysku Google",
        "Enable Google Drive sync" => "Włącz synchronizację Dysku Google",
        "Auto-restore at startup" => "Automatyczne przywracanie przy uruchomieniu",
        "Click the button below to connect with Google OAuth." => "Kliknij poniższy przycisk, aby połączyć się z Google OAuth.",
        "Connect with Google" => "Połącz się z Google",
        "OAuth status: configured." => "Stan OAuth: skonfigurowany.",
        "OAuth status: not connected." => "Stan OAuth: brak połączenia.",
        "OAuth status: connecting..." => "Stan OAuth: łączenie...",
        "Unknown OAuth error." => "Nieznany błąd OAuth.",
        "OAuth status: failed ({0})" => "Stan OAuth: niepowodzenie ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Połączenie OAuth nie powiodło się.{0}{0}{1}",
        "Google Drive OAuth" => "OAuth Dysku Google",
        "Google account connected" => "Połączono konto Google",
        "(not detected)" => "(nie wykryto)",
        "OAuth client source: {0}" => "Źródło klienta OAuth: {0}",
        "Drive file ID (optional):" => "Identyfikator pliku na dysku (opcjonalnie):",
        "Export settings" => "Eksportuj ustawienia",
        "Import settings" => "Importuj ustawienia",
        "Select Google OAuth credentials JSON" => "Wybierz dane uwierzytelniające Google OAuth JSON",
        "OAuth status: credentials file required." => "Stan OAuth: wymagany plik danych uwierzytelniających.",
        "OAuth status: error ({0})" => "Stan OAuth: błąd ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Nie można odczytać danych uwierzytelniających OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Stan OAuth: połączony ({0}).",
        "Settings exported to:{0}{1}" => "Ustawienia wyeksportowane do:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Nie można wyeksportować ustawień.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Zaimportowanie pliku ustawień zastąpi bieżącą konfigurację lokalną. Kontynuować?",
        "Unable to read the selected file.{0}{0}{1}" => "Nie można odczytać wybranego pliku.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Wybrany plik nie zawiera prawidłowych ustawień JSON.",
        "Settings imported from:{0}{1}" => "Ustawienia zaimportowane z:{0}{1}",
        _ => english
    };
}



