namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateBg(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Диск",
        "Evernote Export" => "Експортиране на Evernote",
        "Settings" => "Настройки",
        "Save" => "Запазване",
        "Cancel" => "Отказ",
        "App:" => "Приложение:",
        "Refresh" => "Опресняване",
        "Log out" => "Излезте",
        "Switch to" => "Превключете към",
        "Exit" => "Изход",
        "{0} is still running" => "{0} все още работи",
        "Use the tray icon to reopen or exit." => "Използвайте иконата в областта, за да отворите отново или да излезете.",
        "Ignore" => "Игнорирайте",
        "Ignore {0}" => "Игнориране на {0}",
        "Unignore {0}" => "Премахване на пренебрегването на {0}",
        "Set export file for {0}..." => "Задаване на файл за експортиране за {0}...",
        "Clear export file name" => "Изчистете името на файла за експортиране",
        "Clear export file ({0})" => "Изчистване на файла за експортиране ({0})",
        "stack" => "стек",
        "notebook" => "бележник",
        "Select the Evernote root folder, then export the checked notebooks." => "Изберете главната папка на Evernote, след което експортирайте отметнатите бележници.",
        "Evernote Folder..." => "Папка Evernote...",
        "Reload" => "Презареди",
        "Export" => "Експортиране",
        "Evernote polling frequency (minutes):" => "Честота на анкети в Evernote (минути):",
        "Pause automatic polling" => "Поставяне на пауза на автоматичното анкетиране",
        "Lock: (none)" => "Заключване: (няма)",
        "Force" => "Сила",
        "State poll: every 6s, next in --s" => "Държавна анкета: на всеки 6s, следваща след --s",
        "Keep last X markdown exports:" => "Запазване на последните X маркдаун експортирания:",
        "Older files in ./markdown will be deleted automatically after each export." => "По-старите файлове в ./markdown ще бъдат изтривани автоматично след всяко експортиране.",
        "No Evernote folder selected." => "Няма избрана папка Evernote.",
        "Show ignored" => "Показване игнорирано",
        "Right-click: ignore or set export file name." => "Щракнете с десен бутон: игнорирайте или задайте име на файл за експортиране.",
        "Choose the root folder of the Evernote installation" => "Изберете основната папка на инсталацията на Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB открит: {0} | Стекове: {1} | Тетрадки: {2}",
        "DB error: {0}" => "Грешка в DB: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Не може да се прочете базата данни на Evernote.{0}{0}{1}",
        " [ignored]" => "[игнориран]",
        " | updated: {0}" => "| актуализиран: {0}",
        " | export: {0}.md" => "| експортиране: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} тетрадки){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} бележки){2}{3}{4}",
        "(none)" => "(няма)",
        "Lock: {0}" => "Заключване: {0}",
        "awaiting confirmation from {0}" => "очаква се потвърждение от {0}",
        "State poll: every {0}s, next in {1}s" => "Държавно гласуване: на всеки {0}s, следващо след {1}s",
        "Export File Name" => "Име на файл за експортиране",
        "Export file name for {0} (without .md):" => "Име на файл за експортиране за {0} (без .md):",
        "The same name lets you group multiple stacks/notebooks." => "Същото име ви позволява да групирате множество стекове/тетрадки.",
        "Invalid name. Use at least one valid character." => "Невалидно име. Използвайте поне един валиден знак.",
        "Language" => "език",
        "Choose the UI language" => "Изберете езика на потребителския интерфейс",
        "System default" => "Система по подразбиране",
        "Close button behavior:" => "Поведение на бутона за затваряне:",
        "Minimize to tray" => "Минимизиране в тава",
        "Close app" => "Затворете приложението",
        "Controls what happens when you click the window close button." => "Контролира какво се случва, когато щракнете върху бутона за затваряне на прозореца.",
        "Enable debug logs" => "Активиране на регистрационни файлове за отстраняване на грешки",
        "Local config file: {0}" => "Локален конфигурационен файл: {0}",
        "Google Drive config sync" => "Синхронизиране на конфигурацията на Google Диск",
        "Enable Google Drive sync" => "Активирайте синхронизирането на Google Диск",
        "Auto-restore at startup" => "Автоматично възстановяване при стартиране",
        "Click the button below to connect with Google OAuth." => "Щракнете върху бутона по-долу, за да се свържете с Google OAuth.",
        "Connect with Google" => "Свържете се с Google",
        "OAuth status: configured." => "Състояние на OAuth: конфигуриран.",
        "OAuth status: not connected." => "OAuth състояние: няма връзка.",
        "OAuth status: connecting..." => "OAuth състояние: свързва се...",
        "Unknown OAuth error." => "Неизвестна OAuth грешка.",
        "OAuth status: failed ({0})" => "Състояние на OAuth: неуспешно ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth връзката е неуспешна.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Google акаунт е свързан",
        "(not detected)" => "(не е открит)",
        "OAuth client source: {0}" => "OAuth клиентски източник: {0}",
        "Drive file ID (optional):" => "Идентификатор на файла в Диск (по избор):",
        "Export settings" => "Експортиране на настройки",
        "Import settings" => "Импортиране на настройки",
        "Select Google OAuth credentials JSON" => "Изберете Google OAuth идентификационни данни JSON",
        "OAuth status: credentials file required." => "Състояние на OAuth: изисква се файл с идентификационни данни.",
        "OAuth status: error ({0})" => "OAuth състояние: грешка ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Не могат да се прочетат идентификационни данни за OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth състояние: свързан ({0}).",
        "Settings exported to:{0}{1}" => "Настройките са експортирани в: {0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Не могат да се експортират настройки.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Импортирането на файл с настройки ще замени текущата ви локална конфигурация. Продължаване?",
        "Unable to read the selected file.{0}{0}{1}" => "Не може да се прочете избраният файл.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Избраният файл не съдържа валидни настройки JSON.",
        "Settings imported from:{0}{1}" => "Настройките са импортирани от: {0}{1}",
        _ => english
    };
}



