namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateAr(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "جوجل درايف",
        "Evernote Export" => "تصدير إيفرنوت",
        "Settings" => "إعدادات",
        "Save" => "يحفظ",
        "Cancel" => "يلغي",
        "App:" => "برنامج:",
        "Refresh" => "ينعش",
        "Log out" => "تسجيل الخروج",
        "Switch to" => "التبديل إلى",
        "Exit" => "مخرج",
        "{0} is still running" => "{0} لا يزال قيد التشغيل",
        "Use the tray icon to reopen or exit." => "استخدم رمز الدرج لإعادة فتحه أو الخروج منه.",
        "Ignore" => "يتجاهل",
        "Ignore {0}" => "تجاهل {0}",
        "Unignore {0}" => "إلغاء التجاهل {0}",
        "Set export file for {0}..." => "تعيين ملف التصدير لـ {0}...",
        "Clear export file name" => "مسح اسم ملف التصدير",
        "Clear export file ({0})" => "مسح ملف التصدير ({0})",
        "stack" => "كومة",
        "notebook" => "دفتر",
        "Select the Evernote root folder, then export the checked notebooks." => "حدد مجلد Evernote الجذر، ثم قم بتصدير دفاتر الملاحظات المحددة.",
        "Evernote Folder..." => "مجلد إيفرنوت...",
        "Reload" => "إعادة تحميل",
        "Export" => "يصدّر",
        "Evernote polling frequency (minutes):" => "تكرار استطلاع Evernote (بالدقائق):",
        "Pause automatic polling" => "إيقاف الاستقصاء التلقائي مؤقتًا",
        "Lock: (none)" => "القفل: (لا يوجد)",
        "Force" => "قوة",
        "State poll: every 6s, next in --s" => "استطلاع الولاية: كل 6 ثوانٍ، التالي في --s",
        "Keep last X markdown exports:" => "احتفظ بصادرات تخفيض السعر X الأخيرة:",
        "Older files in ./markdown will be deleted automatically after each export." => "سيتم حذف الملفات الأقدم في ./markdown تلقائيًا بعد كل عملية تصدير.",
        "No Evernote folder selected." => "لم يتم تحديد مجلد Evernote.",
        "Show ignored" => "عرض تم تجاهله",
        "Right-click: ignore or set export file name." => "انقر بزر الماوس الأيمن: تجاهل أو قم بتعيين اسم ملف التصدير.",
        "Choose the root folder of the Evernote installation" => "اختر المجلد الجذر لتثبيت Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "تم اكتشاف قاعدة البيانات: {0} | الأكوام: {1} | دفاتر الملاحظات: {2}",
        "DB error: {0}" => "خطأ في قاعدة البيانات: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "غير قادر على قراءة قاعدة بيانات Evernote.{0}{0}{1}",
        " [ignored]" => "[تم التجاهل]",
        " | updated: {0}" => "| تم التحديث: {0}",
        " | export: {0}.md" => "| التصدير: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} دفاتر الملاحظات){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} ملاحظات){2}{3}{4}",
        "(none)" => "(لا أحد)",
        "Lock: {0}" => "القفل: {0}",
        "awaiting confirmation from {0}" => "في انتظار التأكيد من {0}",
        "State poll: every {0}s, next in {1}s" => "استطلاع الولاية: كل {0}s، التالي في {1}s",
        "Export File Name" => "تصدير اسم الملف",
        "Export file name for {0} (without .md):" => "تصدير اسم الملف لـ {0} (بدون .md):",
        "The same name lets you group multiple stacks/notebooks." => "يتيح لك الاسم نفسه تجميع عدة مكدسات/أجهزة كمبيوتر محمولة.",
        "Invalid name. Use at least one valid character." => "اسم غير صالح. استخدم حرفًا صالحًا واحدًا على الأقل.",
        "Language" => "لغة",
        "Choose the UI language" => "اختر لغة واجهة المستخدم",
        "System default" => "الافتراضي للنظام",
        "Close button behavior:" => "سلوك زر الإغلاق:",
        "Minimize to tray" => "تصغير إلى الدرج",
        "Close app" => "إغلاق التطبيق",
        "Controls what happens when you click the window close button." => "يتحكم في ما يحدث عند النقر فوق زر إغلاق النافذة.",
        "Enable debug logs" => "تمكين سجلات التصحيح",
        "Local config file: {0}" => "ملف التكوين المحلي: {0}",
        "Google Drive config sync" => "مزامنة تكوين Google Drive",
        "Enable Google Drive sync" => "تمكين مزامنة جوجل درايف",
        "Auto-restore at startup" => "الاستعادة التلقائية عند بدء التشغيل",
        "Click the button below to connect with Google OAuth." => "انقر فوق الزر أدناه للاتصال بـ Google OAuth.",
        "Connect with Google" => "تواصل مع جوجل",
        "OAuth status: configured." => "حالة OAuth: تم تكوينه.",
        "OAuth status: not connected." => "حالة OAuth: غير متصل.",
        "OAuth status: connecting..." => "حالة OAuth: جارٍ الاتصال...",
        "Unknown OAuth error." => "خطأ OAuth غير معروف.",
        "OAuth status: failed ({0})" => "حالة OAuth: فشل ({0})",
        "OAuth connection failed.{0}{0}{1}" => "فشل اتصال OAuth.{0}{0}{1}",
        "Google Drive OAuth" => "جوجل درايف OAuth",
        "Google account connected" => "حساب Google متصل",
        "(not detected)" => "(لم يتم الكشف عنها)",
        "OAuth client source: {0}" => "مصدر عميل OAuth: {0}",
        "Drive file ID (optional):" => "معرف ملف محرك الأقراص (اختياري):",
        "Export settings" => "إعدادات التصدير",
        "Import settings" => "إعدادات الاستيراد",
        "Select Google OAuth credentials JSON" => "حدد بيانات اعتماد Google OAuth JSON",
        "OAuth status: credentials file required." => "حالة OAuth: ملف بيانات الاعتماد مطلوب.",
        "OAuth status: error ({0})" => "حالة OAuth: خطأ ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "غير قادر على قراءة بيانات اعتماد OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "حالة OAuth: متصل ({0}).",
        "Settings exported to:{0}{1}" => "تم تصدير الإعدادات إلى:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "غير قادر على تصدير الإعدادات.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "سيؤدي استيراد ملف الإعدادات إلى استبدال التكوين المحلي الحالي. يكمل؟",
        "Unable to read the selected file.{0}{0}{1}" => "غير قادر على قراءة الملف المحدد.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "الملف المحدد لا يحتوي على إعدادات صالحة JSON.",
        "Settings imported from:{0}{1}" => "تم استيراد الإعدادات من:{0}{1}",
        _ => english
    };
}



