namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateTr(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Evernote Dışa Aktarma",
        "Settings" => "Ayarlar",
        "Save" => "Kaydetmek",
        "Cancel" => "İptal etmek",
        "App:" => "Uygulama:",
        "Refresh" => "Yenile",
        "Log out" => "Oturumu kapat",
        "Switch to" => "Geçiş yap",
        "Exit" => "Çıkış",
        "{0} is still running" => "{0} hala çalışıyor",
        "Use the tray icon to reopen or exit." => "Yeniden açmak veya çıkmak için tepsi simgesini kullanın.",
        "Ignore" => "Görmezden gelmek",
        "Ignore {0}" => "{0} yoksay",
        "Unignore {0}" => "Yoksaymayı bırak {0}",
        "Set export file for {0}..." => "{0} için dışa aktarma dosyasını ayarla...",
        "Clear export file name" => "Dışa aktarma dosyası adını temizle",
        "Clear export file ({0})" => "Dışa aktarma dosyasını temizle ({0})",
        "stack" => "yığın",
        "notebook" => "not defteri",
        "Select the Evernote root folder, then export the checked notebooks." => "Evernote kök klasörünü seçin ve işaretlenen not defterlerini dışa aktarın.",
        "Evernote Folder..." => "Evernote Klasörü...",
        "Reload" => "Yeniden yükle",
        "Export" => "İhracat",
        "Evernote polling frequency (minutes):" => "Evernote yoklama sıklığı (dakika):",
        "Pause automatic polling" => "Otomatik yoklamayı duraklat",
        "Lock: (none)" => "Kilit: (yok)",
        "Force" => "Güç",
        "State poll: every 6s, next in --s" => "Eyalet anketi: her 6 saniyede bir, sonraki --s",
        "Keep last X markdown exports:" => "Son X işaretleme ihracatını koru:",
        "Older files in ./markdown will be deleted automatically after each export." => "./markdown içindeki eski dosyalar her dışa aktarımdan sonra otomatik olarak silinecektir.",
        "No Evernote folder selected." => "Evernote klasörü seçilmedi.",
        "Show ignored" => "Yok sayılanları göster",
        "Right-click: ignore or set export file name." => "Sağ tıklayın: dışa aktarma dosyası adını yoksayın veya ayarlayın.",
        "Choose the root folder of the Evernote installation" => "Evernote kurulumunun kök klasörünü seçin",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "Veritabanı algılandı: {0} | Yığınlar: {1} | Defterler: {2}",
        "DB error: {0}" => "Veritabanı hatası: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Evernote veritabanı okunamıyor.{0}{0}{1}",
        " [ignored]" => "[göz ardı edildi]",
        " | updated: {0}" => "| güncellendi: {0}",
        " | export: {0}.md" => "| dışa aktarma: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} not defterleri){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} notlar){2}{3}{4}",
        "(none)" => "(hiçbiri)",
        "Lock: {0}" => "Kilit: {0}",
        "awaiting confirmation from {0}" => "{0} tarafından onay bekleniyor",
        "State poll: every {0}s, next in {1}s" => "Eyalet anketi: her {0}s'de bir, sonraki {1}s'de",
        "Export File Name" => "Dosya Adını Dışa Aktar",
        "Export file name for {0} (without .md):" => "{0} için dosya adını dışa aktarın (.md olmadan):",
        "The same name lets you group multiple stacks/notebooks." => "Aynı ad, birden fazla yığını/dizüstü bilgisayarı gruplandırmanıza olanak tanır.",
        "Invalid name. Use at least one valid character." => "Geçersiz ad. En az bir geçerli karakter kullanın.",
        "Language" => "Dil",
        "Choose the UI language" => "Kullanıcı arayüzü dilini seçin",
        "System default" => "Sistem varsayılanı",
        "Close button behavior:" => "Kapat düğmesi davranışı:",
        "Minimize to tray" => "Tepsiye küçült",
        "Close app" => "Uygulamayı kapat",
        "Controls what happens when you click the window close button." => "Pencere kapat düğmesini tıklattığınızda ne olacağını kontrol eder.",
        "Enable debug logs" => "Hata ayıklama günlüklerini etkinleştir",
        "Local config file: {0}" => "Yerel yapılandırma dosyası: {0}",
        "Google Drive config sync" => "Google Drive yapılandırma senkronizasyonu",
        "Enable Google Drive sync" => "Google Drive senkronizasyonunu etkinleştir",
        "Auto-restore at startup" => "Başlangıçta otomatik geri yükleme",
        "Click the button below to connect with Google OAuth." => "Google OAuth'a bağlanmak için aşağıdaki düğmeyi tıklayın.",
        "Connect with Google" => "Google'a bağlanın",
        "OAuth status: configured." => "OAuth durumu: yapılandırılmış.",
        "OAuth status: not connected." => "OAuth durumu: bağlı değil.",
        "OAuth status: connecting..." => "OAuth durumu: bağlanılıyor...",
        "Unknown OAuth error." => "Bilinmeyen OAuth hatası.",
        "OAuth status: failed ({0})" => "OAuth durumu: başarısız oldu ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth bağlantısı başarısız oldu.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Google hesabı bağlandı",
        "(not detected)" => "(algılanmadı)",
        "OAuth client source: {0}" => "OAuth istemci kaynağı: {0}",
        "Drive file ID (optional):" => "Drive dosyası kimliği (isteğe bağlı):",
        "Export settings" => "Ayarları dışa aktar",
        "Import settings" => "Ayarları içe aktar",
        "Select Google OAuth credentials JSON" => "Google OAuth kimlik bilgileri JSON'u seçin",
        "OAuth status: credentials file required." => "OAuth durumu: kimlik bilgileri dosyası gerekli.",
        "OAuth status: error ({0})" => "OAuth durumu: hata ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "OAuth kimlik bilgileri okunamıyor.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth durumu: bağlandı ({0}).",
        "Settings exported to:{0}{1}" => "Ayarlar şuraya aktarıldı:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Ayarlar dışa aktarılamıyor.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Bir ayarlar dosyasının içe aktarılması mevcut yerel yapılandırmanızın yerini alacaktır. Devam etmek?",
        "Unable to read the selected file.{0}{0}{1}" => "Seçilen dosya okunamıyor.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Seçilen dosya geçerli JSON ayarlarını içermiyor.",
        "Settings imported from:{0}{1}" => "Ayarlar şuradan içe aktarıldı:{0}{1}",
        _ => english
    };
}



