namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateGl(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Exportación Evernote",
        "Settings" => "Configuración",
        "Save" => "Gardar",
        "Cancel" => "Cancelar",
        "App:" => "Aplicación:",
        "Refresh" => "Actualizar",
        "Log out" => "Pechar sesión",
        "Switch to" => "Cambiar a",
        "Exit" => "Saír",
        "{0} is still running" => "{0} aínda está en execución",
        "Use the tray icon to reopen or exit." => "Use a icona da bandexa para volver abrir ou saír.",
        "Ignore" => "Ignorar",
        "Ignore {0}" => "Ignorar {0}",
        "Unignore {0}" => "Non ignorar {0}",
        "Set export file for {0}..." => "Establecer ficheiro de exportación para {0}...",
        "Clear export file name" => "Borrar o nome do ficheiro de exportación",
        "Clear export file ({0})" => "Borrar o ficheiro de exportación ({0})",
        "stack" => "pila",
        "notebook" => "caderno",
        "Select the Evernote root folder, then export the checked notebooks." => "Seleccione o cartafol raíz de Evernote e, a continuación, exporte os cadernos marcados.",
        "Evernote Folder..." => "Cartafol Evernote...",
        "Reload" => "Recarga",
        "Export" => "Exportar",
        "Evernote polling frequency (minutes):" => "Frecuencia de votación de Evernote (minutos):",
        "Pause automatic polling" => "Pausa a votación automática",
        "Lock: (none)" => "Bloqueo: (ningunha)",
        "Force" => "Forza",
        "State poll: every 6s, next in --s" => "Enquisa estatal: cada 6 segundos, a continuación en --s",
        "Keep last X markdown exports:" => "Manter as últimas exportacións de rebaixa X:",
        "Older files in ./markdown will be deleted automatically after each export." => "Os ficheiros máis antigos de ./markdown eliminaranse automaticamente despois de cada exportación.",
        "No Evernote folder selected." => "Non se seleccionou ningún cartafol de Evernote.",
        "Show ignored" => "Amosar ignorado",
        "Right-click: ignore or set export file name." => "Fai clic co botón dereito do rato: ignora ou define o nome do ficheiro de exportación.",
        "Choose the root folder of the Evernote installation" => "Escolla o cartafol raíz da instalación de Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "Base de datos detectada: {0} | Pilas: {1} | Cadernos: {2}",
        "DB error: {0}" => "Erro de base de datos: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Non se puido ler a base de datos de Evernote.{0}{0}{1}",
        " [ignored]" => "[ignorado]",
        " | updated: {0}" => "| actualizado: {0}",
        " | export: {0}.md" => "| exportar: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} cadernos){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} notas){2}{3}{4}",
        "(none)" => "(ningunha)",
        "Lock: {0}" => "Bloqueo: {0}",
        "awaiting confirmation from {0}" => "agardando a confirmación de {0}",
        "State poll: every {0}s, next in {1}s" => "Enquisa estatal: cada {0}s, a seguinte en {1}s",
        "Export File Name" => "Exportar o nome do ficheiro",
        "Export file name for {0} (without .md):" => "Exportar o nome do ficheiro para {0} (sen .md):",
        "The same name lets you group multiple stacks/notebooks." => "O mesmo nome permíteche agrupar varias pilas/cadernos.",
        "Invalid name. Use at least one valid character." => "Nome non válido. Use polo menos un carácter válido.",
        "Language" => "Linguaxe",
        "Choose the UI language" => "Escolla o idioma da IU",
        "System default" => "Sistema predeterminado",
        "Close button behavior:" => "Comportamento do botón de pechar:",
        "Minimize to tray" => "Minimizar a bandexa",
        "Close app" => "Pechar a aplicación",
        "Controls what happens when you click the window close button." => "Controla o que ocorre cando fai clic no botón de pechar a fiestra.",
        "Enable debug logs" => "Activar rexistros de depuración",
        "Local config file: {0}" => "Ficheiro de configuración local: {0}",
        "Google Drive config sync" => "Sincronización de configuración de Google Drive",
        "Enable Google Drive sync" => "Activa a sincronización de Google Drive",
        "Auto-restore at startup" => "Restauración automática ao inicio",
        "Click the button below to connect with Google OAuth." => "Fai clic no botón de abaixo para conectarte con Google OAuth.",
        "Connect with Google" => "Conecta con Google",
        "OAuth status: configured." => "Estado de OAuth: configurado.",
        "OAuth status: not connected." => "Estado de OAuth: non conectado.",
        "OAuth status: connecting..." => "Estado de OAuth: conectando...",
        "Unknown OAuth error." => "Erro de OAuth descoñecido.",
        "OAuth status: failed ({0})" => "Estado de OAuth: fallou ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Fallou a conexión con OAuth.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Conta de Google conectada",
        "(not detected)" => "(non detectado)",
        "OAuth client source: {0}" => "Fonte do cliente OAuth: {0}",
        "Drive file ID (optional):" => "ID do ficheiro de Drive (opcional):",
        "Export settings" => "Exportar a configuración",
        "Import settings" => "Importar configuración",
        "Select Google OAuth credentials JSON" => "Seleccione as credenciais de Google OAuth JSON",
        "OAuth status: credentials file required." => "Estado de OAuth: é necesario o ficheiro de credenciais.",
        "OAuth status: error ({0})" => "Estado de OAuth: erro ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Non se poden ler as credenciais de OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Estado de OAuth: conectado ({0}).",
        "Settings exported to:{0}{1}" => "Configuración exportada a:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Non se puido exportar a configuración.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Ao importar un ficheiro de configuración substituirá a súa configuración local actual. Queres continuar?",
        "Unable to read the selected file.{0}{0}{1}" => "Non se puido ler o ficheiro seleccionado.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "O ficheiro seleccionado non contén configuracións JSON válidas.",
        "Settings imported from:{0}{1}" => "Configuración importada de:{0}{1}",
        _ => english
    };
}



