namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateJa(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Googleドライブ",
        "Evernote Export" => "Evernote エクスポート",
        "Settings" => "設定",
        "Save" => "保存",
        "Cancel" => "キャンセル",
        "App:" => "アプリ：",
        "Refresh" => "リフレッシュ",
        "Log out" => "ログアウト",
        "Switch to" => "に切り替えます",
        "Exit" => "出口",
        "{0} is still running" => "{0} はまだ実行中です",
        "Use the tray icon to reopen or exit." => "再度開くか終了するには、トレイ アイコンを使用します。",
        "Ignore" => "無視する",
        "Ignore {0}" => "{0} を無視する",
        "Unignore {0}" => "{0} を無視する",
        "Set export file for {0}..." => "{0} のエクスポート ファイルを設定します...",
        "Clear export file name" => "エクスポートファイル名のクリア",
        "Clear export file ({0})" => "エクスポート ファイルのクリア ({0})",
        "stack" => "スタック",
        "notebook" => "ノート",
        "Select the Evernote root folder, then export the checked notebooks." => "Evernote ルート フォルダーを選択し、チェックしたノートブックをエクスポートします。",
        "Evernote Folder..." => "Evernote フォルダー...",
        "Reload" => "リロード",
        "Export" => "輸出",
        "Evernote polling frequency (minutes):" => "Evernote のポーリング頻度 (分):",
        "Pause automatic polling" => "自動ポーリングを一時停止する",
        "Lock: (none)" => "ロック：（なし）",
        "Force" => "力",
        "State poll: every 6s, next in --s" => "州の投票: 6 秒ごと、次は --s 後",
        "Keep last X markdown exports:" => "最後の X マークダウン エクスポートを保持します。",
        "Older files in ./markdown will be deleted automatically after each export." => "./markdown 内の古いファイルは、エクスポートのたびに自動的に削除されます。",
        "No Evernote folder selected." => "Evernote フォルダーが選択されていません。",
        "Show ignored" => "無視された表示",
        "Right-click: ignore or set export file name." => "右クリック: 無視するか、エクスポート ファイル名を設定します。",
        "Choose the root folder of the Evernote installation" => "Evernote インストールのルート フォルダーを選択します",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB が検出されました: {0} |スタック: {1} |ノートブック: {2}",
        "DB error: {0}" => "DB エラー: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Evernote データベースを読み取れません。{0}{0}{1}",
        " [ignored]" => "[無視]",
        " | updated: {0}" => "|更新日: {0}",
        " | export: {0}.md" => "|エクスポート: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} ノートブック){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} メモ){2}{3}{4}",
        "(none)" => "（なし）",
        "Lock: {0}" => "ロック: {0}",
        "awaiting confirmation from {0}" => "{0} からの確認を待っています",
        "State poll: every {0}s, next in {1}s" => "州の世論調査: {0} 秒ごと、次は {1} 秒以内",
        "Export File Name" => "エクスポートファイル名",
        "Export file name for {0} (without .md):" => "{0} のエクスポート ファイル名 (.md なし):",
        "The same name lets you group multiple stacks/notebooks." => "同じ名前を使用すると、複数のスタック/ノートブックをグループ化できます。",
        "Invalid name. Use at least one valid character." => "無効な名前です。少なくとも 1 つの有効な文字を使用してください。",
        "Language" => "言語",
        "Choose the UI language" => "UI言語を選択してください",
        "System default" => "システムのデフォルト",
        "Close button behavior:" => "「閉じる」ボタンの動作:",
        "Minimize to tray" => "トレイに最小化する",
        "Close app" => "アプリを閉じる",
        "Controls what happens when you click the window close button." => "ウィンドウを閉じるボタンをクリックしたときの動作を制御します。",
        "Enable debug logs" => "デバッグログを有効にする",
        "Local config file: {0}" => "ローカル構成ファイル: {0}",
        "Google Drive config sync" => "Googleドライブの設定同期",
        "Enable Google Drive sync" => "Google ドライブの同期を有​​効にする",
        "Auto-restore at startup" => "起動時に自動復元",
        "Click the button below to connect with Google OAuth." => "下のボタンをクリックして Google OAuth に接続します。",
        "Connect with Google" => "Google と接続する",
        "OAuth status: configured." => "OAuth ステータス: 設定済み。",
        "OAuth status: not connected." => "OAuth ステータス: 未接続。",
        "OAuth status: connecting..." => "OAuth ステータス: 接続中...",
        "Unknown OAuth error." => "不明な OAuth エラー。",
        "OAuth status: failed ({0})" => "OAuth ステータス: 失敗 ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth 接続に失敗しました。{0}{0}{1}",
        "Google Drive OAuth" => "GoogleドライブOAuth",
        "Google account connected" => "Googleアカウントが接続されました",
        "(not detected)" => "(検出されませんでした)",
        "OAuth client source: {0}" => "OAuth クライアント ソース: {0}",
        "Drive file ID (optional):" => "ドライブ ファイル ID (オプション):",
        "Export settings" => "設定のエクスポート",
        "Import settings" => "インポート設定",
        "Select Google OAuth credentials JSON" => "Google OAuth 認証情報 JSON を選択します",
        "OAuth status: credentials file required." => "OAuth ステータス: 認証情報ファイルが必要です。",
        "OAuth status: error ({0})" => "OAuth ステータス: エラー ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "OAuth 資格情報を読み取ることができません。{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth ステータス: 接続済み ({0})。",
        "Settings exported to:{0}{1}" => "設定のエクスポート先:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "設定をエクスポートできません。{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "設定ファイルをインポートすると、現在のローカル構成が置き換えられます。続く？",
        "Unable to read the selected file.{0}{0}{1}" => "選択したファイルを読み取れません。{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "選択したファイルには有効な設定 JSON が含まれていません。",
        "Settings imported from:{0}{1}" => "インポートされた設定:{0}{1}",
        _ => english
    };
}



