namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateNl(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Evernote-export",
        "Settings" => "Instellingen",
        "Save" => "Redden",
        "Cancel" => "Annuleren",
        "App:" => "Applicatie:",
        "Refresh" => "Vernieuwen",
        "Log out" => "Uitloggen",
        "Switch to" => "Schakel over naar",
        "Exit" => "Uitgang",
        "{0} is still running" => "{0} is nog steeds actief",
        "Use the tray icon to reopen or exit." => "Gebruik het systeemvakpictogram om opnieuw te openen of af te sluiten.",
        "Ignore" => "Negeren",
        "Ignore {0}" => "Negeer {0}",
        "Unignore {0}" => "Niet negeren {0}",
        "Set export file for {0}..." => "Exportbestand instellen voor {0}...",
        "Clear export file name" => "Wis de naam van het exportbestand",
        "Clear export file ({0})" => "Exportbestand wissen ({0})",
        "stack" => "stapel",
        "notebook" => "notitieboekje",
        "Select the Evernote root folder, then export the checked notebooks." => "Selecteer de Evernote-hoofdmap en exporteer vervolgens de aangevinkte notitieboekjes.",
        "Evernote Folder..." => "Evernote-map...",
        "Reload" => "Herladen",
        "Export" => "Exporteren",
        "Evernote polling frequency (minutes):" => "Pollingfrequentie van Evernote (minuten):",
        "Pause automatic polling" => "Pauzeer automatisch pollen",
        "Lock: (none)" => "Vergrendelen: (geen)",
        "Force" => "Kracht",
        "State poll: every 6s, next in --s" => "Staatspeiling: elke 6s, volgende in --s",
        "Keep last X markdown exports:" => "Behoud laatste X markdown-exports:",
        "Older files in ./markdown will be deleted automatically after each export." => "Oudere bestanden in ./markdown worden na elke export automatisch verwijderd.",
        "No Evernote folder selected." => "Geen Evernote-map geselecteerd.",
        "Show ignored" => "Toon genegeerd",
        "Right-click: ignore or set export file name." => "Klik met de rechtermuisknop: negeer of stel de exportbestandsnaam in.",
        "Choose the root folder of the Evernote installation" => "Kies de hoofdmap van de Evernote-installatie",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB gedetecteerd: {0} | Stapels: {1} | Notitieboekjes: {2}",
        "DB error: {0}" => "DB-fout: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Kan de Evernote-database niet lezen.{0}{0}{1}",
        " [ignored]" => "[genegeerd]",
        " | updated: {0}" => "| bijgewerkt: {0}",
        " | export: {0}.md" => "| exporteren: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} notitieboekjes){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} notities){2}{3}{4}",
        "(none)" => "(geen)",
        "Lock: {0}" => "Vergrendelen: {0}",
        "awaiting confirmation from {0}" => "in afwachting van bevestiging van {0}",
        "State poll: every {0}s, next in {1}s" => "Staatspeiling: elke {0}s, volgende in {1}s",
        "Export File Name" => "Bestandsnaam exporteren",
        "Export file name for {0} (without .md):" => "Bestandsnaam exporteren voor {0} (zonder .md):",
        "The same name lets you group multiple stacks/notebooks." => "Met dezelfde naam kunt u meerdere stapels/notitieboekjes groeperen.",
        "Invalid name. Use at least one valid character." => "Ongeldige naam. Gebruik ten minste één geldig teken.",
        "Language" => "Taal",
        "Choose the UI language" => "Kies de UI-taal",
        "System default" => "Systeemstandaard",
        "Close button behavior:" => "Gedrag van de knop Sluiten:",
        "Minimize to tray" => "Minimaliseren naar lade",
        "Close app" => "Sluit app",
        "Controls what happens when you click the window close button." => "Bepaalt wat er gebeurt als u op de knop Sluiten van het venster klikt.",
        "Enable debug logs" => "Schakel foutopsporingslogboeken in",
        "Local config file: {0}" => "Lokaal configuratiebestand: {0}",
        "Google Drive config sync" => "Synchronisatie van Google Drive-configuratie",
        "Enable Google Drive sync" => "Schakel Google Drive-synchronisatie in",
        "Auto-restore at startup" => "Automatisch herstel bij opstarten",
        "Click the button below to connect with Google OAuth." => "Klik op de onderstaande knop om verbinding te maken met Google OAuth.",
        "Connect with Google" => "Maak verbinding met Google",
        "OAuth status: configured." => "OAuth-status: geconfigureerd.",
        "OAuth status: not connected." => "OAuth-status: niet verbonden.",
        "OAuth status: connecting..." => "OAuth-status: verbinden...",
        "Unknown OAuth error." => "Onbekende OAuth-fout.",
        "OAuth status: failed ({0})" => "OAuth-status: mislukt ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth-verbinding mislukt.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Google-account gekoppeld",
        "(not detected)" => "(niet gedetecteerd)",
        "OAuth client source: {0}" => "OAuth-clientbron: {0}",
        "Drive file ID (optional):" => "Drive-bestands-ID (optioneel):",
        "Export settings" => "Instellingen exporteren",
        "Import settings" => "Instellingen importeren",
        "Select Google OAuth credentials JSON" => "Selecteer Google OAuth-inloggegevens JSON",
        "OAuth status: credentials file required." => "OAuth-status: referentiebestand vereist.",
        "OAuth status: error ({0})" => "OAuth-status: fout ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Kan OAuth-inloggegevens niet lezen.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth-status: verbonden ({0}).",
        "Settings exported to:{0}{1}" => "Instellingen geëxporteerd naar:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Kan instellingen niet exporteren.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Als u een instellingenbestand importeert, wordt uw huidige lokale configuratie vervangen. Doorgaan?",
        "Unable to read the selected file.{0}{0}{1}" => "Kan het geselecteerde bestand niet lezen.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Het geselecteerde bestand bevat geen geldige JSON-instellingen.",
        "Settings imported from:{0}{1}" => "Instellingen geïmporteerd uit:{0}{1}",
        _ => english
    };
}



