namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateHr(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google disk",
        "Evernote Export" => "Evernote izvoz",
        "Settings" => "postavke",
        "Save" => "Uštedjeti",
        "Cancel" => "Otkazati",
        "App:" => "Aplikacija:",
        "Refresh" => "Osvježiti",
        "Log out" => "Odjavi se",
        "Switch to" => "Prebaci na",
        "Exit" => "Izlaz ",
        "{0} is still running" => "{0} još uvijek radi",
        "Use the tray icon to reopen or exit." => "Za ponovno otvaranje ili izlaz koristite ikonu trake.",
        "Ignore" => "Zanemariti",
        "Ignore {0}" => "Ignoriraj {0}",
        "Unignore {0}" => "Poništi zanemarivanje {0}",
        "Set export file for {0}..." => "Postavi izvoznu datoteku za {0}...",
        "Clear export file name" => "Obriši naziv datoteke za izvoz",
        "Clear export file ({0})" => "Očisti izvoznu datoteku ({0})",
        "stack" => "stog",
        "notebook" => "bilježnica",
        "Select the Evernote root folder, then export the checked notebooks." => "Odaberite korijensku mapu Evernotea, zatim izvezite označene bilježnice.",
        "Evernote Folder..." => "Evernote mapa...",
        "Reload" => "Ponovno učitaj",
        "Export" => "Izvoz",
        "Evernote polling frequency (minutes):" => "Učestalost anketiranja Evernotea (minute):",
        "Pause automatic polling" => "Pauziraj automatsko prozivanje",
        "Lock: (none)" => "Zaključaj: (ništa)",
        "Force" => "Sila",
        "State poll: every 6s, next in --s" => "Državna anketa: svakih 6s, sljedeća za --s",
        "Keep last X markdown exports:" => "Zadrži zadnjih X izvoza markdowna:",
        "Older files in ./markdown will be deleted automatically after each export." => "Starije datoteke u ./markdown automatski će se izbrisati nakon svakog izvoza.",
        "No Evernote folder selected." => "Nije odabrana mapa Evernote.",
        "Show ignored" => "Prikaz zanemaren",
        "Right-click: ignore or set export file name." => "Desni klik: ignorirajte ili postavite naziv datoteke za izvoz.",
        "Choose the root folder of the Evernote installation" => "Odaberite korijensku mapu instalacije Evernotea",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB otkriven: {0} | Hrpe: {1} | Bilježnice: {2}",
        "DB error: {0}" => "DB pogreška: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Nije moguće čitati Evernote bazu podataka.{0}{0}{1}",
        " [ignored]" => "[ignorirano]",
        " | updated: {0}" => "| ažurirano: {0}",
        " | export: {0}.md" => "| izvoz: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} bilježnica){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} bilješke){2}{3}{4}",
        "(none)" => "(ništa)",
        "Lock: {0}" => "Zaključavanje: {0}",
        "awaiting confirmation from {0}" => "čeka potvrdu od {0}",
        "State poll: every {0}s, next in {1}s" => "Državna anketa: svakih {0} s, sljedeća za {1} s",
        "Export File Name" => "Naziv datoteke izvoza",
        "Export file name for {0} (without .md):" => "Naziv datoteke izvoza za {0} (bez .md):",
        "The same name lets you group multiple stacks/notebooks." => "Isto ime vam omogućuje grupiranje više hrpova/bilježnica.",
        "Invalid name. Use at least one valid character." => "Nevažeći naziv. Koristite barem jedan važeći znak.",
        "Language" => "Jezik",
        "Choose the UI language" => "Odaberite jezik korisničkog sučelja",
        "System default" => "Zadana vrijednost sustava",
        "Close button behavior:" => "Ponašanje gumba za zatvaranje:",
        "Minimize to tray" => "Smanji na pladanj",
        "Close app" => "Zatvori aplikaciju",
        "Controls what happens when you click the window close button." => "Kontrolira što se događa kada kliknete gumb za zatvaranje prozora.",
        "Enable debug logs" => "Omogući zapisnike otklanjanja pogrešaka",
        "Local config file: {0}" => "Lokalna konfiguracijska datoteka: {0}",
        "Google Drive config sync" => "Sinkronizacija konfiguracije Google diska",
        "Enable Google Drive sync" => "Omogućite sinkronizaciju Google diska",
        "Auto-restore at startup" => "Automatsko vraćanje pri pokretanju",
        "Click the button below to connect with Google OAuth." => "Pritisnite donji gumb za povezivanje s Google OAuth.",
        "Connect with Google" => "Povežite se s Googleom",
        "OAuth status: configured." => "OAuth status: konfiguriran.",
        "OAuth status: not connected." => "OAuth status: nije povezan.",
        "OAuth status: connecting..." => "OAuth status: povezivanje...",
        "Unknown OAuth error." => "Nepoznata OAuth pogreška.",
        "OAuth status: failed ({0})" => "OAuth status: nije uspio ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth veza nije uspjela.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Google račun povezan",
        "(not detected)" => "(nije otkriveno)",
        "OAuth client source: {0}" => "Izvor OAuth klijenta: {0}",
        "Drive file ID (optional):" => "ID datoteke diska (neobavezno):",
        "Export settings" => "Izvoz postavki",
        "Import settings" => "Postavke uvoza",
        "Select Google OAuth credentials JSON" => "Odaberite Google OAuth vjerodajnice JSON",
        "OAuth status: credentials file required." => "OAuth status: potrebna je datoteka s vjerodajnicama.",
        "OAuth status: error ({0})" => "OAuth status: pogreška ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Nije moguće pročitati OAuth vjerodajnice.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth status: povezan ({0}).",
        "Settings exported to:{0}{1}" => "Postavke su izvezene u: {0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Nije moguće izvesti postavke.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Uvoz datoteke postavki zamijenit će vašu trenutnu lokalnu konfiguraciju. Nastaviti?",
        "Unable to read the selected file.{0}{0}{1}" => "Nije moguće pročitati odabranu datoteku.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Odabrana datoteka ne sadrži valjane postavke JSON.",
        "Settings imported from:{0}{1}" => "Postavke uvezene iz: {0}{1}",
        _ => english
    };
}



