namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateSk(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Disk Google",
        "Evernote Export" => "Export Evernote",
        "Settings" => "Nastavenia",
        "Save" => "Uložiť",
        "Cancel" => "Zrušiť",
        "App:" => "Aplikácia:",
        "Refresh" => "Obnoviť",
        "Log out" => "Odhláste sa",
        "Switch to" => "Prepnúť na",
        "Exit" => "VÝCHOD",
        "{0} is still running" => "{0} stále beží",
        "Use the tray icon to reopen or exit." => "Na opätovné otvorenie alebo ukončenie použite ikonu na paneli.",
        "Ignore" => "Ignorovať",
        "Ignore {0}" => "Ignorovať {0}",
        "Unignore {0}" => "Neignorovať {0}",
        "Set export file for {0}..." => "Nastaviť exportný súbor pre {0}...",
        "Clear export file name" => "Vymazať názov exportovaného súboru",
        "Clear export file ({0})" => "Vymazať exportovaný súbor ({0})",
        "stack" => "zásobník",
        "notebook" => "notebook",
        "Select the Evernote root folder, then export the checked notebooks." => "Vyberte koreňový priečinok Evernote a potom exportujte začiarknuté poznámkové bloky.",
        "Evernote Folder..." => "Priečinok Evernote...",
        "Reload" => "Znovu načítať",
        "Export" => "Exportovať",
        "Evernote polling frequency (minutes):" => "Frekvencia hlasovania Evernote (minúty):",
        "Pause automatic polling" => "Pozastaviť automatické hlasovanie",
        "Lock: (none)" => "Zámok: (žiadny)",
        "Force" => "sila",
        "State poll: every 6s, next in --s" => "Štátny prieskum: každých 6 s, ďalší o -- s",
        "Keep last X markdown exports:" => "Ponechať posledných X exportov zníženia:",
        "Older files in ./markdown will be deleted automatically after each export." => "Staršie súbory v ./markdown budú automaticky odstránené po každom exporte.",
        "No Evernote folder selected." => "Nie je vybratý žiadny priečinok Evernote.",
        "Show ignored" => "Zobraziť ignorované",
        "Right-click: ignore or set export file name." => "Kliknite pravým tlačidlom myši: ignorujte alebo nastavte názov exportovaného súboru.",
        "Choose the root folder of the Evernote installation" => "Vyberte koreňový priečinok inštalácie Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "Zistená DB: {0} | Zásobníky: {1} | Notebooky: {2}",
        "DB error: {0}" => "Chyba DB: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Nedá sa čítať databáza Evernote.{0}{0}{1}",
        " [ignored]" => "[ignorované]",
        " | updated: {0}" => "| aktualizované: {0}",
        " | export: {0}.md" => "| export: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} notebooky){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} poznámky){2}{3}{4}",
        "(none)" => "(žiadny)",
        "Lock: {0}" => "Zámok: {0}",
        "awaiting confirmation from {0}" => "čaká na potvrdenie od {0}",
        "State poll: every {0}s, next in {1}s" => "Štátny prieskum: každých {0}s, ďalší za {1}s",
        "Export File Name" => "Názov exportovaného súboru",
        "Export file name for {0} (without .md):" => "Exportovať názov súboru pre {0} (bez .md):",
        "The same name lets you group multiple stacks/notebooks." => "Rovnaký názov vám umožňuje zoskupiť viaceré zásobníky/notebooky.",
        "Invalid name. Use at least one valid character." => "Neplatné meno. Použite aspoň jeden platný znak.",
        "Language" => "Jazyk",
        "Choose the UI language" => "Vyberte jazyk používateľského rozhrania",
        "System default" => "Predvolené nastavenie systému",
        "Close button behavior:" => "Správanie tlačidla Zavrieť:",
        "Minimize to tray" => "Minimalizovať do zásobníka",
        "Close app" => "Zatvorte aplikáciu",
        "Controls what happens when you click the window close button." => "Ovláda, čo sa stane po kliknutí na tlačidlo zatvorenia okna.",
        "Enable debug logs" => "Povoliť denníky ladenia",
        "Local config file: {0}" => "Miestny konfiguračný súbor: {0}",
        "Google Drive config sync" => "Synchronizácia konfigurácie Disku Google",
        "Enable Google Drive sync" => "Povoliť synchronizáciu Disku Google",
        "Auto-restore at startup" => "Automatické obnovenie pri spustení",
        "Click the button below to connect with Google OAuth." => "Kliknutím na tlačidlo nižšie sa spojíte s protokolom Google OAuth.",
        "Connect with Google" => "Spojte sa so spoločnosťou Google",
        "OAuth status: configured." => "Stav OAuth: nakonfigurovaný.",
        "OAuth status: not connected." => "Stav OAuth: nepripojené.",
        "OAuth status: connecting..." => "Stav OAuth: pripája sa...",
        "Unknown OAuth error." => "Neznáma chyba OAuth.",
        "OAuth status: failed ({0})" => "Stav OAuth: zlyhal ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Pripojenie OAuth zlyhalo.{0}{0}{1}",
        "Google Drive OAuth" => "OAuth Disku Google",
        "Google account connected" => "Účet Google je pripojený",
        "(not detected)" => "(nezistené)",
        "OAuth client source: {0}" => "Zdroj klienta OAuth: {0}",
        "Drive file ID (optional):" => "ID súboru na Disku (voliteľné):",
        "Export settings" => "Exportovať nastavenia",
        "Import settings" => "Importovať nastavenia",
        "Select Google OAuth credentials JSON" => "Vyberte JSON poverenia Google OAuth",
        "OAuth status: credentials file required." => "Stav OAuth: Vyžaduje sa súbor poverení.",
        "OAuth status: error ({0})" => "Stav OAuth: chyba ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Nie je možné prečítať poverenia OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Stav OAuth: pripojený ({0}).",
        "Settings exported to:{0}{1}" => "Nastavenia exportované do:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Nastavenia nie je možné exportovať.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Importovanie súboru nastavení nahradí vašu aktuálnu lokálnu konfiguráciu. Pokračovať?",
        "Unable to read the selected file.{0}{0}{1}" => "Nie je možné prečítať vybratý súbor.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Vybratý súbor neobsahuje platné nastavenia JSON.",
        "Settings imported from:{0}{1}" => "Nastavenia importované z:{0}{1}",
        _ => english
    };
}



