namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateIs(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Evernote Export",
        "Settings" => "Stillingar",
        "Save" => "Vista",
        "Cancel" => "Hætta við",
        "App:" => "App:",
        "Refresh" => "Endurnýja",
        "Log out" => "Skráðu þig út",
        "Switch to" => "Skiptu yfir í",
        "Exit" => "Hætta",
        "{0} is still running" => "{0} er enn í gangi",
        "Use the tray icon to reopen or exit." => "Notaðu bakkatáknið til að opna aftur eða hætta.",
        "Ignore" => "Hunsa",
        "Ignore {0}" => "Hunsa {0}",
        "Unignore {0}" => "Hunsa {0}",
        "Set export file for {0}..." => "Stilltu útflutningsskrá fyrir {0}...",
        "Clear export file name" => "Hreinsaðu heiti útflutningsskráar",
        "Clear export file ({0})" => "Hreinsa útflutningsskrá ({0})",
        "stack" => "stafla",
        "notebook" => "minnisbók",
        "Select the Evernote root folder, then export the checked notebooks." => "Veldu Evernote rótarmöppuna og fluttu síðan út merktu fartölvurnar.",
        "Evernote Folder..." => "Evernote mappa...",
        "Reload" => "Endurhlaða",
        "Export" => "Útflutningur",
        "Evernote polling frequency (minutes):" => "Kjörtíðni Evernote (mínútur):",
        "Pause automatic polling" => "Gera hlé á sjálfvirkri skoðanakönnun",
        "Lock: (none)" => "Læsing: (enginn)",
        "Force" => "Afl",
        "State poll: every 6s, next in --s" => "Ríkiskönnun: á 6. fresti, næst í --s",
        "Keep last X markdown exports:" => "Halda síðasta X útflutningi á mörkun:",
        "Older files in ./markdown will be deleted automatically after each export." => "Eldri skrám í ./markdown verður eytt sjálfkrafa eftir hvern útflutning.",
        "No Evernote folder selected." => "Engin Evernote mappa valin.",
        "Show ignored" => "Sýna hunsuð",
        "Right-click: ignore or set export file name." => "Hægrismelltu: hunsa eða stilltu nafn útflutningsskráar.",
        "Choose the root folder of the Evernote installation" => "Veldu rótarmöppu Evernote uppsetningar",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB fannst: {0} | Staflar: {1} | Glósubækur: {2}",
        "DB error: {0}" => "DB villa: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Get ekki lesið Evernote gagnagrunn.{0}{0}{1}",
        " [ignored]" => "[hunsað]",
        " | updated: {0}" => "| uppfært: {0}",
        " | export: {0}.md" => "| útflutningur: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} minnisbækur){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} athugasemdir){2}{3}{4}",
        "(none)" => "(engin)",
        "Lock: {0}" => "Læsing: {0}",
        "awaiting confirmation from {0}" => "bíður staðfestingar frá {0}",
        "State poll: every {0}s, next in {1}s" => "Ríkiskönnun: á hverjum {0}s, næst eftir {1}s",
        "Export File Name" => "Flytja út skráarnafn",
        "Export file name for {0} (without .md):" => "Flytja út skráarheiti fyrir {0} (án .md):",
        "The same name lets you group multiple stacks/notebooks." => "Sama nafn gerir þér kleift að flokka marga stafla/fartölvur.",
        "Invalid name. Use at least one valid character." => "Ógilt nafn. Notaðu að minnsta kosti einn gildan staf.",
        "Language" => "Tungumál",
        "Choose the UI language" => "Veldu UI tungumál",
        "System default" => "Sjálfgefið kerfi",
        "Close button behavior:" => "Hegðun lokahnapps:",
        "Minimize to tray" => "Lágmarka í bakka",
        "Close app" => "Lokaðu appinu",
        "Controls what happens when you click the window close button." => "Stýrir því sem gerist þegar þú smellir á gluggalokunarhnappinn.",
        "Enable debug logs" => "Virkja villuleitarskrár",
        "Local config file: {0}" => "Staðbundin stillingarskrá: {0}",
        "Google Drive config sync" => "Google Drive samstillingarsamstilling",
        "Enable Google Drive sync" => "Virkjaðu Google Drive samstillingu",
        "Auto-restore at startup" => "Sjálfvirk endurheimt við ræsingu",
        "Click the button below to connect with Google OAuth." => "Smelltu á hnappinn hér að neðan til að tengjast Google OAuth.",
        "Connect with Google" => "Tengstu við Google",
        "OAuth status: configured." => "OAuth staða: stillt.",
        "OAuth status: not connected." => "OAuth staða: ekki tengd.",
        "OAuth status: connecting..." => "OAuth staða: tengir...",
        "Unknown OAuth error." => "Óþekkt OAuth villa.",
        "OAuth status: failed ({0})" => "OAuth staða: mistókst ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth tenging mistókst.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Google reikningur tengdur",
        "(not detected)" => "(ekki uppgötvað)",
        "OAuth client source: {0}" => "Uppruni OAuth biðlara: {0}",
        "Drive file ID (optional):" => "Drive skráaauðkenni (valfrjálst):",
        "Export settings" => "Flytja út stillingar",
        "Import settings" => "Flytja inn stillingar",
        "Select Google OAuth credentials JSON" => "Veldu Google OAuth skilríki JSON",
        "OAuth status: credentials file required." => "OAuth staða: skilríkisskrá krafist.",
        "OAuth status: error ({0})" => "OAuth staða: villa ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Ekki er hægt að lesa OAuth skilríki.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth staða: tengd ({0}).",
        "Settings exported to:{0}{1}" => "Stillingar fluttar út í:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Ekki hægt að flytja út stillingar.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Innflutningur á stillingaskrá mun koma í stað núverandi staðbundinnar stillingar. Halda áfram?",
        "Unable to read the selected file.{0}{0}{1}" => "Get ekki lesið valda skrá.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Valin skrá inniheldur ekki gildar stillingar JSON.",
        "Settings imported from:{0}{1}" => "Stillingar fluttar inn frá:{0}{1}",
        _ => english
    };
}



