namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateLt(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google diskas",
        "Evernote Export" => "„Evernote“ eksportas",
        "Settings" => "Nustatymai",
        "Save" => "Išsaugoti",
        "Cancel" => "Atšaukti",
        "App:" => "Programėlė:",
        "Refresh" => "Atnaujinti",
        "Log out" => "Atsijungti",
        "Switch to" => "Perjungti į",
        "Exit" => "Išeiti",
        "{0} is still running" => "{0} vis dar veikia",
        "Use the tray icon to reopen or exit." => "Norėdami vėl atidaryti arba išeiti, naudokite dėklo piktogramą.",
        "Ignore" => "Ignoruoti",
        "Ignore {0}" => "Ignoruoti {0}",
        "Unignore {0}" => "Neignoruoti {0}",
        "Set export file for {0}..." => "Nustatyti eksporto failą {0}...",
        "Clear export file name" => "Išvalyti eksporto failo pavadinimą",
        "Clear export file ({0})" => "Išvalyti eksporto failą ({0})",
        "stack" => "krūva",
        "notebook" => "užrašų knygelė",
        "Select the Evernote root folder, then export the checked notebooks." => "Pasirinkite Evernote šakninį aplanką, tada eksportuokite pažymėtus bloknotus.",
        "Evernote Folder..." => "Evernote aplankas...",
        "Reload" => "Įkelti iš naujo",
        "Export" => "Eksportuoti",
        "Evernote polling frequency (minutes):" => "Evernote apklausų dažnis (minutės):",
        "Pause automatic polling" => "Pristabdyti automatinį balsavimą",
        "Lock: (none)" => "Užraktas: (nėra)",
        "Force" => "Jėga",
        "State poll: every 6s, next in --s" => "Valstybės apklausa: kas 6 s, kitas po --s",
        "Keep last X markdown exports:" => "Palikti paskutinį X žymėjimo eksportą:",
        "Older files in ./markdown will be deleted automatically after each export." => "Senesni failai ./markdown bus automatiškai ištrinti po kiekvieno eksportavimo.",
        "No Evernote folder selected." => "Nepasirinktas joks Evernote aplankas.",
        "Show ignored" => "Rodyti nepaisoma",
        "Right-click: ignore or set export file name." => "Dešiniuoju pelės mygtuku spustelėkite: nepaisykite arba nustatykite eksporto failo pavadinimą.",
        "Choose the root folder of the Evernote installation" => "Pasirinkite „Evernote“ diegimo šakninį aplanką",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB aptikta: {0} | Krūvos: {1} | Užrašų knygelės: {2}",
        "DB error: {0}" => "DB klaida: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Nepavyko nuskaityti Evernote duomenų bazės.{0}{0}{1}",
        " [ignored]" => "[nepaisoma]",
        " | updated: {0}" => "| atnaujinta: {0}",
        " | export: {0}.md" => "| eksportuoti: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} užrašų knygelės){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} pastabos){2}{3}{4}",
        "(none)" => "(nėra)",
        "Lock: {0}" => "Užraktas: {0}",
        "awaiting confirmation from {0}" => "laukiama patvirtinimo iš {0}",
        "State poll: every {0}s, next in {1}s" => "Būsenos apklausa: kas {0}s, kita po {1}s",
        "Export File Name" => "Eksportuoti failo pavadinimą",
        "Export file name for {0} (without .md):" => "Eksportuoti failo pavadinimą, skirtą {0} (be .md):",
        "The same name lets you group multiple stacks/notebooks." => "Tuo pačiu pavadinimu galite grupuoti kelis krūvelius / užrašų knygeles.",
        "Invalid name. Use at least one valid character." => "Neteisingas pavadinimas. Naudokite bent vieną tinkamą simbolį.",
        "Language" => "Kalba",
        "Choose the UI language" => "Pasirinkite vartotojo sąsajos kalbą",
        "System default" => "Numatytasis sistemos",
        "Close button behavior:" => "Uždaryti mygtuko veikimas:",
        "Minimize to tray" => "Sumažinti iki dėklo",
        "Close app" => "Uždaryti programą",
        "Controls what happens when you click the window close button." => "Valdo, kas atsitiks, kai spustelėsite lango uždarymo mygtuką.",
        "Enable debug logs" => "Įgalinti derinimo žurnalus",
        "Local config file: {0}" => "Vietinis konfigūracijos failas: {0}",
        "Google Drive config sync" => "„Google“ disko konfigūracijos sinchronizavimas",
        "Enable Google Drive sync" => "Įgalinti „Google“ disko sinchronizavimą",
        "Auto-restore at startup" => "Automatinis atkūrimas paleidžiant",
        "Click the button below to connect with Google OAuth." => "Spustelėkite toliau esantį mygtuką, kad prisijungtumėte prie „Google OAuth“.",
        "Connect with Google" => "Susisiekite su Google",
        "OAuth status: configured." => "OAuth būsena: sukonfigūruota.",
        "OAuth status: not connected." => "OAuth būsena: neprisijungta.",
        "OAuth status: connecting..." => "OAuth būsena: jungiamasi...",
        "Unknown OAuth error." => "Nežinoma OAuth klaida.",
        "OAuth status: failed ({0})" => "OAuth būsena: nepavyko ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth ryšys nepavyko.{0}{0}{1}",
        "Google Drive OAuth" => "„Google“ disko „OAuth“.",
        "Google account connected" => "„Google“ paskyra prijungta",
        "(not detected)" => "(neaptikta)",
        "OAuth client source: {0}" => "„OAuth“ kliento šaltinis: {0}",
        "Drive file ID (optional):" => "Disko failo ID (pasirenkama):",
        "Export settings" => "Eksportuoti nustatymus",
        "Import settings" => "Importuoti nustatymus",
        "Select Google OAuth credentials JSON" => "Pasirinkite „Google OAuth“ kredencialų JSON",
        "OAuth status: credentials file required." => "OAuth būsena: reikalingas kredencialų failas.",
        "OAuth status: error ({0})" => "OAuth būsena: klaida ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Nepavyko nuskaityti OAuth kredencialų.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth būsena: prijungta ({0}).",
        "Settings exported to:{0}{1}" => "Nustatymai eksportuoti į:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Nepavyko eksportuoti nustatymų.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Nustatymų failo importavimas pakeis dabartinę vietinę konfigūraciją. Tęsti?",
        "Unable to read the selected file.{0}{0}{1}" => "Nepavyko nuskaityti pasirinkto failo.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Pasirinktame faile nėra galiojančių JSON nustatymų.",
        "Settings imported from:{0}{1}" => "Nustatymai importuoti iš:{0}{1}",
        _ => english
    };
}



