namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateGa(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Easpórtáil Evernote",
        "Settings" => "Socruithe",
        "Save" => "Sábháil",
        "Cancel" => "Cealaigh",
        "App:" => "Aip:",
        "Refresh" => "Athnuaigh",
        "Log out" => "Logáil amach",
        "Switch to" => "Athraigh go",
        "Exit" => "Scoir",
        "{0} is still running" => "Tá {0} fós ag rith",
        "Use the tray icon to reopen or exit." => "Úsáid íocón an tráidire chun athoscailt nó imeacht.",
        "Ignore" => "Déan neamhaird de",
        "Ignore {0}" => "Déan neamhaird de {0}",
        "Unignore {0}" => "Gan neamhaird {0}",
        "Set export file for {0}..." => "Socraigh comhad easpórtála le haghaidh {0}...",
        "Clear export file name" => "Glan ainm an chomhaid easpórtála",
        "Clear export file ({0})" => "Glan an comhad easpórtála ({0})",
        "stack" => "cruacha",
        "notebook" => "leabhar nótaí",
        "Select the Evernote root folder, then export the checked notebooks." => "Roghnaigh an fillteán fréimhe Evernote, ansin onnmhairiú na leabhair nótaí seiceáilte.",
        "Evernote Folder..." => "Fillteán Evernote...",
        "Reload" => "Athlódáil",
        "Export" => "Easpórtáil",
        "Evernote polling frequency (minutes):" => "Minicíocht vótaíochta Evernote (nóiméid):",
        "Pause automatic polling" => "Cuir vótaíocht uathoibríoch ar sos",
        "Lock: (none)" => "Glasáil: (aon cheann)",
        "Force" => "Fórsa",
        "State poll: every 6s, next in --s" => "vótaíocht stáit: gach 6s, an chéad cheann eile i --s",
        "Keep last X markdown exports:" => "Coinnigh na heaspórtálacha marcála síos deiridh X:",
        "Older files in ./markdown will be deleted automatically after each export." => "Scriosfar comhaid níos sine in ./markdown go huathoibríoch tar éis gach easpórtála.",
        "No Evernote folder selected." => "Níor roghnaíodh aon fhillteán Evernote.",
        "Show ignored" => "Neamhaird ar an seó",
        "Right-click: ignore or set export file name." => "Cliceáil ar dheis: déan neamhaird de nó socraigh ainm an chomhaid easpórtála.",
        "Choose the root folder of the Evernote installation" => "Roghnaigh fillteán fréimhe na suiteála Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB braite: {0} | Cruacha: {1} | Leabhair Nótaí: {2}",
        "DB error: {0}" => "Earráid DB: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Ní féidir bunachar sonraí Evernote a léamh.{0}{0}{1}",
        " [ignored]" => "[neamhaird]",
        " | updated: {0}" => "| nuashonraithe: {0}",
        " | export: {0}.md" => "| onnmhairiú: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} leabhair nótaí){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} nótaí){2}{3}{4}",
        "(none)" => "(aon cheann)",
        "Lock: {0}" => "Glasáil: {0}",
        "awaiting confirmation from {0}" => "ag fanacht le deimhniú ó {0}",
        "State poll: every {0}s, next in {1}s" => "vótaíocht stáit: gach {0}s, an chéad cheann eile i {1}s",
        "Export File Name" => "Easpórtáil Ainm an Chomhaid",
        "Export file name for {0} (without .md):" => "Easpórtáil ainm comhaid le haghaidh {0} (gan .md):",
        "The same name lets you group multiple stacks/notebooks." => "Ligeann an t-ainm céanna duit stoic/leabhair nótaí iolracha a ghrúpáil.",
        "Invalid name. Use at least one valid character." => "Ainm neamhbhailí. Úsáid carachtar bailí amháin ar a laghad.",
        "Language" => "Teanga",
        "Choose the UI language" => "Roghnaigh an teanga Chomhéadain",
        "System default" => "Réamhshocrú córais",
        "Close button behavior:" => "Iompar cnaipe dúnta:",
        "Minimize to tray" => "Íoslaghdaigh go tráidire",
        "Close app" => "Dún an app",
        "Controls what happens when you click the window close button." => "Rialaíonn sé cad a tharlaíonn nuair a chliceálann tú an cnaipe dún fuinneoige.",
        "Enable debug logs" => "Cumasaigh logaí dífhabhtaithe",
        "Local config file: {0}" => "Comhad cumraíochta logánta: {0}",
        "Google Drive config sync" => "Sioncronú cumraíochta Google Drive",
        "Enable Google Drive sync" => "Cumasaigh Google Drive sioncrónaithe",
        "Auto-restore at startup" => "Athchóirigh uathoibríoch ag am tosaithe",
        "Click the button below to connect with Google OAuth." => "Cliceáil ar an gcnaipe thíos chun nascadh le Google OAuth.",
        "Connect with Google" => "Ceangail le Google",
        "OAuth status: configured." => "Stádas OAuth: cumraithe.",
        "OAuth status: not connected." => "Stádas OAuth: níl sé ceangailte.",
        "OAuth status: connecting..." => "Stádas OAuth: ag nascadh...",
        "Unknown OAuth error." => "Earráid anaithnid OAuth.",
        "OAuth status: failed ({0})" => "Stádas OAuth: theip air ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Theip ar cheangal OAuth.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Cuntas Google nasctha",
        "(not detected)" => "(gan braitheadh)",
        "OAuth client source: {0}" => "Foinse cliaint OAuth: {0}",
        "Drive file ID (optional):" => "Aitheantas comhaid Drive (roghnach):",
        "Export settings" => "Socruithe easpórtála",
        "Import settings" => "Socruithe a allmhairiú",
        "Select Google OAuth credentials JSON" => "Roghnaigh dintiúir Google OAuth JSON",
        "OAuth status: credentials file required." => "Stádas OAuth: comhad dintiúir ag teastáil.",
        "OAuth status: error ({0})" => "Stádas OAuth: earráid ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Ní féidir dintiúir OAuth a léamh.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Stádas OAuth: ceangailte ({0}).",
        "Settings exported to:{0}{1}" => "Socruithe easpórtáilte chuig: {0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Ní féidir na socruithe a easpórtáil.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Cuirfear do chumraíocht áitiúil reatha in ionad comhad socruithe a iompórtáil. Lean ort?",
        "Unable to read the selected file.{0}{0}{1}" => "Ní féidir an comhad roghnaithe a léamh.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Níl socruithe bailí JSON sa chomhad roghnaithe.",
        "Settings imported from:{0}{1}" => "Socruithe iompórtáilte ó: {0}{1}",
        _ => english
    };
}



