namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateRo(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Export Evernote",
        "Settings" => "Setări",
        "Save" => "Salva",
        "Cancel" => "Anula",
        "App:" => "Aplicație:",
        "Refresh" => "Reîmprospăta",
        "Log out" => "Deconectați-vă",
        "Switch to" => "Comutați la",
        "Exit" => "Ieșire",
        "{0} is still running" => "{0} încă rulează",
        "Use the tray icon to reopen or exit." => "Utilizați pictograma tavă pentru a redeschide sau a ieși.",
        "Ignore" => "Ignora",
        "Ignore {0}" => "Ignorați {0}",
        "Unignore {0}" => "Anulați ignorarea {0}",
        "Set export file for {0}..." => "Setați fișierul de export pentru {0}...",
        "Clear export file name" => "Ștergeți numele fișierului de export",
        "Clear export file ({0})" => "Ștergeți fișierul de export ({0})",
        "stack" => "stivă",
        "notebook" => "caietul",
        "Select the Evernote root folder, then export the checked notebooks." => "Selectați folderul rădăcină Evernote, apoi exportați caietele bifate.",
        "Evernote Folder..." => "Folder Evernote...",
        "Reload" => "Reîncărcați",
        "Export" => "Export",
        "Evernote polling frequency (minutes):" => "Frecvența sondajului Evernote (minute):",
        "Pause automatic polling" => "Întrerupeți sondarea automată",
        "Lock: (none)" => "Blocare: (niciuna)",
        "Force" => "Vigoare",
        "State poll: every 6s, next in --s" => "Sondaj de stat: la fiecare 6 secunde, următorul în --s",
        "Keep last X markdown exports:" => "Păstrați ultimele exporturi de reducere X:",
        "Older files in ./markdown will be deleted automatically after each export." => "Fișierele mai vechi din ./markdown vor fi șterse automat după fiecare export.",
        "No Evernote folder selected." => "Niciun dosar Evernote selectat.",
        "Show ignored" => "Afișează ignorat",
        "Right-click: ignore or set export file name." => "Faceți clic dreapta: ignorați sau setați numele fișierului de export.",
        "Choose the root folder of the Evernote installation" => "Alegeți folderul rădăcină al instalării Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB detectat: {0} | Stive: {1} | Caiete: {2}",
        "DB error: {0}" => "Eroare DB: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Nu se poate citi baza de date Evernote.{0}{0}{1}",
        " [ignored]" => "[ignorat]",
        " | updated: {0}" => "| actualizat: {0}",
        " | export: {0}.md" => "| export: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} caiete){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} note){2}{3}{4}",
        "(none)" => "(nici unul)",
        "Lock: {0}" => "Blocare: {0}",
        "awaiting confirmation from {0}" => "așteaptă confirmarea de la {0}",
        "State poll: every {0}s, next in {1}s" => "Sondaj de stat: la fiecare {0}s, următorul în {1}s",
        "Export File Name" => "Nume fișier de export",
        "Export file name for {0} (without .md):" => "Exportați numele fișierului pentru {0} (fără .md):",
        "The same name lets you group multiple stacks/notebooks." => "Același nume vă permite să grupați mai multe stive/caiete.",
        "Invalid name. Use at least one valid character." => "Nume nevalid. Utilizați cel puțin un caracter valid.",
        "Language" => "Limbă",
        "Choose the UI language" => "Alegeți limba UI",
        "System default" => "Implicit de sistem",
        "Close button behavior:" => "Comportamentul butonului de închidere:",
        "Minimize to tray" => "Minimizați în tavă",
        "Close app" => "Închideți aplicația",
        "Controls what happens when you click the window close button." => "Controlează ce se întâmplă când faceți clic pe butonul de închidere a ferestrei.",
        "Enable debug logs" => "Activați jurnalele de depanare",
        "Local config file: {0}" => "Fișier de configurare local: {0}",
        "Google Drive config sync" => "Sincronizarea configurației Google Drive",
        "Enable Google Drive sync" => "Activați sincronizarea Google Drive",
        "Auto-restore at startup" => "Restaurare automată la pornire",
        "Click the button below to connect with Google OAuth." => "Faceți clic pe butonul de mai jos pentru a vă conecta la Google OAuth.",
        "Connect with Google" => "Conectați-vă cu Google",
        "OAuth status: configured." => "Stare OAuth: configurată.",
        "OAuth status: not connected." => "Stare OAuth: neconectat.",
        "OAuth status: connecting..." => "Stare OAuth: se conectează...",
        "Unknown OAuth error." => "Eroare OAuth necunoscută.",
        "OAuth status: failed ({0})" => "Stare OAuth: eșuat ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Conexiunea OAuth a eșuat.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Cont Google conectat",
        "(not detected)" => "(nedetectat)",
        "OAuth client source: {0}" => "Sursa client OAuth: {0}",
        "Drive file ID (optional):" => "ID fișierul Drive (opțional):",
        "Export settings" => "Exportați setările",
        "Import settings" => "Import setări",
        "Select Google OAuth credentials JSON" => "Selectați acreditările Google OAuth JSON",
        "OAuth status: credentials file required." => "Stare OAuth: fișierul de acreditări este necesar.",
        "OAuth status: error ({0})" => "Stare OAuth: eroare ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Nu se pot citi acreditările OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Stare OAuth: conectat ({0}).",
        "Settings exported to:{0}{1}" => "Setări exportate în:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Nu se pot exporta setările.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Importul unui fișier de setări va înlocui configurația locală actuală. Continua?",
        "Unable to read the selected file.{0}{0}{1}" => "Nu se poate citi fișierul selectat.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Fișierul selectat nu conține setări valide JSON.",
        "Settings imported from:{0}{1}" => "Setări importate din:{0}{1}",
        _ => english
    };
}



