namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateCy(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Allforio Evernote",
        "Settings" => "Gosodiadau",
        "Save" => "Arbed",
        "Cancel" => "Canslo",
        "App:" => "Ap:",
        "Refresh" => "Adnewyddu",
        "Log out" => "Allgofnodi",
        "Switch to" => "Newid i",
        "Exit" => "Ymadael",
        "{0} is still running" => "Mae {0} yn dal i redeg",
        "Use the tray icon to reopen or exit." => "Defnyddiwch eicon yr hambwrdd i ailagor neu adael.",
        "Ignore" => "Anwybyddu",
        "Ignore {0}" => "Anwybyddu {0}",
        "Unignore {0}" => "Anwybyddu {0}",
        "Set export file for {0}..." => "Gosod ffeil allforio ar gyfer {0}...",
        "Clear export file name" => "Clirio enw ffeil allforio",
        "Clear export file ({0})" => "Clirio'r ffeil allforio ({0})",
        "stack" => "pentwr",
        "notebook" => "llyfr nodiadau",
        "Select the Evernote root folder, then export the checked notebooks." => "Dewiswch y ffolder gwraidd Evernote, yna allforio y llyfrau nodiadau wedi'u gwirio.",
        "Evernote Folder..." => "Ffolder Evernote...",
        "Reload" => "Ail-lwytho",
        "Export" => "Allforio",
        "Evernote polling frequency (minutes):" => "Amlder pleidleisio Evernote (munudau):",
        "Pause automatic polling" => "Oedwch y pleidleisio awtomatig",
        "Lock: (none)" => "Clo: (dim)",
        "Force" => "Llu",
        "State poll: every 6s, next in --s" => "Pôl gwladol: bob 6s, nesaf yn --s",
        "Keep last X markdown exports:" => "Cadw'r allforion marcio X diwethaf:",
        "Older files in ./markdown will be deleted automatically after each export." => "Bydd ffeiliau hŷn yn ./markdown yn cael eu dileu yn awtomatig ar ôl pob allforio.",
        "No Evernote folder selected." => "Dim ffolder Evernote wedi'i ddewis.",
        "Show ignored" => "Anwybyddwyd y sioe",
        "Right-click: ignore or set export file name." => "De-gliciwch: anwybyddu neu osod enw ffeil allforio.",
        "Choose the root folder of the Evernote installation" => "Dewiswch ffolder gwraidd y gosodiad Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB canfod: {0} | Staciau: {1} | Llyfrau nodiadau: {2}",
        "DB error: {0}" => "Gwall DB: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Methu darllen cronfa ddata Evernote.{0}{0}{1}",
        " [ignored]" => "[anwybyddwyd]",
        " | updated: {0}" => "| wedi'i ddiweddaru: {0}",
        " | export: {0}.md" => "| allforio: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} llyfrau nodiadau){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} nodiadau){2}{3}{4}",
        "(none)" => "(dim)",
        "Lock: {0}" => "Clo: {0}",
        "awaiting confirmation from {0}" => "yn aros am gadarnhad gan {0}",
        "State poll: every {0}s, next in {1}s" => "Pôl gwladol: pob {0}s, nesaf mewn {1}s",
        "Export File Name" => "Allforio Enw Ffeil",
        "Export file name for {0} (without .md):" => "Allforio enw ffeil ar gyfer {0} (heb .md):",
        "The same name lets you group multiple stacks/notebooks." => "Mae'r un enw yn gadael i chi grwpio pentyrrau/llyfrau nodiadau lluosog.",
        "Invalid name. Use at least one valid character." => "Enw annilys. Defnyddiwch o leiaf un nod dilys.",
        "Language" => "Iaith",
        "Choose the UI language" => "Dewiswch iaith y UI",
        "System default" => "System diofyn",
        "Close button behavior:" => "Ymddygiad botwm cau:",
        "Minimize to tray" => "Lleihau i hambwrdd",
        "Close app" => "Cau app",
        "Controls what happens when you click the window close button." => "Yn rheoli beth sy'n digwydd pan fyddwch chi'n clicio ar y botwm cau ffenestr.",
        "Enable debug logs" => "Galluogi logiau dadfygio",
        "Local config file: {0}" => "Ffeil ffurfweddu lleol: {0}",
        "Google Drive config sync" => "Cysoni cyfluniad Google Drive",
        "Enable Google Drive sync" => "Galluogi cysoni Google Drive",
        "Auto-restore at startup" => "Adfer yn awtomatig wrth gychwyn",
        "Click the button below to connect with Google OAuth." => "Cliciwch y botwm isod i gysylltu â Google OAuth.",
        "Connect with Google" => "Cysylltwch â Google",
        "OAuth status: configured." => "Statws OAuth: wedi'i ffurfweddu.",
        "OAuth status: not connected." => "Statws OAuth: heb ei gysylltu.",
        "OAuth status: connecting..." => "Statws OAuth: cysylltu...",
        "Unknown OAuth error." => "Gwall OAuth anhysbys.",
        "OAuth status: failed ({0})" => "Statws OAuth: wedi methu ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Methodd cysylltiad OAuth.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Cyfrif Google wedi'i gysylltu",
        "(not detected)" => "(heb ei ganfod)",
        "OAuth client source: {0}" => "Ffynhonnell cleient OAuth: {0}",
        "Drive file ID (optional):" => "ID ffeil Drive (dewisol):",
        "Export settings" => "Gosodiadau allforio",
        "Import settings" => "Mewnforio gosodiadau",
        "Select Google OAuth credentials JSON" => "Dewiswch tystlythyrau Google OAuth JSON",
        "OAuth status: credentials file required." => "Statws OAuth: angen ffeil tystlythyrau.",
        "OAuth status: error ({0})" => "Statws OAuth: gwall ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Methu darllen manylion OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Statws OAuth: cysylltiedig ({0}).",
        "Settings exported to:{0}{1}" => "Gosodiadau wedi'u hallforio i: {0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Methu allforio gosodiadau. {0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Bydd mewnforio ffeil gosodiadau yn disodli eich ffurfweddiad lleol cyfredol. Parhau?",
        "Unable to read the selected file.{0}{0}{1}" => "Methu darllen y ffeil dewisiedig.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Nid yw'r ffeil a ddewiswyd yn cynnwys gosodiadau dilys JSON.",
        "Settings imported from:{0}{1}" => "Gosodiadau wedi'u mewnforio o: {0}{1}",
        _ => english
    };
}



