namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateBe(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Экспарт Evernote",
        "Settings" => "Налады",
        "Save" => "Захаваць",
        "Cancel" => "Адмяніць",
        "App:" => "Прыкладанне:",
        "Refresh" => "Абнавіць",
        "Log out" => "Выйсці",
        "Switch to" => "Пераключыцца на",
        "Exit" => "Выхад",
        "{0} is still running" => "{0} усё яшчэ працуе",
        "Use the tray icon to reopen or exit." => "Каб паўторна адкрыць або выйсці, выкарыстоўвайце значок у панэлі.",
        "Ignore" => "Ігнараваць",
        "Ignore {0}" => "Ігнараваць {0}",
        "Unignore {0}" => "Не ігнараваць {0}",
        "Set export file for {0}..." => "Усталяваць файл экспарту для {0}...",
        "Clear export file name" => "Ачысціць назву файла экспарту",
        "Clear export file ({0})" => "Ачысціць файл экспарту ({0})",
        "stack" => "стэк",
        "notebook" => "нататнік",
        "Select the Evernote root folder, then export the checked notebooks." => "Выберыце каранёвую тэчку Evernote, затым экспартуйце адзначаныя сшыткі.",
        "Evernote Folder..." => "Папка Evernote...",
        "Reload" => "Перазагрузіць",
        "Export" => "Экспарт",
        "Evernote polling frequency (minutes):" => "Частата апытання Evernote (у хвілінах):",
        "Pause automatic polling" => "Прыпыніць аўтаматычнае апытанне",
        "Lock: (none)" => "Блакаванне: (няма)",
        "Force" => "Сіла",
        "State poll: every 6s, next in --s" => "Дзяржаўнае апытанне: кожныя 6 с, наступнае праз --с",
        "Keep last X markdown exports:" => "Захаваць апошнія X экспарту ўцэнкі:",
        "Older files in ./markdown will be deleted automatically after each export." => "Старыя файлы ў ./markdown будуць аўтаматычна выдаляцца пасля кожнага экспарту.",
        "No Evernote folder selected." => "Папка Evernote не выбрана.",
        "Show ignored" => "Шоу праігнаравана",
        "Right-click: ignore or set export file name." => "Пстрыкніце правай кнопкай мышы: ігнаруйце або задайце імя файла экспарту.",
        "Choose the root folder of the Evernote installation" => "Выберыце каранёвую тэчку ўстаноўкі Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "Выяўлена БД: {0} | Стосы: {1} | Сшыткі: {2}",
        "DB error: {0}" => "Памылка БД: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Немагчыма прачытаць базу дадзеных Evernote.{0}{0}{1}",
        " [ignored]" => "[ігнаруецца]",
        " | updated: {0}" => "| абноўлена: {0}",
        " | export: {0}.md" => "| экспарт: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} сшыткі){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} нататкі){2}{3}{4}",
        "(none)" => "(няма)",
        "Lock: {0}" => "Блакаванне: {0}",
        "awaiting confirmation from {0}" => "чакаецца пацвярджэнне ад {0}",
        "State poll: every {0}s, next in {1}s" => "Апытанне штата: кожныя {0} с, наступнае праз {1} с",
        "Export File Name" => "Імя файла экспарту",
        "Export file name for {0} (without .md):" => "Імя файла экспарту для {0} (без .md):",
        "The same name lets you group multiple stacks/notebooks." => "Адна і тая ж назва дазваляе групаваць некалькі стосаў/сшыткаў.",
        "Invalid name. Use at least one valid character." => "Няправільнае імя. Выкарыстоўвайце хаця б адзін сапраўдны сімвал.",
        "Language" => "мова",
        "Choose the UI language" => "Выберыце мову інтэрфейсу",
        "System default" => "Сістэма па змаўчанні",
        "Close button behavior:" => "Паводзіны кнопкі закрыцця:",
        "Minimize to tray" => "Згарнуць у латок",
        "Close app" => "Зачыніць праграму",
        "Controls what happens when you click the window close button." => "Кантралюе тое, што адбываецца, калі вы націскаеце кнопку закрыцця акна.",
        "Enable debug logs" => "Уключыць журналы адладкі",
        "Local config file: {0}" => "Лакальны файл канфігурацыі: {0}",
        "Google Drive config sync" => "Сінхранізацыя канфігурацыі Google Drive",
        "Enable Google Drive sync" => "Уключыць сінхранізацыю Google Drive",
        "Auto-restore at startup" => "Аўтаматычнае аднаўленне пры запуску",
        "Click the button below to connect with Google OAuth." => "Націсніце кнопку ніжэй, каб падключыцца да Google OAuth.",
        "Connect with Google" => "Падключыцеся да Google",
        "OAuth status: configured." => "Статус OAuth: наладжаны.",
        "OAuth status: not connected." => "Статус OAuth: не падключана.",
        "OAuth status: connecting..." => "Статус OAuth: падключэнне...",
        "Unknown OAuth error." => "Невядомая памылка OAuth.",
        "OAuth status: failed ({0})" => "Статус OAuth: збой ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Збой злучэння OAuth.{0}{0}{1}",
        "Google Drive OAuth" => "Google Drive OAuth",
        "Google account connected" => "Уліковы запіс Google падключаны",
        "(not detected)" => "(не выяўлена)",
        "OAuth client source: {0}" => "Крыніца кліента OAuth: {0}",
        "Drive file ID (optional):" => "Ідэнтыфікатар файла дыска (неабавязкова):",
        "Export settings" => "Экспарт параметраў",
        "Import settings" => "Налады імпарту",
        "Select Google OAuth credentials JSON" => "Выберыце ўліковыя даныя Google OAuth JSON",
        "OAuth status: credentials file required." => "Статус OAuth: патрабуецца файл уліковых даных.",
        "OAuth status: error ({0})" => "Статус OAuth: памылка ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Немагчыма прачытаць уліковыя дадзеныя OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Статус OAuth: падключаны ({0}).",
        "Settings exported to:{0}{1}" => "Налады экспартаваны ў: {0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Немагчыма экспартаваць налады.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "Імпарт файла налад заменіць бягучую лакальную канфігурацыю. Працягнуць?",
        "Unable to read the selected file.{0}{0}{1}" => "Немагчыма прачытаць выбраны файл.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Выбраны файл не ўтрымлівае сапраўдных налад JSON.",
        "Settings imported from:{0}{1}" => "Налады імпартаваны з: {0}{1}",
        _ => english
    };
}



