namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateKo(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "구글 드라이브",
        "Evernote Export" => "Evernote 내보내기",
        "Settings" => "설정",
        "Save" => "구하다",
        "Cancel" => "취소",
        "App:" => "앱:",
        "Refresh" => "새로 고치다",
        "Log out" => "로그아웃",
        "Switch to" => "다음으로 전환",
        "Exit" => "출구",
        "{0} is still running" => "{0}이(가) 아직 실행 중입니다.",
        "Use the tray icon to reopen or exit." => "다시 열거나 종료하려면 트레이 아이콘을 사용하세요.",
        "Ignore" => "무시하다",
        "Ignore {0}" => "{0} 무시",
        "Unignore {0}" => "무시하지 않음 {0}",
        "Set export file for {0}..." => "{0}에 대한 내보내기 파일 설정...",
        "Clear export file name" => "내보내기 파일 이름 지우기",
        "Clear export file ({0})" => "내보내기 파일 지우기({0})",
        "stack" => "스택",
        "notebook" => "공책",
        "Select the Evernote root folder, then export the checked notebooks." => "Evernote 루트 폴더를 선택한 다음, 확인된 노트북을 내보냅니다.",
        "Evernote Folder..." => "에버노트 폴더...",
        "Reload" => "새로고침",
        "Export" => "내보내다",
        "Evernote polling frequency (minutes):" => "Evernote 폴링 빈도(분):",
        "Pause automatic polling" => "자동 폴링 일시중지",
        "Lock: (none)" => "잠금: (없음)",
        "Force" => "힘",
        "State poll: every 6s, next in --s" => "상태 폴링: 6초마다, --s의 다음",
        "Keep last X markdown exports:" => "마지막 X 마크다운 내보내기 유지:",
        "Older files in ./markdown will be deleted automatically after each export." => "./markdown의 이전 파일은 내보낼 때마다 자동으로 삭제됩니다.",
        "No Evernote folder selected." => "Evernote 폴더가 선택되지 않았습니다.",
        "Show ignored" => "무시된 표시",
        "Right-click: ignore or set export file name." => "마우스 오른쪽 버튼 클릭: 내보내기 파일 이름을 무시하거나 설정합니다.",
        "Choose the root folder of the Evernote installation" => "Evernote 설치의 루트 폴더를 선택하세요",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB 감지됨: {0} | 스택: {1} | 노트북: {2}",
        "DB error: {0}" => "DB 오류: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Evernote 데이터베이스를 읽을 수 없습니다.{0}{0}{1}",
        " [ignored]" => "[무시]",
        " | updated: {0}" => "| 업데이트됨: {0}",
        " | export: {0}.md" => "| 내보내기: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} 노트북){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} 메모){2}{3}{4}",
        "(none)" => "(없음)",
        "Lock: {0}" => "잠금: {0}",
        "awaiting confirmation from {0}" => "{0}의 확인을 기다리는 중",
        "State poll: every {0}s, next in {1}s" => "상태 폴링: {0}s마다, 다음은 {1}s",
        "Export File Name" => "내보내기 파일 이름",
        "Export file name for {0} (without .md):" => "{0}에 대한 파일 이름 내보내기(.md 제외):",
        "The same name lets you group multiple stacks/notebooks." => "동일한 이름을 사용하면 여러 스택/노트북을 그룹화할 수 있습니다.",
        "Invalid name. Use at least one valid character." => "이름이 잘못되었습니다. 유효한 문자를 하나 이상 사용하세요.",
        "Language" => "언어",
        "Choose the UI language" => "UI 언어 선택",
        "System default" => "시스템 기본값",
        "Close button behavior:" => "닫기 버튼 동작:",
        "Minimize to tray" => "트레이로 최소화",
        "Close app" => "앱 닫기",
        "Controls what happens when you click the window close button." => "창 닫기 버튼을 클릭할 때 발생하는 상황을 제어합니다.",
        "Enable debug logs" => "디버그 로그 활성화",
        "Local config file: {0}" => "로컬 구성 파일: {0}",
        "Google Drive config sync" => "Google 드라이브 구성 동기화",
        "Enable Google Drive sync" => "Google 드라이브 동기화 활성화",
        "Auto-restore at startup" => "시작 시 자동 복원",
        "Click the button below to connect with Google OAuth." => "아래 버튼을 클릭하시면 Google OAuth로 연결됩니다.",
        "Connect with Google" => "Google과 연결",
        "OAuth status: configured." => "OAuth 상태: 구성됨.",
        "OAuth status: not connected." => "OAuth 상태: 연결되지 않았습니다.",
        "OAuth status: connecting..." => "OAuth 상태: 연결 중...",
        "Unknown OAuth error." => "알 수 없는 OAuth 오류입니다.",
        "OAuth status: failed ({0})" => "OAuth 상태: 실패({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth 연결에 실패했습니다.{0}{0}{1}",
        "Google Drive OAuth" => "Google 드라이브 OAuth",
        "Google account connected" => "Google 계정이 연결되었습니다",
        "(not detected)" => "(감지되지 않음)",
        "OAuth client source: {0}" => "OAuth 클라이언트 소스: {0}",
        "Drive file ID (optional):" => "드라이브 파일 ID(선택사항):",
        "Export settings" => "설정 내보내기",
        "Import settings" => "가져오기 설정",
        "Select Google OAuth credentials JSON" => "Google OAuth 자격 증명 JSON 선택",
        "OAuth status: credentials file required." => "OAuth 상태: 자격 증명 파일이 필요합니다.",
        "OAuth status: error ({0})" => "OAuth 상태: 오류({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "OAuth 자격 증명을 읽을 수 없습니다.{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth 상태: 연결됨({0}).",
        "Settings exported to:{0}{1}" => "내보낸 설정:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "설정을 내보낼 수 없습니다.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "설정 파일을 가져오면 현재 로컬 구성이 대체됩니다. 계속하다?",
        "Unable to read the selected file.{0}{0}{1}" => "선택한 파일을 읽을 수 없습니다.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "선택한 파일에 유효한 설정 JSON이 포함되어 있지 않습니다.",
        "Settings imported from:{0}{1}" => "다음에서 가져온 설정:{0}{1}",
        _ => english
    };
}



