namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateIt(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "Google Drive",
        "Evernote Export" => "Esportazione Evernote",
        "Settings" => "Impostazioni",
        "Save" => "Salva",
        "Cancel" => "Cancellare",
        "App:" => "Applicazione:",
        "Refresh" => "Aggiorna",
        "Log out" => "Esci",
        "Switch to" => "Passa a",
        "Exit" => "Uscita",
        "{0} is still running" => "{0} è ancora in esecuzione",
        "Use the tray icon to reopen or exit." => "Utilizzare l'icona nella barra delle applicazioni per riaprire o uscire.",
        "Ignore" => "Ignorare",
        "Ignore {0}" => "Ignora {0}",
        "Unignore {0}" => "Non ignorare {0}",
        "Set export file for {0}..." => "Imposta il file di esportazione per {0}...",
        "Clear export file name" => "Cancella il nome del file di esportazione",
        "Clear export file ({0})" => "Cancella file di esportazione ({0})",
        "stack" => "pila",
        "notebook" => "taccuino",
        "Select the Evernote root folder, then export the checked notebooks." => "Seleziona la cartella principale Evernote, quindi esporta i taccuini selezionati.",
        "Evernote Folder..." => "Cartella Evernote...",
        "Reload" => "Ricaricare",
        "Export" => "Esportare",
        "Evernote polling frequency (minutes):" => "Frequenza dei sondaggi Evernote (minuti):",
        "Pause automatic polling" => "Mettere in pausa il polling automatico",
        "Lock: (none)" => "Blocco: (nessuno)",
        "Force" => "Forza",
        "State poll: every 6s, next in --s" => "Sondaggio statale: ogni 6 secondi, successivo tra --s",
        "Keep last X markdown exports:" => "Mantieni le ultime X esportazioni di ribasso:",
        "Older files in ./markdown will be deleted automatically after each export." => "I file più vecchi in ./markdown verranno eliminati automaticamente dopo ogni esportazione.",
        "No Evernote folder selected." => "Nessuna cartella Evernote selezionata.",
        "Show ignored" => "Mostra ignorato",
        "Right-click: ignore or set export file name." => "Fare clic con il tasto destro: ignora o imposta il nome del file di esportazione.",
        "Choose the root folder of the Evernote installation" => "Scegli la cartella principale dell'installazione di Evernote",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "DB rilevato: {0} | Pile: {1} | Taccuini: {2}",
        "DB error: {0}" => "Errore DB: {0}",
        "Unable to read Evernote database.{0}{0}{1}" => "Impossibile leggere il database Evernote.{0}{0}{1}",
        " [ignored]" => "[ignorato]",
        " | updated: {0}" => "| aggiornato: {0}",
        " | export: {0}.md" => "| esporta: {0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0} ({1} quaderni){2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0} ({1} note){2}{3}{4}",
        "(none)" => "(nessuno)",
        "Lock: {0}" => "Blocco: {0}",
        "awaiting confirmation from {0}" => "in attesa di conferma da {0}",
        "State poll: every {0}s, next in {1}s" => "Sondaggio statale: ogni {0}s, successivo tra {1}s",
        "Export File Name" => "Esporta nome file",
        "Export file name for {0} (without .md):" => "Esporta il nome del file per {0} (senza .md):",
        "The same name lets you group multiple stacks/notebooks." => "Lo stesso nome ti consente di raggruppare più pile/taccuini.",
        "Invalid name. Use at least one valid character." => "Nome non valido. Utilizza almeno un carattere valido.",
        "Language" => "Lingua",
        "Choose the UI language" => "Scegli la lingua dell'interfaccia utente",
        "System default" => "Predefinito del sistema",
        "Close button behavior:" => "Comportamento del pulsante Chiudi:",
        "Minimize to tray" => "Ridurre a icona nel vassoio",
        "Close app" => "Chiudi l'app",
        "Controls what happens when you click the window close button." => "Controlla cosa succede quando fai clic sul pulsante di chiusura della finestra.",
        "Enable debug logs" => "Abilita i log di debug",
        "Local config file: {0}" => "File di configurazione locale: {0}",
        "Google Drive config sync" => "Sincronizzazione della configurazione di Google Drive",
        "Enable Google Drive sync" => "Abilita la sincronizzazione di Google Drive",
        "Auto-restore at startup" => "Ripristino automatico all'avvio",
        "Click the button below to connect with Google OAuth." => "Fai clic sul pulsante in basso per connetterti con Google OAuth.",
        "Connect with Google" => "Connettiti con Google",
        "OAuth status: configured." => "Stato OAuth: configurato.",
        "OAuth status: not connected." => "Stato OAuth: non connesso.",
        "OAuth status: connecting..." => "Stato OAuth: connessione in corso...",
        "Unknown OAuth error." => "Errore OAuth sconosciuto.",
        "OAuth status: failed ({0})" => "Stato OAuth: non riuscito ({0})",
        "OAuth connection failed.{0}{0}{1}" => "Connessione OAuth non riuscita.{0}{0}{1}",
        "Google Drive OAuth" => "OAuth di Google Drive",
        "Google account connected" => "Account Google collegato",
        "(not detected)" => "(non rilevato)",
        "OAuth client source: {0}" => "Origine client OAuth: {0}",
        "Drive file ID (optional):" => "ID file dell'unità (facoltativo):",
        "Export settings" => "Impostazioni di esportazione",
        "Import settings" => "Importa impostazioni",
        "Select Google OAuth credentials JSON" => "Seleziona le credenziali OAuth di Google JSON",
        "OAuth status: credentials file required." => "Stato OAuth: file delle credenziali obbligatorio.",
        "OAuth status: error ({0})" => "Stato OAuth: errore ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "Impossibile leggere le credenziali OAuth.{0}{0}{1}",
        "OAuth status: connected ({0})." => "Stato OAuth: connesso ({0}).",
        "Settings exported to:{0}{1}" => "Impostazioni esportate in:{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "Impossibile esportare le impostazioni.{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "L'importazione di un file di impostazioni sostituirà la configurazione locale corrente. Continuare?",
        "Unable to read the selected file.{0}{0}{1}" => "Impossibile leggere il file selezionato.{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "Il file selezionato non contiene impostazioni JSON valide.",
        "Settings imported from:{0}{1}" => "Impostazioni importate da:{0}{1}",
        _ => english
    };
}



