namespace WinGemini;

internal static partial class UiLanguageService
{
    private static string TranslateZhHans(string english) => english switch
    {
        "Gemini" => "Gemini",
        "NotebookLM" => "NotebookLM",
        "Google Drive" => "谷歌云端硬盘",
        "Evernote Export" => "印象笔记导出",
        "Settings" => "设置",
        "Save" => "节省",
        "Cancel" => "取消",
        "App:" => "应用程序：",
        "Refresh" => "刷新",
        "Log out" => "退出",
        "Switch to" => "切换到",
        "Exit" => "出口",
        "{0} is still running" => "{0} 仍在运行",
        "Use the tray icon to reopen or exit." => "使用托盘图标重新打开或退出。",
        "Ignore" => "忽略",
        "Ignore {0}" => "忽略 {0}",
        "Unignore {0}" => "忽略 {0}",
        "Set export file for {0}..." => "设置导出文件为 {0}...",
        "Clear export file name" => "清除导出文件名",
        "Clear export file ({0})" => "清除导出文件 ({0})",
        "stack" => "堆",
        "notebook" => "笔记本",
        "Select the Evernote root folder, then export the checked notebooks." => "选择 Evernote 根文件夹，然后导出选中的笔记本。",
        "Evernote Folder..." => "印象笔记文件夹...",
        "Reload" => "重新加载",
        "Export" => "出口",
        "Evernote polling frequency (minutes):" => "Evernote 投票频率（分钟）：",
        "Pause automatic polling" => "暂停自动轮询",
        "Lock: (none)" => "锁：（无）",
        "Force" => "力量",
        "State poll: every 6s, next in --s" => "状态民意调查：每 6 秒一次，下一个 --s 后",
        "Keep last X markdown exports:" => "保留最后 X 个降价导出：",
        "Older files in ./markdown will be deleted automatically after each export." => "每次导出后，./markdown 中的旧文件将被自动删除。",
        "No Evernote folder selected." => "未选择 Evernote 文件夹。",
        "Show ignored" => "显示忽略",
        "Right-click: ignore or set export file name." => "右键单击：忽略或设置导出文件名。",
        "Choose the root folder of the Evernote installation" => "选择 Evernote 安装的根文件夹",
        "DB detected: {0} | Stacks: {1} | Notebooks: {2}" => "检测到数据库：{0} |堆栈：{1} |笔记本：{2}",
        "DB error: {0}" => "数据库错误：{0}",
        "Unable to read Evernote database.{0}{0}{1}" => "无法读取 Evernote 数据库。{0}{0}{1}",
        " [ignored]" => "[忽略]",
        " | updated: {0}" => "|更新：{0}",
        " | export: {0}.md" => "|导出：{0}.md",
        "{0} ({1} notebooks){2}{3}{4}" => "{0}（{1} 笔记本）{2}{3}{4}",
        "{0} ({1} notes){2}{3}{4}" => "{0}（{1} 注释）{2}{3}{4}",
        "(none)" => "（没有任何）",
        "Lock: {0}" => "锁：{0}",
        "awaiting confirmation from {0}" => "等待 {0} 的确认",
        "State poll: every {0}s, next in {1}s" => "州民意调查：每 {0} 秒，下一个 {1} 秒",
        "Export File Name" => "导出文件名",
        "Export file name for {0} (without .md):" => "{0} 的导出文件名（不带 .md）：",
        "The same name lets you group multiple stacks/notebooks." => "相同的名称可让您对多个堆栈/笔记本进行分组。",
        "Invalid name. Use at least one valid character." => "名称无效。至少使用一个有效字符。",
        "Language" => "语言",
        "Choose the UI language" => "选择用户界面语言",
        "System default" => "系统默认",
        "Close button behavior:" => "关闭按钮行为：",
        "Minimize to tray" => "最小化到托盘",
        "Close app" => "关闭应用程序",
        "Controls what happens when you click the window close button." => "控制单击窗口关闭按钮时发生的情况。",
        "Enable debug logs" => "启用调试日志",
        "Local config file: {0}" => "本地配置文件：{0}",
        "Google Drive config sync" => "Google 云端硬盘配置同步",
        "Enable Google Drive sync" => "启用 Google 云端硬盘同步",
        "Auto-restore at startup" => "启动时自动恢复",
        "Click the button below to connect with Google OAuth." => "单击下面的按钮连接 Google OAuth。",
        "Connect with Google" => "与谷歌连接",
        "OAuth status: configured." => "OAuth 状态：已配置。",
        "OAuth status: not connected." => "OAuth 状态：未连接。",
        "OAuth status: connecting..." => "OAuth 状态：正在连接...",
        "Unknown OAuth error." => "未知的 OAuth 错误。",
        "OAuth status: failed ({0})" => "OAuth 状态：失败 ({0})",
        "OAuth connection failed.{0}{0}{1}" => "OAuth 连接失败。{0}{0}{1}",
        "Google Drive OAuth" => "谷歌云端硬盘 OAuth",
        "Google account connected" => "已连接 Google 帐户",
        "(not detected)" => "（未检测到）",
        "OAuth client source: {0}" => "OAuth 客户端来源：{0}",
        "Drive file ID (optional):" => "驱动器文件 ID（可选）：",
        "Export settings" => "导出设置",
        "Import settings" => "导入设置",
        "Select Google OAuth credentials JSON" => "选择 Google OAuth 凭证 JSON",
        "OAuth status: credentials file required." => "OAuth 状态：需要凭据文件。",
        "OAuth status: error ({0})" => "OAuth 状态：错误 ({0})",
        "Unable to read OAuth credentials.{0}{0}{1}" => "无法读取 OAuth 凭据。{0}{0}{1}",
        "OAuth status: connected ({0})." => "OAuth 状态：已连接 ({0})。",
        "Settings exported to:{0}{1}" => "设置导出到：{0}{1}",
        "Unable to export settings.{0}{0}{1}" => "无法导出设置。{0}{0}{1}",
        "Importing a settings file will replace your current local configuration. Continue?" => "导入设置文件将替换您当前的本地配置。继续？",
        "Unable to read the selected file.{0}{0}{1}" => "无法读取所选文件。{0}{0}{1}",
        "The selected file does not contain valid settings JSON." => "所选文件不包含有效的设置 JSON。",
        "Settings imported from:{0}{1}" => "设置导入自：{0}{1}",
        _ => english
    };
}



